### ISSUE TITLE
Idea: steamuser / serveruser - workshop only in steamuser

### ISSUE THREAD

**Issue by j0nxs** [arkmanager/ark-server-tools#1008]
Hello,

I run a server on a vps with arkmanager.
I set it up as follows:
- serveruser ark (/srv/ark)
- steamuser steam (/opt/steam)

+ Two Ark Servers share the same directory (/srv/ark/ShooterGame) 
[ has problems with arkmanager (update and restart servers ) ]
   - request for single ark installation support
+ Problem with automatic mod update. Mods are installed in /srv/ark/Steam ... - because SteamCMD use the $HOME variable to locate the library - I think its better to store the steam library in /opt/steam or add a option for it. - I solve this temporary by adding HOME=/opt/steam in top of the arkmanager script. 
I think that is the problematic line, but im not sure if its solve all of that.
Best option is to make that configurable (workshop_user) or switchable (store workshop in serveruser or steamuser)

```bash
#
# SteamCMD helper function
#
function runSteamCMD(){
  "$steamcmdroot/$steamcmdexec" +@NoPromptForPassword 1 ${steamcmd_cmds_prelogin} +login ${steamlogin:-anonymous} ${steamcmd_cmds_postlogin} "$@" +quit
}
```

Set HOME=xyz or add a su - {steamuser} "command"? 

I think some people try a similar setup, it would be nice to support it.

**Comment by klightspeed** [comment]
1911a67 adds a `steamcmdhome` option to override `$HOME` when running steamcmd

**Comment by j0nxs** [comment]
You don't understand me correctly, i know from this patch, but it isn't work correctly. $HOME is not overritten on the correct place.

**Comment by klightspeed** [comment]
`HOME="${steamcmdhome}" $cmd $args` will set `HOME` for the `$cmd` being run.

**Comment by j0nxs** [comment]
I had installed the latest version and i tested it. But it downloads in the wrong folder not in steamuser, after i write HOME=/path/to/steamcmd, works everything.

**Comment by klightspeed** [comment]
Please add `arkstUnstable=yes` to your `arkmanager.cfg` (or add `--unstable` to your netinstall command line) to enable following the head of the master branch instead of just the latest release.
