### ISSUE TITLE
updating

### ISSUE THREAD

**Issue by X0lfm4n** [arkmanager/ark-server-tools#1011]
I have this parameter via crontab -e inserted, however, the server or the mods is not updated

*/30 * * * * ./ark-server-tools/tools/arkmanager update --check --update-mods --warn --saveworld @Island

**Comment by quietMichael** [comment]
I have the same problem with me Do not update the server independently.

**Comment by klightspeed** [comment]
`--check` is not a recognised option, so you'll be getting this in your mail or dead.letter:
```
Unrecognized option --check
Try 'arkmanager -h' or 'arkmanager --help' for more information
```

**Comment by quietMichael** [comment]
klightspeed Hi Can you give me a cron that checks every 30min and then updates the server and reboots? Would be mega!
greetings

**Comment by klightspeed** [comment]
`arkmanager update --update-mods --warn` should check for updates , then update the server.

If you have a staging directory then it will update the staging directory, stop the server, update the game directory, and restart the server.

If you don't have a staging directory, then it will stop the server before downloading the game server update.

**Comment by quietMichael** [comment]
Only this? arkmanager update --update-mods --warn

**Comment by X0lfm4n** [comment]
thanks for the help @klightspeed that work

**Comment by X0lfm4n** [comment]
sry must reopen it, the servers restart again and again although there is no update

**Comment by klightspeed** [comment]
What is the output of `arkmanager checkupdate @island checkmodupdate @island`?

**Comment by X0lfm4n** [comment]
i start the server normaly with arkmanager start @Island

and in the crontab -e i have stand:
*/30 * * * * ./ark-server-tools/tools/arkmanager update --update-mods --warn --saveworld @Island called i dont see any output.

after the 30 minutes the server shutdown with warning but there is no server or mod update

**Comment by klightspeed** [comment]
What is the output of `arkmanager checkupdate @island checkmodupdate @island`?

**Comment by X0lfm4n** [comment]
oh sry you have wrote other parameters, i check it

**Comment by klightspeed** [comment]
That is very odd that there is no output.

The output of `checkupdate` should be something like:
```
Querying Steam database for latest version...
Current version: 3562785
Available version: 3562785
Your server is up to date!
```

The output of `checkmodupdate` should be something like:
```
All mods are up to date
```
if all mods are up-to-date, or:
```
Mod 1618319057 [Dino Bars] has been updated on the Steam workshop
Local last updated: 31 Jan 2019 8:27am
Steam last updated: 12 Feb 2019 10:36am
```
if it's been updated.

**Comment by X0lfm4n** [comment]
ok, I have always entered it in the crontab and not running in the console

`ark@rs002617:~$ ./ark-server-tools/tools/arkmanager checkupdate @Test checkmodupdate @Test
Running command 'checkupdate' for instance 'Test'
Current version:  3562785
Available version:  3562785
Your server is up to date!
Running command 'checkmodupdate' for instance 'Test'
Error: appworkshop_346110.acf not found at /home/ark/steam/Steam/steamapps/workshop
./ark-server-tools/tools/arkmanager: line 2448: /home/ark/steam/Steam/steamapps/workshop/content/346110/1445181373/mod.info: No such file or directory
./ark-server-tools/tools/arkmanager: line 2448: /home/ark/steam/Steam/steamapps/workshop/content/346110/731604991/mod.info: No such file or directory
./ark-server-tools/tools/arkmanager: line 2448: /home/ark/steam/Steam/steamapps/workshop/content/346110/895711211/mod.info: No such file or directory
./ark-server-tools/tools/arkmanager: line 2448: /home/ark/steam/Steam/steamapps/workshop/content/346110/918231138/mod.info: No such file or directory
./ark-server-tools/tools/arkmanager: line 2448: /home/ark/steam/Steam/steamapps/workshop/content/346110/924619115/mod.info: No such file or directory
`

**Comment by klightspeed** [comment]
That missing `appworkshop_346110.acf` file suggests that you don't have the workshop directory set correctly.

**Comment by X0lfm4n** [comment]
there is no option in the config only steamcmd_workshoplog

**Comment by klightspeed** [comment]
Please try locating `appworkshop_346110.acf`, and set `steamworkshopdir` to the directory that contains that file.  It looks like your install of `steamcmd` locates the workshop directory in a non-standard directory.

**Comment by X0lfm4n** [comment]
the file was located at
`/home/ark/steam/steamapps/workshop/appworkshop_346110.acf
/home/ark/steam/steam/steamapps/workshop/appworkshop_346110.acf`
what must i change?

**Comment by klightspeed** [comment]
Please note that Linux is case sensitive, so you will need to make sure you have the correct case.

Which of those files was most recently modified.  In arkmanager.cfg, set `steamworkshopdir` to the path of the directory containing that file (e.g. `steamworkshopdir=/home/ark/steam/steam/steamapps/workshop`)

**Comment by X0lfm4n** [comment]
i have put it in both files:

```
/etc/arkmanager/arkmanager.cfg
/home/ark/ark-server-tools/tools/arkmanager.cfg
```

in different white:
```
steamworkshopdir=/home/ark/steam/Steam/steamapps/workshop
steamworkshopdir="/home/ark/steam/Steam/steamapps/workshop"
steamcmd_workshopdir=/home/ark/steam/Steam/steamapps/workshop
steamcmd_workshopdir="/home/ark/steam/Steam/steamapps/workshop"
```

but I always get the same message
`ark@rs002617:~$ ./ark-server-tools/tools/arkmanager checkupdate @Test checkmodupdate @Test
Running command 'checkupdate' for instance 'Test'
Current version:  3562785
Available version:  3562785
Your server is up to date!
Running command 'checkmodupdate' for instance 'Test'
Error: appworkshop_346110.acf not found at /home/ark/steam/Steam/steamapps/workshop
./ark-server-tools/tools/arkmanager: line 2448: /home/ark/steam/Steam/steamapps/workshop/content/346110/1445181373/mod.info: No such file or directory
./ark-server-tools/tools/arkmanager: line 2448: /home/ark/steam/Steam/steamapps/workshop/content/346110/731604991/mod.info: No such file or directory
./ark-server-tools/tools/arkmanager: line 2448: /home/ark/steam/Steam/steamapps/workshop/content/346110/895711211/mod.info: No such file or directory
./ark-server-tools/tools/arkmanager: line 2448: /home/ark/steam/Steam/steamapps/workshop/content/346110/918231138/mod.info: No such file or directory
./ark-server-tools/tools/arkmanager: line 2448: /home/ark/steam/Steam/steamapps/workshop/content/346110/924619115/mod.info: No such file or directory
`

**Comment by klightspeed** [comment]
So you're telling it to look where it's already been looking.

If you run `ls -l --color=always /home/ark/steam/Steam/steamapps/workshop`, what colour is `appworkshop_346110.acf`?

If it's red, this means it's a symlink referring to a non-existent file.  If that is the case, that suggests you used `cp -s` (`--symbolic-link`) when copying the steam workshop directory, in which case it'd be best to delete the workshop directory and re-download the mods.

Does anything change after running `arkmanager installmods @Test`

**Comment by X0lfm4n** [comment]
no its not red

`ark@rs002617:~$ ls -l --color=always /home/ark/steam/Steam/steamapps/workshop
total 4
drwxr-xr-x 2 ark ark 4096 Mar  6 12:19 content`

**Comment by klightspeed** [comment]
Does anything change after running `arkmanager installmods @Test`

**Comment by X0lfm4n** [comment]
with this command he install all mods from the other server on this test server even though only one mod is in the test server config

**Comment by klightspeed** [comment]
Let me guess - you have a cron job deleting the workshop directory?

**Comment by X0lfm4n** [comment]
no, I do not have, I just want that he looks over crontab every x minutes whether for the server or a mod an update then gives the - warning there, the server goes down updatet and starts again.

the only thing I have in crontab in it once a day I have a restart

**Comment by klightspeed** [comment]
What is the output of the following commands when run from the console under the context of the ark user:
```
~/ark-server-tools/tools/arkmanager installmods @Test
find ~ -type d -name 'appworkshop_346110.acf' -ls
```

**Comment by X0lfm4n** [comment]
`ark@rs002617:~$ ./ark-server-tools/tools/arkmanager installmods @Test
Running command 'installmods' for instance 'Test'
Downloading mod 731604991 ... Mod 731604991 downloaded
Copying files to /home/ark/server/Test/ShooterGame/Content/Mods/731604991
Mod 731604991 installed
ark@rs002617:~$ find ~ -type d -name 'appworkshop_346110.acf' -ls
ark@rs002617:~$
`

**Comment by klightspeed** [comment]
What about `./ark-server-tools/tools/arkmanager installmods --verbose @Test`

**Comment by X0lfm4n** [comment]
``ark@rs002617:~$ ./ark-server-tools/tools/arkmanager installmods --verbose @Test
Running command 'installmods' for instance 'Test'
Downloading mod 731604991Executing /home/ark/steamcmd/steamcmd.sh +@NoPromptForPassword 1 +login anonymous +workshop_download_item 346110 731604991 +quit
Redirecting stderr to '/home/ark/steam/Steam/logs/stderr.txt'
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.
"@NoPromptForPassword" = "1"

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
Downloading item 731604991 ...
Success. Downloaded item 731604991 to "/home/ark/steam/steam/steamapps/workshop/content/346110/731604991" (56080923 bytes) Mod 731604991 downloaded
Copying files to /home/ark/server/Test/ShooterGame/Content/Mods/731604991
Mod 731604991 installed

**Comment by klightspeed** [comment]
So it is in fact lower-case, where you have been using upper-case.

**Comment by X0lfm4n** [comment]
so what can I do?

**Comment by klightspeed** [comment]
Please check the permissions on `/home/ark/steam/steam/steamapps/workshop` - I duplicated the missing `appworkshop_346110.acf` by making `/home/ark/steam/steam/steamapps/workshop` non-writable.

Also, please try setting `steamworkshopdir=/home/ark/steam/steam/steamapps/workshop` (note the lower-case)

**Comment by X0lfm4n** [comment]
i have change the permission for `/home/ark/steam/steam/steamapps/workshop` from 755 to 555 and insert `steamworkshopdir=/home/ark/steam/steam/steamapps/workshop` in /etc/arkmanager/arkmanager.cfg and /home/ark/ark/ark-server-tools/tools/arkmanager.cfg

**Comment by klightspeed** [comment]
What are you doin?

I said I __replicated__ your issue by making the directory non-writable, which means that the fix should be to make sure that the directory is owned by the user and is writable (0755)

**Comment by X0lfm4n** [comment]
ah ok then I've got it wrong I've already wondered, I have the directories back to 0755
