### ISSUE TITLE
Can't update server to latest version

### ISSUE THREAD

**Issue by akmaslov** [arkmanager/ark-server-tools#1021]
I can't seem to update the server to latest version. When I run:

sudo arkmanager checkupdate \@main 

I get the following output:

Running command 'checkupdate' for instance 'main'
Querying Steam database for latest version...
Current version:  3912455 
Available version:  
Your server is up to date!

Using the --force flag doesn't seem to do the trick either.

**Comment by klightspeed** [comment]
Does it work if you don't use sudo?

**Comment by akmaslov** [comment]
Probably not; I always use sudo to run the arkmanager commands.

**Comment by klightspeed** [comment]
The empty available version, and --force not working, suggests that your steamcmd install may be corrupt.  Please try removing and re-extracting steamcmd.

**Comment by akmaslov** [comment]
For future generations. 

The problem was simple: I was out of space on the disk. Once I freed up some bits (Ark is a massive hog), the problem went away. I'm sure there's an error being hidden here somewhere.
