### ISSUE TITLE
Trying to play with friends, but it's just not working

### ISSUE THREAD

**Issue by tr1pped0ut** [arkmanager/ark-server-tools#1023]
I've been working for hours to try to figure this out. The server shows up in lan with my computer ip but no one outside my house can join. I try to connect directly with myIp:27015 but it says not responding. I've done all of instructions and port forwarded 7777-7778 tcp/udp and 27015-27020 tcp/udp and did the iptables commands. In the start command, it is port 7777 and query port 27015. I will provide more information if informed to.

Thanks .

**Comment by klightspeed** [comment]
Some routers do not support NAT loopback, and trying to connect to your own public IP address from within your network won't work on those routers.

Does trying to query the server using the arkservers.net link printed by `arkmanager status` work?

**Comment by tr1pped0ut** [comment]
> Some routers do not support NAT loopback, and trying to connect to your own public IP address from within your network won't work on those routers.
> 
> Does trying to query the server using the arkservers.net link printed by `arkmanager status` work?

Thanks for your quick reply.

The Arkservers link from `arkmanager status` says server not found

Also on http://opensimulator.org/wiki/NAT_Loopback_Routers for my router says: Loopback is flaky.

The thing is I have previously made a minecraft server and it worked fine with others connecting.

**Comment by klightspeed** [comment]
It you run tcpdump or wireshark on the machine running the server, and try to connect to it from outside the network (e.g. by trying to have a friend direct-connect using the steam connect link, or by querying it using the arkservers.net link), does it show traffic on ports 27015 and 7778?

**Comment by tr1pped0ut** [comment]
> It you run tcpdump or wireshark on the machine running the server, and try to connect to it from outside the network (e.g. by trying to have a friend direct-connect using the steam connect link, or by querying it using the arkservers.net link), does it show traffic on ports 27015 and 7778?

So, I had my friend connect while wireshark was capturing.

It does show traffic with 27015 and 7778, although 27015 is the source port for all of them, nothing is connecting to 27015 (stuff is coming from 27015 but not going to it). Also the only thing for 7778 is my computer ip connecting to valve's ip and valves ip to my computer ip (valve's ip is 155.133.254.132).

I can provide more information if needed

**Comment by tr1pped0ut** [comment]
> It you run tcpdump or wireshark on the machine running the server, and try to connect to it from outside the network (e.g. by trying to have a friend direct-connect using the steam connect link, or by querying it using the arkservers.net link), does it show traffic on ports 27015 and 7778?

I did find a bit of traffic coming from port 27015 to various other ports. If I click on them it mentions ark: survival evolved.

Also it shows my computer ip connecting to valve's ip, and vice versa with the ports coming from 7778 to 27019 and the other way around.

I can provide more information if provided

**Comment by klightspeed** [comment]
Did you capture `tcp portrange 7777-7778 or udp portrange 27015-27020`?

If ark_Port=7778 and ark_QueryPort=27015 in your config (which results in passing Port=7777 and QueryPort=27015 to the server), and no traffic is coming in with destination UDP port 27015, that suggests that the forwarder isn't set up correctly.

Was the traffic coming from port 27015 originating from your server (i.e. source ip 192.168.1.121 and source port 27015), or originating from outside (i.e. destination ip 192.168.1.121 and source port 27015)?

**Comment by tr1pped0ut** [comment]
The traffic from port 27015 was originating from me to other ip's. Also I figured out that 3 of them are going to my friend's ip, and when he tried to connect it still says server is not responding.  And the 7778 originated from me.

![Also here is a picture of my port forwarding. ](https://user-images.githubusercontent.com/34494436/60058193-75233780-96b5-11e9-8177-29cfca836a97.PNG)

**Comment by klightspeed** [comment]
Let me get this right - there is no incoming traffic from your friend's IP to the server, yet somehow your server is sending a reply from port 27015 to your friend's IP?

If your friend runs wireshark while trying to connect (with capture filter `ip host your.public.ip.address`, do they see the client querying the server, and do they see a response from your server?

I was wrong about tcp port 7778 - it's UDP port 7778, and I think the server then uses NAT traversal (using something like STUN) to connect between server and client.

**Comment by tr1pped0ut** [comment]
Hmm.. He sent me the wireshark file and it doesn't seem to have my ip in it.. would you like to chat from steam chat?

**Comment by klightspeed** [comment]
I won't be able to do anything until about 09:00 UTC.

**Comment by Hulth** [comment]
Do you run a firewall on your computer that hosts the server?
