### ISSUE TITLE
Server cluster Server running but no listening

### ISSUE THREAD

**Issue by usernr12** [arkmanager/ark-server-tools#1024]
Hallo, first time sorry for my English.
Now my problem, i have create a cluster with the ARK Server Tools for 4 instances called ragnarok, ARK1, ARK2, ARK3. ragnarok and ARK3 running and listening, ARK1 and ARK2 only running but not listening.
The Ports are: 
ragnarok: RCON 32330, 7778, 27015
ARK1:  RCON 32332, 7780,  27017
ARK2:  RCON 32334, 7782,  27019
ARK3:  RCON  32336, 7784,  27021

I have open the Ports with ipTables and with udp and tcp

arkmanager.cfg:
```
arkstChannel="master"                                               # change it to a different branch to get non-stable versions
install_bindir="/usr/local/bin"
install_libexecdir="/usr/local/libexec/arkmanager"
install_datadir="/usr/local/share/arkmanager"

# config SteamCMD
steamcmdroot="/home/ark/steamcmd"                                 # path of your steamcmd instance
steamcmdexec="steamcmd.sh"                                          # name of steamcmd executable
steamcmd_user="ark"                                               # name of the system user who own steamcmd folder
steamcmd_appinfocache="/home/ark/Steam/appcache/appinfo.vdf"      # cache of the appinfo command
steamcmd_workshoplog="/home/ark/Steam/logs/workshop_log.txt"      # Steam workshop log
steamlogin="anonymous"                                             # Uncomment this to specify steam login instead of using anonymous login
#steamcmdhome=/home/steam                                           # Uncomment this to override steamcmd home directory

# config environment
arkserverexec="ShooterGame/Binaries/Linux/ShooterGameServer"        # name of ARK server executable
arkbackupdir="/home/ark/ARK-Backups"                              # path to backup directory
arkwarnminutes="30"                                                 # number of minutes to warn players when using update --warn
arkautorestartfile="ShooterGame/Saved/.autorestart"                 # path to autorestart file
arkAutoUpdateOnStart="true"                                        # set this to true if you want to always update before startup
arkBackupPreUpdate="true"                                          # set this to true if you want to perform a backup before updating
arkStartDelay=20                                                   # set this to change the maximum delay between server starts - 0 or unser for no delay, will continue immediately when server is up
#defaultinstance_max=20                                             # Same as above, for v1.6.43 compatibility
arkStagingDir="/home/ark/ARK-Staging"                            # Uncomment to enable updates to be fully downloaded before restarting the server (reduces downtime while updating)

# Options to automatically remove old backups to keep backup size in check
# Each compressed backup is generally about 1-2MB in size.
arkMaxBackupSizeMB="2500"                                            # Set to automatically remove old backups when size exceeds this limit
arkMaxBackupSizeGB="5"                                             # Uncomment this and comment the above to specify the limit in whole GB

# Update warning messages
# Modify as desired, putting the %d replacement operator where the number belongs
msgWarnUpdateMinutes="Der Server startet in 10 Minuten fuer ein Update neu"
msgWarnUpdateMinutes="Der Server startet in 5 Minuten fuer ein Update neu"
msgWarnUpdateMinutes="Der Server startet in 3 Minuten fuer ein Update neu, bitte Landet alle falls ihr noch in der Luft seid"
msgWarnUpdateMinutes="Der Server stertet in 1 Minute fuer ein Update neu, nicht der fall  Verursacht schmerzen, die Landung schmerzt"
msgWarnUpdateSeconds="This ARK server will shutdown for an update in %d seconds"
msgWarnRestartMinutes="Der Server startet in 10 Minuten neu"
msgWarnRestartMinutes="Der Server startet in 5 Minuten neu"
msgWarnRestartMinutes="Der Server startet in 3 Minuten neu. bitte Landet alle falls ihr noch in der Luft seid"
msgWarnRestartMinutes="Der Server startet in 1Minute neu,wer hÃ¶her fliegt faellt laenger"
msgWarnRestartSeconds="This ARK Server will shutdown for a restart in %d seconds"
msgWarnShutdownMinutes="Der Server faehrt in 10 Minuten herunter"
msgWarnShutdownMinutes="Der Server faehrt in 5 Minuten herunter"
msgWarnShutdownMinutes="Der Server faehrt in 3 Minuten herunter, bitte landet wenn ihr noch in der Luft seid"
msgWarmShutdownMinutes="Der Server faehrt in 1 Minute herunter, wer laenger faellt, schlaegt haerter auf"
msgWarnShutdownSeconds="This ARK server will shutdown in %d seconds"
msgWarnCancelled="Restart cancelled by player request"

# Notifications
# discordWebhookURL="https://discordapp.com/api/webhooks/{webhook.id}/{webhook.token}"
# notifyMsgShuttingDown="Shutting down"
# notifyMsgStarting="Starting"
# notifyMsgServerUp="Server is up"
# notifyMsgStoppedListening="Server has stopped listening - restarting"
# notifyMsgServerTerminated="Server exited - restarting"
# notifyTemplate="Message from instance {instance} on server {server}: {msg}"
# noNotifyWarning=true

# Restart cancel chat command
chatCommandRestartCancel="/cancelupdate"

# ARK server common options - use ark_<optionname>=<value>
# comment out these values if you want to define them
# inside your GameUserSettings.ini file
serverMap="Ragnarok"                                               # server map (default TheIsland)
#serverMapModId="469987622"                                         # Uncomment this to specify the Map Mod Id (<fileid> in http://steamcommunity.com/sharedfiles/filedetails/?id=<fileid>)
#ark_TotalConversionMod="496735411"                                 # Uncomment this to specify a total-conversion mod
ark_RCONEnabled="True"                                              # Enable RCON Protocol
ark_ServerPassword=""                                               # ARK server password, empty: no password required to login
ark_ServerAdminPassword="KEEP IT SAFE"                               # ARK server admin password, KEEP IT SAFE!
ark_MaxPlayers="15"
ark_GameModIds="731604991,1565015734,741203089,558651608,749466101,736236773,719928795,764755314,793605978,902548451,924933745,1211297684,1273112284,893904615,670764308,741203089"                     # Uncomment to specify additional mods by Mod Id separated by commas
ark_AltSaveDirectoryName="Server - Ragnarok"                                    # Uncomment to specify a different save directory name

# ARK server flags - use arkflag_<optionname>=true
#arkflag_OnlyAdminRejoinAsSpectator=true                            # Uncomment to only allow admins to rejoin as spectator
#arkflag_DisableDeathSpectator=true                                 # Uncomment to disable players from becoming spectators when they die
arkflag_log=true
arkflag_server=true

# ARK server options - i.e. for -optname=val, use arkopt_optname=val
#arkopt_StructureDestructionTag=DestroySwampSnowStructures

# config Service
logdir="/var/log/arktools"                                          # Logs path (default /var/log/arktools)

# steamdb specific
appid=376030                                                        # Linux server App ID
mod_appid=346110                                                    # App ID for mods

# Mod OS Selection
mod_branch=Windows
# Add mod-specific OS selection below:
#mod_branch_496735411=Windows

# alternate configs
# example for config name "ark1":
#configfile_ark1="/path/to/config/file"
configfile_ARK1=/etc/arkmanager/instances/ARK1.cfg
configfile_ARK2=/etc/arkmanager/instances/ARK2.cfg
configfile_ARK3=/etc/arkmanager/instances/ARK3.cfg
#defaultinstance="ragnarok"
```
  
I dont now, why instance ragnarok and ARK3 run and listening and the other only run?

**Comment by klightspeed** [comment]
I'm guessing you're overriding those default options in the instance configs?

Make sure each server has its own AltSaveDirectory and has the same list of mods if the servers share the same install directory.  Also make sure you have the spelling and casing of the map names correct.

**Comment by usernr12** [comment]
Thanks for your answer
Yes i thing so, here my instances.

# config environment
arkserverroot="/home/ark/Valguero"                                     
arkbackupdir="/home/ark/ARK-Backups/Valguero"

# ARK server options - use ark_<optionname>=<value>
# comment out these values if you want to define them
# inside your GameUserSettings.ini file
serverMap="Valguero"                                            
#serverMapModId="469987622"                                    
#ark_TotalConversionMod="496735411"                                
ark_RCONEnabled="True"                                            
ark_RCONPort="32331"                                            
ark_SessionName="Syndige Schönheit"                                
ark_Port="7784"                                                    
ark_QueryPort="27017"                                              
ark_ServerPassword=""                                              
ark_ServerAdminPassword="KEEP IT SAFE"                               
ark_MaxPlayers="15"
ark_GameModIds="731604991,1565015734,741203089,558651608,749466101,736236773,719928795,764755314,793605978,902548451,924933745,812655342,1273112284,893904615,670764308,741203089"                    
ark_AltSaveDirectoryName="Server - Valguer"                                  


# ARK server flags - use arkflag_<optionname>=true
#arkflag_OnlyAdminRejoinAsSpectator=true                            
#arkflag_DisableDeathSpectator=true                               
arkflag_log=true
arkflag_NoBattleEye=true

# ARK server options - i.e. for -optname=val, use arkopt_optname=val
#arkopt_StructureDestructionTag=DestroySwampSnowStructures

#arkPreStart="/etc/arkmanager/instances/instance.start"            

# config environment
arkserverroot="/home/ark/ARK2"                                  
arkbackupdir="/home/ark/ARK-Backups/ARK2"

# ARK server options - use ark_<optionname>=<value>
# comment out these values if you want to define them
# inside your GameUserSettings.ini file
serverMap="Aberration_P"                                              
#serverMapModId="469987622"                                       
#ark_TotalConversionMod="496735411"                               
ark_RCONEnabled="True"                                            
ark_RCONPort="32332"                                            
ark_SessionName="Syndige Dunkelheit"                             
ark_Port="7780"                                                 
ark_QueryPort="27019"                                            
ark_ServerPassword=""                                             
ark_ServerAdminPassword="KEEP IT SAFE"                               
ark_MaxPlayers="15"
ark_GameModIds="731604991,1565015734,741203089,558651608,749466101,736236773,719928795,764755314,793605978,902548451,924933745,812655342,1273112284,893904615,670764308,741203089"                   
#ark_AltSaveDirectoryName="Server - ARK2"                              

# ARK server flags - use arkflag_<optionname>=true
#arkflag_OnlyAdminRejoinAsSpectator=true                     
#arkflag_DisableDeathSpectator=true                           
arkflag_log=true
arkflag_server=true

# ARK server options - i.e. for -optname=val, use arkopt_optname=val
#arkopt_StructureDestructionTag=DestroySwampSnowStructures

#arkPreStart="/etc/arkmanager/instances/instance.start"          

# config environment
arkserverroot="/home/ark/ARK3"                                    
arkbackupdir="/home/ark/ARK-Backups/ARK3"

# ARK server options - use ark_<optionname>=<value>
# comment out these values if you want to define them
# inside your GameUserSettings.ini file
serverMap="Extinction"                                             
#serverMapModId="469987622"                                        
#ark_TotalConversionMod="496735411"                                 
ark_RCONEnabled="True"                                            
ark_RCONPort="32336"                                            
ark_SessionName="Syndige Technik"                              
ark_Port="7782"                                                     
ark_QueryPort="27021"                                             
ark_ServerPassword=""                                            
ark_ServerAdminPassword="KEEP IT SAFE"                               #
ark_MaxPlayers="15"
ark_GameModIds="731604991,1565015734,741203089,558651608,749466101,736236773,719928795,764755314,793605978,902548451,924933745,812655342,1273112284,893904615,670764308,741203089"                    
ark_AltSaveDirectoryName="Server - ARK3"                            

# ARK server flags - use arkflag_<optionname>=true
#arkflag_OnlyAdminRejoinAsSpectator=true                           
#arkflag_DisableDeathSpectator=true                               
arkflag_log=true
arkflag_server=true

# ARK server options - i.e. for -optname=val, use arkopt_optname=val
#arkopt_StructureDestructionTag=DestroySwampSnowStructures

#arkPreStart="/etc/arkmanager/instances/instance.start"          

# config environment
arkserverroot="/home/ark/ARK"                                  
arkbackupdir="/home/ark/ARK-Backups/ARK"

# ARK server options - use ark_<optionname>=<value>
# comment out these values if you want to define them
# inside your GameUserSettings.ini file
serverMap="Ragnarok"                                              
#serverMapModId="469987622"                                         
#ark_TotalConversionMod="496735411"                                
ark_RCONEnabled="True"                                           
ark_RCONPort="32330"                                              
ark_SessionName="Syndige Goetterdaemmerung"                             
ark_Port="7778"                                                  
ark_QueryPort="27015"                                              
ark_ServerPassword=""                                          
ark_ServerAdminPassword="KEEP IT SAFE"                              
ark_MaxPlayers="15"
ark_GameModIds="731604991,1565015734,741203089,558651608,749466101,736236773,719928795,764755314,793605978,902548451,924933745,812655342,1273112284,893904615,670764308,741203089"                    
ark_AltSaveDirectoryName="Server - ARK"                               


# ARK server flags - use arkflag_<optionname>=true
#arkflag_OnlyAdminRejoinAsSpectator=true                          
#arkflag_DisableDeathSpectator=true                            
arkflag_log=true
arkflag_server=true

# ARK server options - i.e. for -optname=val, use arkopt_optname=val
#arkopt_StructureDestructionTag=DestroySwampSnowStructures

#arkPreStart="/etc/arkmanager/instances/instance.start"              

netstart -tulpn

Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:32336           0.0.0.0:*               LISTEN      32474/ShooterGameSe
tcp        0      0 0.0.0.0:10000           0.0.0.0:*               LISTEN      1457/perl
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      955/apache2
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      824/sshd
tcp        0      0 0.0.0.0:32330           0.0.0.0:*               LISTEN      21824/ShooterGameSe
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      811/mysqld
tcp        0      0 0.0.0.0:32332           0.0.0.0:*               LISTEN      27045/ShooterGameSe
tcp6       0      0 :::22                   :::*                    LISTEN      824/sshd
udp     1536      0 0.0.0.0:7777            0.0.0.0:*                           21824/ShooterGameSe
udp        0      0 0.0.0.0:7778            0.0.0.0:*                           21824/ShooterGameSe
udp        0      0 0.0.0.0:7781            0.0.0.0:*                           32474/ShooterGameSe
udp        0      0 0.0.0.0:7782            0.0.0.0:*                           32474/ShooterGameSe
udp     2304      0 0.0.0.0:7783            0.0.0.0:*                           32462/ShooterGameSe
udp        0      0 0.0.0.0:7787            0.0.0.0:*                           24345/ShooterGameSe
udp        0      0 0.0.0.0:10000           0.0.0.0:*                           1457/perl
udp        0      0 0.0.0.0:14001           0.0.0.0:*                           23868/ShooterGameSe
udp        0      0 0.0.0.0:14001           0.0.0.0:*                           32462/ShooterGameSe
udp        0      0 0.0.0.0:14001           0.0.0.0:*                           24345/ShooterGameSe
udp        0      0 0.0.0.0:27015           0.0.0.0:*                           21824/ShooterGameSe
udp        0      0 0.0.0.0:27021           0.0.0.0:*                           32474/ShooterGameSe

two instances are running perfect, but the other have an conflict with the Ports, and i dont now why

status @all

Running command 'status' for instance 'ARK1'
 Server running:   Yes
 Server PID:   23868
 Server listening:   No
 Server build ID:   3940673
 Server version:   297.35
Running command 'status' for instance 'ARK2'
 Server running:   Yes
 Server PID:   27045
 Server listening:   No
 Server build ID:   3940673
 Server version:   297.35
Running command 'status' for instance 'ARK3'
 Server running:   Yes
 Server PID:   4414
 Server listening:   Yes
Server Name: Syndige Technik - (v297.35)
Players: 0 / 15
Active Players: 0
 Server online:   Yes
 ARKServers link:   http://arkservers.net/server/***.**.***.**:27021
 Steam connect link:   steam://connect/***.**.***.**:27021
 Server build ID:   3940673
 Server version:   297.35
Running command 'status' for instance 'main'
 Server running:   No
 Server listening:   No
 Server build ID:   3940673
 Server version:   297.35
Running command 'status' for instance 'ragnarok'
/etc/arkmanager/instances/ragnarok.cfg: line 1: 121129768#: command not found
 Server running:   Yes
 Server PID:   21824
 Server listening:   Yes
Server Name: Syndige Goetterdaemmerung - (v297.35)
Players: 4 / 15
Active Players: 3
 Server online:   Yes
 ARKServers link:   http://arkservers.net/server/***.**.***.**:27015
 Steam connect link:   steam://connect/***.**.***.**:27015
 Server build ID:   3940673
 Server version:   297.35

**Comment by klightspeed** [comment]
Are you sharing the host with other users?

It looks like PIDs 21824 and 32474 are your working servers, and PIDs 23868 and 27045 are your non-working servers.

Do you know what PIDs 32462 and 24345 are?  i.e. where do the following pseudofiles link:
```
/proc/32462/exe
/proc/24345/exe
```

**Comment by usernr12** [comment]
Hi, i thing the problem with the PID´s we have fixed with a restart of my V- Server, but after it only one Server, called ragnarok are running an listening, the ohter only running.
 i have found this in the /var/log/arktools/arkserver.log
 of the ohter Server who run and listening befor i restert ther Root.

2019-06-28 17:21:41: [ARK3] Using binned.
2019-06-28 17:21:41: [ARK3] 4.5.1-0+UE4 7038 3077 404 10
2019-06-28 17:21:41: [ARK3] CtrlCHandler: Signal=2
2019-06-28 17:21:45: [ARK3] /usr/local/bin/arkmanager: line 1171: 19895 Aborted                 "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
2019-06-28 17:23:54: [ARK3] 2019-06-28 17:23:54: start
2019-06-28 17:23:54: [ARK3] 2019-06-28 17:23:54: Running /home/ark/ARK3/ShooterGame/Binaries/Linux/ShooterGameServer Extinction?RCONEnabled=True?RCONPort=32336?SessionName=Syndige\ Technik?Port=7781?QueryPort=27021?ServerPassword?ServerAdminPassword=Keep it save?MaxPlayers=15?GameModIds=731604991,1565015734,741203089,558651608,749466101,736236773,719928795,764755314,793605978,902548451,924933745,812655342,1273112284,893904615,670764308,741203089?AltSaveDirectoryName=Server\ -\ ARK3?bRawSockets?AllowFlyingStaminaRecovery=true?AllowCrateSpawnsOnTopOfStructures=true?bAllowUnlimitedRespecs=true?PreventSpawnAnimations=true?OverrideOfficialDifficulty=5.0?ServerPassword?bRawSockets?listen -ForceAllowCaveFlyers -exclusivejoin -NoBattlEye -clusterid=Syndig -NoTransferFromFiltering -ClusterDirOverride=/home/ark/arkservers/clusterdata -log -server -NoTransferFromFiltering
2019-06-28 17:23:54: [ARK3] 2019-06-28 17:23:54: Server PID: 3107
2019-06-28 17:23:55: [ARK3] [S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
2019-06-28 17:24:32: [ARK3] [S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed

i dont know where the problem is.
