### ISSUE TITLE
Two instances - same characters (question)

### ISSUE THREAD

**Issue by Yippee38** [arkmanager/ark-server-tools#1029]
I've got a Ragnarok server set up that is currently on hold (nobody playing).  I'm trying to set up a Valguero server.  I simlinked a new ARK directory for the Valguero.  Actually, I created a ARKValguero directory, and simlinked everything inside of it, except for the Saved directory.  That, I manually created, along with a LinuxServer directory.  I put the .ini files I wanted in that directory.

I've got the instance config file set up, and the arkmanager.cfg set up so it's pointing to both instance configs.

When I launch the game, it's giving me the Valguero instance, but I can spawn in with a Ragnarok character.  I don't want that.  I want the two to be completely independant.  What am I missing?

**Comment by klightspeed** [comment]
The Saved directory is within the ShooterGame directory.

You probably want the ShooterGame, ShooterGame/Content, ShooterGame/Content/Mods, and ShooterGame/Saved directories created as directories.

**Comment by Yippee38** [comment]
I know that the Saved directory is under ShooterGame.  I did not copy the /Content or /Content/Mods directories.  I don't know that that will help though.  The character saves are not, as far as I can tell, in those directories.  Everything else is fine.  I just need to find a fix for why the game is looking at my Ragnarok characters.

**Comment by Yippee38** [comment]
I've discovered where the problem lies.  Apparently, even though I've got the "arkserverroot=" set in each instance, it is saving all games data to the original ARK directory.

Here's my arkmanager.cfg:
`arkstChannel="master"                                               # change it to a different branch to get non-stable versions
install_bindir="/usr/local/bin"
install_libexecdir="/usr/local/libexec/arkmanager"
install_datadir="/usr/local/share/arkmanager"

# config SteamCMD
steamcmdroot="/home/steam/steamcmd"                                 # path of your steamcmd instance
steamcmdexec="steamcmd.sh"                                          # name of steamcmd executable
steamcmd_user="steam"                                               # name of the system user who own steamcmd folder
steamcmd_appinfocache="/home/steam/Steam/appcache/appinfo.vdf"      # cache of the appinfo command
#steamlogin="anonymous"                                             # Uncomment this to specify steam login instead of using anonymous login

# config environment
arkserverexec="ShooterGame/Binaries/Linux/ShooterGameServer"        # name of ARK server executable
#arkbackupdir="/home/steam/ARK-Backups"                              # path to backup directory
arkwarnminutes="60"                                                 # number of minutes to warn players when using update --warn
arkautorestartfile="ShooterGame/Saved/.autorestart"                 # path to autorestart file
arkAutoUpdateOnStart="true"                                        # set this to true if you want to always update before startup
arkBackupPreUpdate="true"                                          # set this to true if you want to perform a backup before updating
#arkStagingDir="/home/steam/ARK-Staging"                            # Uncomment to enable updates to be fully downloaded before restarting the server (reduces downtime while updating)

# Options to automatically remove old backups to keep backup size in check
# Each compressed backup is generally about 1-2MB in size.
arkMaxBackupSizeMB="5000"                                            # Set to automatically remove old backups when size exceeds this limit
#arkMaxBackupSizeGB="2"                                             # Uncomment this and comment the above to specify the limit in whole GB

# Update warning messages
# Modify as desired, putting the %d replacement operator where the number belongs
msgWarnUpdateMinutes="This ARK server will shutdown for an update in %d minutes"
msgWarnUpdateSeconds="This ARK server will shutdown for an update in %d seconds"
msgWarnRestartMinutes="This ARK server will shutdown for a restart in %d minutes"
msgWarnRestartSeconds="This ARK server will shutdown for a restart in %d seconds"
msgWarnShutdownMinutes="This ARK server will shutdown in %d minutes"
msgWarnShutdownSeconds="This ARK server will shutdown in %d seconds"
msgWarnCancelled="Restart cancelled by player request"

# Restart cancel chat command
#chatCommandRestartCancel="/cancelupdate"

# ARK server common options - use ark_<optionname>=<value>
# comment out these values if you want to define them
# inside your GameUserSettings.ini file
# Everything in here is commented out

# ARK server flags - use arkflag_<optionname>=true
#arkflag_OnlyAdminRejoinAsSpectator=true                            # Uncomment to only allow admins to rejoin as spectator
#arkflag_DisableDeathSpectator=true                                 # Uncomment to disable players from becoming spectators when they die

# ARK server options - i.e. for -optname=val, use arkopt_optname=val
#arkopt_StructureDestructionTag=DestroySwampSnowStructures

# config Service
logdir="/var/log/arktools"                                          # Logs path (default /var/log/arktools)

# steamdb specific
appid=376030                                                        # Linux server App ID
mod_appid=346110                                                    # App ID for mods

# Mod OS Selection
mod_branch=Windows
# Add mod-specific OS selection below:
#mod_branch_496735411=Windows

# alternate configs
# example for config name "ark1":
configfile_YippeeRagnarok="/etc/arkmanager/instances/YippeeRagnarok.cfg"
configfile_YippeeValguero="/etc/arkmanager/instances/YippeeValguero.cfg"

defaultinstance="YippeeValguero"`

And here's my .cfg file for Valguero.  My Ragnarok is essentially the same, except it has different directories for the arkserverroot, arkbackupdir, and, of course, servermap.
`# config environment
arkserverroot="/home/steam/ARK.Valguero"                                     # path of your ARK server files (default ~/ARK)
arkbackupdir="/home/steam/ARK-Valguero-Backups"

# ARK server options - use ark_<optionname>=<value>
# comment out these values if you want to define them
# inside your GameUserSettings.ini file
serverMap="Valguero_P"                                               # server map (default TheIsland)
#serverMapModId="469987622"                                         # Uncomment this to specify the Map Mod Id (<fileid> in http://steamcommunity.com/sharedfiles/filedetails/?id=<fileid>)
#ark_TotalConversionMod="496735411"                                 # Uncomment this to specify a total-conversion mod
# Removed server settings for space
#ark_AltSaveDirectoryName="SotF"                                    # Uncomment to specify a different save directory name

# ARK server flags - use arkflag_<optionname>=true
#arkflag_OnlyAdminRejoinAsSpectator=true                            # Uncomment to only allow admins to rejoin as spectator
#arkflag_DisableDeathSpectator=true                                 # Uncomment to disable players from becoming spectators when they die
arkflag_structurememopts=""

# ARK server options - i.e. for -optname=val, use arkopt_optname=val
#arkopt_StructureDestructionTag=DestroySwampSnowStructures
#arkopt_ActiveEvent=
arkflag_NoBattlEye=true`

Since I've got the arkserverroot set differently for both, it seems that the saves should be saving to the correct directories.  BTW, my dir structure looks like this....
/home/steam
______________/ARK (original install)
______________/ARK.Valguero (everything in here is symlinked to the ARK directory, except the contents of ./ShooterGame/Saved.  Saved is a completely new directory.)

Does anybody have any idea what I'm doing wrong?

**Comment by klightspeed** [comment]
Symlinks act as path reparse points.  Relative paths do not have the information to traverse symlinks backwards, and so will traverse the physical path.

Hard links (cp -al) or bind mounting are going to be more reliable.

For bind mounting, you would want to (as root):
```
mount --bind /home/steam/ARK /home/steam/ARK.Valguero
mount --bind /home/steam/ARK.Valguero.Saved /home/steam/ARK.Valguero/ShooterGame/Saved
```

In /etc/fstab, this would be:
```
/home/steam/ARK /home/steam/ARK.Valguero none bind 0 0
/home/steam/ARK.Valguero.Saved /home/steam/ARK.Valguero/ShooterGame/Saved
```

For hard links, if using a staging directory arkmanager will use hard links (or reflinks if the filesystem supports it) between the staging directory and the game directory (which in turn if the same staging directory is used for multiple instances on the same filesystem will result in hard links between those instances).

**Comment by Yippee38** [comment]
Thanks @klightspeed!  I'll give that a shot.

**Comment by Yippee38** [comment]
I tried hardlinks, but apparently, I can only hardlink files, not directories.  That's too much work.  So I went with bind mounting.  I ran the first command.  That apparently worked.  However, it looks like it only works on the top level directory.  So, if I understand this correctly, it will mount the subdirectories in ARK, but not the subdirectories in /ARK/ShooterGame/Saved.  So that's the reason for the second command you listed.

However, since I don't want the /ARK.Valguero/ShooterGame/Saved to be using the Ragnarok directory (/ARK/ShooterGame/Saved), I would instead need to bind mount the other directories inside of ShooterGame, and leave Saved as a standalone directory.  Correct?

**Comment by klightspeed** [comment]
```
umount /home/steam/ARK.Valguero
mv /home/steam/ARK.Valguero/ShooterGame/Saved /home/steam/ARK.Valguero.Saved
mount --bind /home/steam/ARK /home/steam/ARK.Valguero
mount --bind /home/steam/ARK.Valguero.Saved /home/steam/ARK.Valguero/ShooterGame/Saved
```

**Comment by Yippee38** [comment]
I don't have to unmount.  I rebooted.  ;)

Ok.  Thanks!  Thanks for all of your help.  It fixed my problem (looks that way at least), and I learned something about linux at the same time.  Win!
