### ISSUE TITLE
Core Dump on second instance in a cluster

### ISSUE THREAD

**Issue by spacefiddle** [arkmanager/ark-server-tools#1030]
Have Extinction running for some time, no issues. Can still run and use it with no issues.
After creating a second instance for Valguero, it seems to start and run normally.... until you connect to it. After about 10-15 seconds on the char creation screen, you get dumped back to title page with "You were idle too long!" and a second popup saying connection lost.

In arkserver.log:
[Valguero] /usr/local/bin/arkmanager: line 1171: 25938 Aborted                        (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"

The primary instance with Extinction still seems happy. They have identical configs, except specifying the new Valguero-specific mod from the Val devs, in the instance .cfg file under "extra mods."

**Comment by spacefiddle** [comment]
Disregard. The core dump is apparently the manager failing to shutdown cleanly, but that's its own thing.
The server is running - if I immediately just enter the game with the default toon and spend no time on the creation screen.

Tested by running around, punching things, etc and so forth and everything's fine.
Got myself killed to choose "create new survivor."
Ten seconds after being on creation screen, "You were idle too long!" and booted. Just like when connecting.

This game....

**Comment by klightspeed** [comment]
`Aborted (core dumped)` is due to the game giving itself a SIGABRT when it shuts down cleanly.

**Comment by spacefiddle** [comment]
Gotcha, thanks. I'd be tearing my hair out if I had any left. arkmanager status states the server is online and listening, and displays bnoth the ARKServers link and the Steam Connect link.... but going to arkservers gives "server offline / not found" and no one can connect to it. Meanwhile the first instance, differing in config only in port numbers, is fine. Firewall rules have been checking a billion times. I can connect to the server locally via LAN browse. Router NAT has been checked a billion times. I don't get it.

Does the display of the two links from status indicate a successful test of some kind? Or is it just contstructing a link?

**Comment by klightspeed** [comment]
Server listening means that the server has opened its game port, is responding to query requests, and is not reporting 0/0 players.  Note that the script queries either localhost or the IP specified as the MultiHome IP, so cannot confirm if others can connect to it.
Server online means that the server has registered itself with the Steam master server.  The Steam master server does not confirm that it can query the server.
The port needed are the query port, the game port (Port + 1), and sometimes the server port (Port).  The RCON Port should not be exposed to the internet.
