### ISSUE TITLE
Can not see other maps in the cluster

### ISSUE THREAD

**Issue by CorsairF4U** [arkmanager/ark-server-tools#1033]

**Comment by CorsairF4U** [comment]
all three maps are the same config minus their map name and ports here is the island, server runs, you can play but when you go to an obelisk and try to go to another map there are none in the list

arkserverroot="/home/steam/ARK"                                   
arkbackupdir="/home/steam/ARK-Backups/theisland"

serverMap="TheIsland"  
ark_RCONEnabled="True" 
ark_RCONPort="32330" 
ark_SessionName="MuddyARK-TheIsland" 
ark_Port="7778"  
ark_QueryPort="27015"
ark_AltSaveDirectoryName="Saved-TheIsland"   

arkflag_AllowCaveBuildingPVE=true

# ark cluster settings
arkflag_NoTransferFromFiltering=""
arkopt_clusterid=muddycluster
#ark_PreventDownloadSurvivors=False
#ark_PreventDownloadItems=False
#ark_PreventDownloadDinos=False
#ark_PreventUploadSurvivors=False
#ark_PreventUploadItems=False
#ark_PreventUploadDinos=False
#ark_noTributeDownloads=false
arkopt_ClusterDirOverride=/home/steam/ark-clusterdata

**Comment by sphbecker** [comment]
Try changing your first line you listed to
arkflag_NoTransferFromFiltering=true  (not "")

Everything else looks correct, I just setup the same thing myself and it works fine.

I assume you are running all instances on the same Linux server? If not, then you need to ensure that /home/steam/ark-clusterdata is a shared NFS mount for all servers.
