### ISSUE TITLE
existing ark server

### ISSUE THREAD

**Issue by MyUncleSam** [arkmanager/ark-server-tools#1044]
Hi there,

at the moment I have a running Ark Server. Is it possible to move it so that the ark server tools can manage the server (inclusive 3 addons)?

Would be great if someone can provide a howto or wiki entry for that because I am very interested to try this tool!

**Comment by theEvil007** [comment]
I think the easiest way is to setup your server by arkmanager with all things needed, config, mods etc.
After that start it, stop it when running in the right way. At least copy over all the player, tribe and game data from the old to the new one and start it again.

Worked for me.
