### ISSUE TITLE
Steam: "server not responding"

### ISSUE THREAD

**Issue by worp1900** [arkmanager/ark-server-tools#1045]
Cheers guys,

arkmanager status gives me:

```
$ arkmanager status
Running command 'status' for instance 'main'
 Server running:   Yes
 Server PID:   26842
 Server listening:   Yes
Server Name: ARK ###### - (v302.1)
Players: 0 / 70
Active Players: 0
 Server online:   Yes
 ARKServers link:   http://arkservers.net/server/<ip>:27015
 Steam connect link:   steam://connect/<ip>:27015
 Server build ID:   4396170
 Server version:   302.1
```

UFW says:

```
$ ufw status
Status: active

To                         Action      From
27017/tcp                  ALLOW       Anywhere
7778/tcp                   ALLOW       Anywhere
7778/udp                   ALLOW       Anywhere
27016/tcp                  ALLOW       Anywhere
27016/udp                  ALLOW       Anywhere
3000/tcp                   ALLOW       Anywhere
3001                       ALLOW       Anywhere
27017/udp                  ALLOW       Anywhere
7778                       ALLOW       Anywhere
32330                      ALLOW       Anywhere
```

netstat says:

    $ netstat -tulpn | grep -i shooter
    udp        0      0 0.0.0.0:27015           0.0.0.0:*                           26842/ShooterGameSe
    udp        0      0 0.0.0.0:7778            0.0.0.0:*                           26842/ShooterGameSe

Yet steam says (View > Servers > Favorites > Refresh):

    <IP>:27015         < not responding >
    <IP>:27016         < not responding >
    <IP>:27017         < not responding >

Sidenote: I added 270(15-17) so I could keep all ports in check in case i misunderstood some port configuration.

What else might I check to get to the root of the problem?

Further information:
```
$ arkmanager --version
Version: 1.6
Channel: master
Commit: 40e373f
Release Tag: v1.6.48
Blob SHA: 6ecfbdf544c14c10864eb90dc7417de580e74478

OS: Ubuntu:14.04 (yes, I know it's old, sorry :/ )

I just installed arkmanager today on a clean slate, steamcmd as well just today.

**Comment by klightspeed** [comment]
Is this from inside or outside the network that the server is on?

If it's on the same LAN, you're trying to connect to the public IP, and you're behind a modem / router, that router needs to support loopback routing.

If it's from outside the network, note that some ISPs block incoming queries on common game ports,

**Comment by worp1900** [comment]
The server is outside my network on public web.

I was able to connect to the server with an older version of the tool some 1 or 2 years back, so I'm fairly certain ISP is not the issue.

What tools might I need to debug this issue? How can I gather more information?

**Comment by pj200105** [comment]
Any chance you got this fixed? Having the exact same issue.

**Comment by Alphakilo** [comment]
@pj200105 please create a new issue, including above command outputs.
