### ISSUE TITLE
arkflag_culture=

### ISSUE THREAD

**Issue by tobi-wankenobi** [arkmanager/ark-server-tools#1046]
Hello, 
I set arkflag_culture=de, but it doesn't work. 
Mods like S+ don't recognize it and are in english language. 

Is there another way to set the language?

**Comment by klightspeed** [comment]
Use `arkopt_culture=de`

**Comment by tobi-wankenobi** [comment]
Thx, i will test it.

**Comment by klightspeed** [comment]
Note that the client culture may be different to the server culture, and mods may use the client culture instead of the server culture.

**Comment by tobi-wankenobi** [comment]
Okay, well, that was the mistake. Now it works. Thank you very much for the quick help.
