### ISSUE TITLE
"ark_AllowCaveBuildingPvE=True" command not written in GameUserSettings.ini

### ISSUE THREAD

**Issue by christian1211** [arkmanager/ark-server-tools#1055]
After I put "ark_AllowCaveBuildingPvE=True" in the instance config, it got ignored. I also tried it in arkmanager.cfg. After starting the instance, the command is still not written in GameUserSettings.ini.

**Comment by klightspeed** [comment]
arkmanager does not itself write anything to `GameUserSettings.ini` - it is the game server itself that updates that file either on startup or when e.g. the MOTD is updated.

Does `AllowCaveBuildingPVE=True` get added to the server option string (you can check either by looking at the arkmanager log file - `/var/log/arktools/arkserver.log` - or by getting the full commandline of the running server - `ps -AF | grep 'ShooterGameServer'`)?

If it does get added, and all of the other options are written by the game to `GameUserSettings.ini`, then this would appear to be a game server bug, or perhaps the server isn't set to PvE.

If it does not get added to the server options, does `arkmanager printconfig` show it being defined?

**Comment by christian1211** [comment]
Yes, it get added to the server option string in arkserver.log.
There are some more settings which are not added to `GameUserSettings.ini`, like:
```
bDisableStructureDecayPvE
alwaysNotifyPlayerJoined
```
Both of them are also in server option string.

`arkmanager printconfig` shows all of them are defined.

**Comment by klightspeed** [comment]
What are the permissions on `GameUserSettings.ini`?

**Comment by christian1211** [comment]
-rw------- 1 steam steam 5,0K Jan 17 11:16 GameUserSettings.ini

Some settings are writte, just not all of them.

**Comment by klightspeed** [comment]
If you manually put the setting into GameUserSettings.ini, is it kept?

**Comment by christian1211** [comment]
Yes, it is kept.

From the Ports, only RCON-Port is written in `GameUserSettings.ini.` Query- and Game-Port ain't. This is correct? Or they also have to be in this file?

**Comment by klightspeed** [comment]
It looks like the game server no longer writes or updates all of the options specified in the option string in `GameUserSettings.ini` during startup.  I would think that options specified on the commandline would still override options in `GameUserSettings.ini`

If you check on the server, do the settings appear to have applied?

**Comment by christian1211** [comment]
No, for me the Settings doesn't seem to have applied.

**Comment by klightspeed** [comment]
Do the `AllowCaveBuildingPVE`, `bDisableStructureDecayPvE` or `alwaysNotifyPlayerJoined` settings apply if you put them directly into `GameUserSettings.ini`?

In my testing, the `Port` and `QueryPort` settings do apply despite not being written to `GameUserSettings.ini`.

Invalid settings do not appear to be added to or removed from `GameUserSettings.ini` - e.g. I added `SuperHyperFakeSettingCantExist=True` to `GameUserSettings.ini`, and it was not removed by the game server.  `AllowCaveBuildingPvE` was also not updated from the game server's command line.  It is also not listed in `ShowMyAdminManager`, despite the string being present in both the executable and the localisation info file.

**Comment by christian1211** [comment]
`alwaysNotifyPlayerJoined` is active when I write it in `GameUserSettings.ini` manually.
`AllowCaveBuildingPVE` I cannot test because I'm a new player and don't know where to find a cave. `bDisableStructureDecayPvE` seems beeing active even without standing in `GameUserSettings.ini`, but I'm not sure if I test it correctly.

**Comment by christian1211** [comment]
Any new information regarding the new realease?

**Comment by klightspeed** [comment]
Testing with a couple of old ARK Server versions I had on other disks (241.5 from May 2016 and 258.35 from Jun 2017), those versions also did not write `DisableStructureDecayPvE`, `AllowCaveBuildingPVE`, or `alwaysNotifyPlayerJoined` to `GameUserSettings.ini`, so I suspect those options have never been supported in the server options string (or at least haven't been supported since 2016).

I have added `arkGameUserSettingsIniFile` and `arkGameIniFile` options, which specify paths to files to overwrite `GameUserSettings.ini` and `Game.ini`.  I have also documented `arkPreStart`, which can be set to the path to a script to run when starting the game server.

**Comment by christian1211** [comment]
So, if `arkGameUserSettingsIniFile` and `arkGameIniFile` is set, I would expect this behavior:

1. arkmanager start @instance
2. Shootergame/Binaries/Linux/GameUserSettings.ini and Shootergame/Binaries/Linux/Game.ini will be overwritten from the specified files from `arkGameUserSettingsIniFile` and `arkGameIniFile`
3. options specified in server-start-string will overwrite options in Shootergame/Binaries/Linux/GameUserSettings.ini and Shootergame/Binaries/Linux/Game.ini

is this correct?

**Comment by klightspeed** [comment]
Swap 3 an 4 - the server itself writes the options.

**Comment by christian1211** [comment]
Thank you. I tried it and it's working.
For now, we can only know what options are supported in server-options-string from testing them, right?

**Comment by klightspeed** [comment]
<https://ark.gamepedia.com/Server_Configuration> is a reasonably good resource, though if you find an error, go ahead and register on gamepedia and fix it (as I have with `?AllowCaveBuildingPVE=true`.

Yes, the only way to test if options are still supported is by testing them.

**Comment by klightspeed** [comment]
Testing here, the following options (as listed on the ARK Gamepedia server config page) are not written to GameUserSettings.ini from the options string:
```
AllowCaveBuildingPvE=True
ForceFlyerExplosives=True
bAppendItemSets=False
bAppendPreventIncreasingMinMaxItemSets=False
bRawSockets=True
```
