### ISSUE TITLE
Server not updating to current Build

### ISSUE THREAD

**Issue by fusselshu** [arkmanager/ark-server-tools#1058]
Hello, all my Servers are somehow stuck at version "v304.453 - 1/27/20", current version is "v304.458 - 2/6/20". I tried manually updating, installing and updating with --force.

Server Name: xxx - (v304.451)
Players: 0 / 30
Active Players: 0
 Server online:   Yes
 ARKServers link:   http://arkservers.net/server/123.123.123.123:27015
 Steam connect link:   steam://connect/123.123.123.123:27015
 Server build ID:   4649182
 Server version:   304.453

 arkmanager --version
Version: 1.6
Channel: master
Commit: 40e373f
Release Tag: v1.6.48

**Comment by klightspeed** [comment]
What is the output of `arkmanager update @instance --verbose --force`?

**Comment by fusselshu** [comment]
Well since we are one big update ahead, it fixed itself by updating to that version. Just back in the time it was frustrating not to have the essential fixes provided by that versions :D

**Comment by klightspeed** [comment]
It looks like Wildcard forgot to update the Linux binaries and version.txt again.

https://steamdb.info/app/376030/history/

The buildid in your status was from 6 February 2020 at 21:32:05 UTC

buildid 4613864 on 28 January 2020 at 01:48:37 UTC updated Binaries/Linux and version.txt
buildid 4614374 (304.453) on 28 January 2020 at 05:32:01 UTC updated Binaries/Win64 and version.txt but not Binaries/Linux
buildid 4618487 (304.454) on 29 January 2020 at 06:09:55 UTC updated Binaries/Win64 but not Binaries/Linux
buildid 4626036 (304.455) on 31 January 2020 at 01:21:11 UTC updated Binaries/Win64 but not Binaries/Linux
buildid 4637992 (304.456) on 4 February 2020 at 02:30:11 UTC updated Binaries/Win64 but not Binaries/Linux
buildid 4641952 (304.457) on 5 February 2020 at 01:48:15 UTC updated Binaries/Win64 but not Binaries/Linux
buildid 4649182 (304.458) on 6 February 2020 at 21:32:05 UTC updated Binaries/Win64 but not Binaries/Linux
buildid 4662864 (305.13) on 11 February 2020 at 18:08:27 UTC updated Binaries/Linux and version.txt

**Comment by fusselshu** [comment]
Ah well thought so that the problem is not on the Arkmanager side :D

**Comment by spacefiddle** [comment]
Hello - I am also seeing a similar issue where the server reports itself as an older version.
Two different older versions, in fact. Output of status is:

Server Name - blah (v307.6)
Players: 0 / 70
(etc)
Server version: 307.02

It's been at those two versions for several updates now. This on Wildcode's side?

**Comment by klightspeed** [comment]
Wildcard has been lazy about updating `version.txt`
