### ISSUE TITLE
Running in AWS

### ISSUE THREAD

**Issue by Marakai** [arkmanager/ark-server-tools#1061]
I've been working on launching my own dedicated server into AWS (using Spot instances to save money 😄 ) and found your tool invaluable to make the process easy.

It would be great if I could now use the underlying services together with your tools, such as storing versioned backups in S3 from `arkmanager`. 

for example `arkmanager s3backup <bucket>`

Would you be interested in integrating that into your tools?

**Comment by Caindrac** [comment]
It is not perfect but if you are running your AWS instances you should be able to set ```arkbackupdir``` to something like ```s3://bucket_name/backups```.  I have never personally tested this but it should work.

**Comment by klightspeed** [comment]
@Caindrac that won't work - the `arkbackupdir` path needs to be accessible by e.g. `cp`, `tar`, etc.

**Comment by Caindrac** [comment]
Yeah that is true.

**Comment by Marakai** [comment]
As @klightspeed already indicated, S3 is an object data store not a file system, so you would need to communicate either via the AWS CLI or direct API calls. There are tools that "mount" S3 with a wrapper layer to make them *appear* to be file systems, but I wouldn't want to add that layer and I believe their maturity and stability may be questionable.

**Comment by Caindrac** [comment]
I understand the problem and I get that it is a object store. I move stuff to S3 all the time from ec2 instances I just forgot that I use an bash alias to move stuff that hides the fact that I am using the aws s3 tooling. @Marakai

**Comment by Marakai** [comment]
I'll give it a go. I'll attach an instance profile to the server so I don't need AWS credentials and therefore don't have to store them somewhere in cleartext (or in SSM parameter store)

**Comment by Marakai** [comment]
Surprised this is still open. Just as an update: I've been running my own Ark for a year now and have my backups in S3. Had to roll back a couple of times without issues, so it's working fine. Backup sizes are minuscule so cost pennies.

I've written a script that used the tools to shut down the server, run an S3 backup, update the server (if applicable), update the mods (if applicable) and start the server up again. If anybody is interested, let me know (i'll try to remember to check my inbox :P) and I can put up a gist or something.
