### ISSUE TITLE
Feature Request:  Check for correct permissions

### ISSUE THREAD

**Issue by Nytridr** [arkmanager/ark-server-tools#1072]
I recently ran into a problem where I seriously messed up permissions for arkmanager  and ark.  What a headache.  

Would love to have an option that would double check to make sure all permissions were set correct.

Also since this suggestion is part of the feature request subject, would also love to be able to run arkmanager with out errors if it was part of the same group.  I am building a wrapper for my discord bot to allow my admins to do a few things when they can not get on the rcon program to do it.  Right now I am able to have the commands ran, but it complains that I do not have write access to the log file.
maybe make it where arkmanager needs to be part of the steam group instead of root group.. or atleast can be ran with out errors if it is being ran by someone that is in the steam user group.

**Comment by klightspeed** [comment]
The game server itself changes the permissions on some files so that only the owner can access them.

88570d51ea4ed59ba8a2264369cac30c3650c540 adds an option to sudo to the configured `steamcmd_user` when `usesudo` is set in the arkmanager config.
