### ISSUE TITLE
Feature Request:  which was updated

### ISSUE THREAD

**Issue by Nytridr** [arkmanager/ark-server-tools#1073]
Sorry to keep bothering ya with these.   

Is there a way to have the bot announce what was updated.   Ark or Mod and Mod ID.

**Comment by klightspeed** [comment]
If you use `arkmanager update --warn`, and `msgWarnReason` is defined, and you don't use `--warnreason`, it should notify whether the update updated the game or mods, and which mods were updated.

**Comment by Nytridr** [comment]
is there a variable I could use at all?

**Comment by klightspeed** [comment]
If you define the variable `msgWarnReason`, then it will notify what has been updated when you use `arkmanager update --warn`
