### ISSUE TITLE
How setup a clusters please?

### ISSUE THREAD

**Issue by Elsolo1992** [arkmanager/ark-server-tools#1080]
Hello, first let me apologize for my bad english, I will do my best ^^!
I'm a very big noob in creating server. I setup many servers, the clusters worked very weel but each time I had problems installing mods, so I restart over and over trying differents things... 

With Ark server tools and this guide ( https://www.solosaga.com/2020/01/ubuntu-18.04-ark-survival-evolved-dedicated-linux-server-with-structures-plus-mod/ ) I succeeded to install one server with all my mods but all my efforts to create a cluster fail... 
 
How i can create a clusters using ark server tools please ?

**Comment by fusselshu** [comment]
Hey there, just go to your Arkmanager installation directory i.e. "/etc/arkmanager/" then go to your instances folder and open the instances which you want to set to be a cluster (xyz.cfg). 
Go to the bottom line of the configs and set these lines to the following:

# ark cluster settings
arkflag_NoTransferFromFiltering=""
arkopt_clusterid=clustername
#ark_PreventDownloadSurvivors=False
#ark_PreventDownloadItems=False
#ark_PreventDownloadDinos=False
#ark_PreventUploadSurvivors=False
#ark_PreventUploadItems=False
#ark_PreventUploadDinos=False
#ark_noTributeDownloads=false
arkopt_ClusterDirOverride=path to where the cluster saves data i.e. (/home/ark/cluster)
