### ISSUE TITLE
Game.ini file keeps being cleared

### ISSUE THREAD

**Issue by darkjedeye** [arkmanager/ark-server-tools#1087]
Hi there, i have been trying to increase the breeding rates on my server, only 1 instance, small family server, And from what i have read, i have to place the settings in the Game.ini file, i have, but it keeps getting cleared to have no content... is it something i am doing wrong? do the settings go there?

I'm lost, as i am fairly new to maintaining my own Linux server

**Comment by klightspeed** [comment]
If the format of the file is invalid (e.g. it is UTF8 with non-ascii characters, or is not valid as an ini file), then the game server itself will replace it with the default (which is empty).

**Comment by darkjedeye** [comment]
ibopen the file in linux using nano, and then add the things in by typing, not copy paste, which as far as i know would keep the file format, right?

**Comment by darkjedeye** [comment]
sorted, no worries.... turns out typos suck.

**Comment by avendretter** [comment]
What do you mean by breeding?
In general these kind of settings should be placed in the GameUserSettings.ini not in the Game.ini.

In there you have the `[ServerSettings]` section.

In here you find all settings you can set: https://ark.gamepedia.com/Server_Configuration

In your case it should be the following settings:

EggHatchSpeedMultiplier=<value> | Value = floatDefault = 1.0 | Higher number decreases (by percentage) time needed for fertilized egg to hatchIntroduced in patch 219.0
-- | -- | --
BabyMatureSpeedMultiplier=<value> | Value = floatDefault = 1.0 | Higher number decreases (by percentage) time needed for baby dino to matureIntroduced in patch 219.0
BabyFoodConsumptionSpeedMultiplier=<value> | Value = floatDefault = 1.0 | Lower number decreases (by percentage) the speed that baby dinos eat their foodIntroduced in patch 222.3
