### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by MeerkatRS** [arkmanager/ark-server-tools#1100]
Added a new mod and getting permission denied. Tried removing it and now says mod mismatch when joining server.
![image](https://user-images.githubusercontent.com/31329492/83945197-162bd500-a7d7-11ea-810a-57f6facdafbc.png)

**Comment by klightspeed** [comment]
That suggests that either you have a bad `umask`, or the mod directory has bad permissions, or the `steam` user does not own that mod directory.

**Comment by Alphakilo** [comment]
Should we check permissions before attempting to download / install mods @klightspeed?

**Comment by klightspeed** [comment]
292e5c91370b20ee6b9b702dfed40ab80a45b3fd adds a warning when the `Mods` directory is not writable.
