### ISSUE TITLE
Server updating mods when no players online

### ISSUE THREAD

**Issue by MeerkatRS** [arkmanager/ark-server-tools#1101]
I don't have --ifempty in my crontab but the server shuts down immediately because there's no players online even though I don't want it to do that
![image](https://user-images.githubusercontent.com/31329492/83982001-cfca9900-a8f0-11ea-901a-ab75da594e47.png)

**Comment by klightspeed** [comment]
If you don't want
```
Nobody is connected.  Shutting down immediately
```
Try adding
```
arkprecisewarn=true
```
to your arkmanager config.

**Comment by MeerkatRS** [comment]
That's exactly what I was looking for. Appreciate the fast responses. Thanks.
