### ISSUE TITLE
Server running but cant connect to it

### ISSUE THREAD

**Issue by josuVazquez** [arkmanager/ark-server-tools#1105]
After a lot of strugle, as you can see I manage to make my server work.

![image](https://user-images.githubusercontent.com/25078974/84577077-7d3e2080-adb9-11ea-92fb-ca032db7393d.png)

But for some reason I can't find my server and when I try to connect directly using IP the connection is rejected by the server.

![image](https://user-images.githubusercontent.com/25078974/84577242-ec684480-adba-11ea-9cee-0d7c09e0a632.png)

**Comment by klightspeed** [comment]
The server should have bound to UDP ports 27015, 7777, and 7778.
