### ISSUE TITLE
Crossplay with Epic

### ISSUE THREAD

**Issue by Xarann** [arkmanager/ark-server-tools#1109]
Hello,

How activate crossplay with epic version ?

https://ark.gamepedia.com/311.74

Thks

**Comment by klightspeed** [comment]
It says you use the `-crossplay` option, so you would put `arkflag_crossplay=true` into your instance config.

It also says that you can't use mods when running a crossplay server.

**Comment by Sc0r** [comment]
there was also something about -epiconly, would that allow mods again?
kind of looks like this could be a thing they fix/add soon-ish.

**Comment by klightspeed** [comment]
> there was also something about -epiconly, would that allow mods again?
> kind of looks like this could be a thing they fix/add soon-ish.

My guess would be that `-epiconly` with mods would require that the mods be on Epic's equivalent of the Steam workshop.

**Comment by TheInternetIsReal** [comment]
Has anyone confirm that `arkflag_crossplay=true` works yet for epic players?

**Comment by Ramblurr** [comment]
Yea, I run a server using that flat and only have epic users playing

**Comment by goldenSniperOS** [comment]
Hi, I have 2 questions maybe someone could help me:

- Is The way to activate crossplay without modifying the config file, ` arkmanager --arkopt, crossplay` ?
- Which one of these values is the value on arkmanager.cfg to allow crossplay: `arkflag_crossplay=true`, `arkflag_crossplay="true"` or arkflag_crossplay="True"

Thanks

**Comment by klightspeed** [comment]
> Hi, I have 2 questions maybe someone could help me:
> 
> * Is The way to activate crossplay without modifying the config file, ` arkmanager --arkopt, crossplay` ?

```
arkmanager --arkopt,--crossplay
```

> * Which one of these values is the value on arkmanager.cfg to allow crossplay: `arkflag_crossplay=true`, `arkflag_crossplay="true"` or `arkflag_crossplay="True"`
> 
> Thanks
Any of the above - any non-blank value will enable the option.

**Comment by goldenSniperOS** [comment]
> > Hi, I have 2 questions maybe someone could help me:
> > 
> > * Is The way to activate crossplay without modifying the config file, ` arkmanager --arkopt, crossplay` ?
> 
> ```
> arkmanager --arkopt,--crossplay
> ```
> 
> > * Which one of these values is the value on arkmanager.cfg to allow crossplay: `arkflag_crossplay=true`, `arkflag_crossplay="true"` or `arkflag_crossplay="True"`
> > 
> > Thanks
> 
> Any of the above - any non-blank value will enable the option.

Thanks @klightspeed for your response, but, maybe I made a mistake typing the command the right command will be `arkmanager restart --arkopt, --crossplay` and what if I need to add another argument? Will be like this `arkmanager restart --arkopt, --crossplay --arkopt, --NoBattleEye` ?

Thanks again

**Comment by klightspeed** [comment]
> Thanks @klightspeed for your response, but, maybe I made a mistake typing the command the right command will be `arkmanager restart --arkopt, --crossplay` and what if I need to add another argument? Will be like this `arkmanager restart --arkopt, --crossplay --arkopt, --NoBattleEye` ?
> 
> Thanks again

Sorry, the option should have a single dash, not a double-dash, so it'd be `--arkopt,-crossplay`

There should be no space between the comma and the option, so it should be `--arkopt,-crossplay`, not `--arkopt, -crossplay`.

You can also specify the `--arkopt,-option` as many times as you need.
e.g.
```
arkmanager restart --arkopt,-crossplay --arkopt,-NoBattleEye`
```
