### ISSUE TITLE
Server running and listening but not really

### ISSUE THREAD

**Issue by hazelement** [arkmanager/ark-server-tools#1110]
I'm trying to start up an instance. The instance seemed to start fine and status shows positive listening. But there is no process listening on ports. Any idea why?

```
root@ark-server:/# arkmanager status
Running command 'status' for instance 'main'
 Server running:   Yes
 Server PID:   12439
 Server listening:   Yes
Server Name: TESTING ARK Server - (v311.99)
Players: 0 / 10
Active Players: 0
 Server online:   Yes
 ARKServers link:   http://arkservers.net/server/xxx.xxx.xxx.xxx:27015
 Steam connect link:   steam://connect/xxx.xxx.xxx.xxx:27015
 Server build ID:   5169549
 Server version:   311.98

root@ark-server:/# lsof -i -P -n | grep LISTEN
systemd-r   684 systemd-resolve   13u  IPv4  20838      0t0  TCP 127.0.0.53:53 (LISTEN)
sshd        751            root    3u  IPv4  19449      0t0  TCP *:22 (LISTEN)
sshd        751            root    4u  IPv6  23556      0t0  TCP *:22 (LISTEN)
ShooterGa 12439           steam   30u  IPv4 151519      0t0  TCP *:32330 (LISTEN)

root@ark-server:/# ulimit -n
1024
```

**Comment by klightspeed** [comment]
The server binds to UDP ports.  You're listing TCP ports on which processes are listening.

**Comment by hazelement** [comment]
You are right. The server is running. However arkservers.net can not see it and I had to add it manually. It took the server with correct info. But when I connect to it from epic, it says Connection Timeout. Tried from steam as well, it says server not responding. Anyway to trouble shoot it? ShooterGame/Saved/Logs doesn't show anything.

**Comment by hazelement** [comment]
I've setup port forwarding on my modem. And I confirm the ports are working with. nc -v -u -z -w 3 <public_ip> <port>

**Comment by pj200105** [comment]
Able to figure it out? I have the same problem.

**Comment by hazelement** [comment]
Ya,  I had to add my server in arkservers.net manually and the website was able to query my server settings. As for connection, it was because my server and my PC are on the same network. It's probably some router configurations or ISP. Once I connect to VPN on another site, I was able to connect to my server.

**Comment by klightspeed** [comment]
> As for connection, it was because my server and my PC are on the same network. It's probably some router configurations or ISP. Once I connect to VPN on another site, I was able to connect to my server.

Your router probably does not support NAT loopback.

**Comment by hazelement** [comment]
That sounds like the case. I didn't find any option on this. Sorry I can't verify that.

**Comment by pj200105** [comment]
> Ya, I had to add my server in arkservers.net manually and the website was able to query my server settings. As for connection, it was because my server and my PC are on the same network. It's probably some router configurations or ISP. Once I connect to VPN on another site, I was able to connect to my server.

Thanks for the reply. Yep figured this out late last night myself.  Was gonna respond to let you know. Glad we both got it fixed!
