### ISSUE TITLE
Idea: issue housekeeping

### ISSUE THREAD

**Issue by Alphakilo** [arkmanager/ark-server-tools#1133]
I was browsing open issues and most of them could be closed as they boil down to:

- game support (e.g. #1097)
- network support (#1023)
- linux support (#1100)
- have resolutions, yet remain open (#1091)
- somewhat stale 😆 (#453)

Since this tool brought me much joy and a feature request of mine was implemented in mere hours (mad props) I'd volunteer to do a late spring cleaning.

**Comment by klightspeed** [comment]
Currently only the owner can add you as a collaborator, so you might need to @ them.

**Comment by Alphakilo** [comment]
Ping @FezVrasta

**Comment by FezVrasta** [comment]
@klightspeed I'd like to make you the repo owner but you first need to delete your own fork

**Comment by klightspeed** [comment]
I wonder if you can transfer it to the arkmanager organisation?

**Comment by FezVrasta** [comment]
yep!

**Comment by FezVrasta** [comment]
done

**Comment by klightspeed** [comment]
I have now invited @Alphakilo to the organisation, and invited them to the Triage role.

**Comment by Alphakilo** [comment]
@klightspeed Thanks! Could you give me some additional permissions, please?
I'd like to create new labels, for instance `Need Docs` or `Support`. And I'd like to change issue titles as well.

**Comment by klightspeed** [comment]
I've given you Write permission - does this allow you to create labels?  If not, I can create the labels you need.
