### ISSUE TITLE
ark_bDisableFriendlyFire not working?

### ISSUE THREAD

**Issue by TheInternetIsReal** [arkmanager/ark-server-tools#1134]
I have this in my instances/main.cfg:
`ark_bDisableFriendlyFire=true`
...which should disable friendly fire in my pvp server. However, I can still hit friendly tribe mates and dinosaurs. Any idea how I can check to make sure my server picked up the option correctly or if arkmanager is the issue? Other common ark_ settings work fine.

Secondly, I have no idea how "using the Game.ini" file works with arkmanager (part of troubleshooting the above). Should I make a game.ini file in my ark shootergame config directory or should I make it in arkmanager folder? There are no instructions in how the config loading precedence or locations work in the readme. Does using a game.ini completely overwrite any game.ini settings in instances/main.cfg file or vice versa?

**Comment by klightspeed** [comment]
`ark_bDisableFriendlyFire=true` should add `?bDisableFriendlyFire=true` to the server options string passed to the game server.

Looking at <https://ark.gamepedia.com/Server_Configuration>, `bDisableFriendlyFire` needs to be specified in `Game.ini`, not the command-line, so `ark_bDisableFriendlyFire` will not work.

If you don't already have any options in `Game.ini`, then you can add the following to either `ShooterGameServer/Saved/Config/LinuxServer/Game.ini` in the directory specified in the `arkserverroot` option, or to `<instancename>.Game.ini` in `/etc/arkmanager/instances` (which will overwrite `ShooterGameServer/Saved/Config/LinuxServer/Game.ini`):
```
[/script/shootergame.shootergamemode]
bDisableFriendlyFire=true
```

**Comment by TheInternetIsReal** [comment]
Thanks. I had no idea from reading the documentation that game.ini settings were not handled by arkmanager "ark_" variables.

**Comment by klightspeed** [comment]
Many settings specified on the command-line map to settings in the `[ServerSettings]` section of `GameUserSettings.ini`, and the game server will write these options as specified on the command-line into `GameUserSettings.ini`
