### ISSUE TITLE
Ubuntu Multi Instance Issue

### ISSUE THREAD

**Issue by Wafflez18** [arkmanager/ark-server-tools#1137]
So I feel like I'm starting to lose my mind. 

I have Ubuntu running in a VM and it's mounted to a freenas smb share using CIFS. Tool starts and stops servers without issues but I'm running into a weird issue when running more than one server at a time. Both run fine separate but once I run both I can only join 1 of them and I can't see the other. Both query on steam and battlemetrics but not in game. Sounds almost like a port issue but the ports should be spaced out enough. I've even tried separating the ports dramatically with the same result of only being able to run one or the other.

I am forwarding +1 game port as well and even tried for fun +2 even though that shouldn't do anything.

## Server 1 ##

Game Port: 8500

Query Port: 28000

 

## Server 2 ##

Game Port: 8502

Query Port: 28001

-Second Crazy Attempt-

## Server 1 ##

Game Port: 8500

Query Port: 28000

 

## Server 2 ##

Game Port: 8600

Query Port: 28100

**Comment by klightspeed** [comment]
Do you have the instances set up to use different RCON ports?  Are they also set up with different names?

When you run `arkmanager status @all`, do they both show up as online?

**Comment by Wafflez18** [comment]
Sorry it took a while to reply back. I decided to scrap my idea of using an SMB share in case that was causing issues. Speed of course for two instances went from about 16 min load times to 90 seconds, even though the share was on the same machine. To make things simple server 1 name is Zelda and Server 2 is Yin. Zelda is set for 29000 and Yin has 29001 for RCON. Both have different server names and file names (instance configs).

When I run a "status @all" I get the opposite results. Yin shows up but Zelda is offline. However I can connect to Zelda but not Yin. Both show up on steam but only Zelda shows up in ark. Now if I run only 1 server at a time "status" reports back fine and I can connect to both. Tempted to scrap both installs and re-download them again. ^^"

Think I might give that last idea a try at this point. Wipe the two test servers and reload them. >.<

**Comment by Wafflez18** [comment]
Hmmm and now its working after deleting and rebuilding the servers. I mean "status @all" now shows both servers offline but I think that might take a moment to update. I can play on both and transfer between them. So small thing but progress is always good. Wont feel like I'm going crazy.

Going to end up closing this as my original issue has been resolved.
