### ISSUE TITLE
.ark-update.lock': Permission denied

### ISSUE THREAD

**Issue by sambo60** [arkmanager/ark-server-tools#1138]
I was checking something unrelated using the journalctl -r
I keep getting the following reported in a forever loop in the journal:
Aug 18 10:37:09 sammy-ms7c02 arkmanager[3782999]: /usr/local/bin/arkmanager: line 1925: /home/sambo/ARK/ShooterGame/Saved/.ark-update.lock: Permission de>
Aug 18 10:37:09 sammy-ms7c02 arkmanager[3782997]: rm: cannot remove '/home/sambo/ARK/ShooterGame/Saved/.ark-update.lock': Permission denied

Now I've been running my ark server for a while now and it still runs with no issues and have been playing just fine.  Not sure when this started but I don't think its normal.  I checked the folder and .ark-update.lock doesn't exist.  Any Help is appreciated

**Comment by klightspeed** [comment]
That suggests that either the user specified in the `steamcmd_user` in `/etc/arkmanager.cfg` does not own `/home/sambo/ARK`, or that you have a scheduled task trying to run `arkmanager update` under a user other than `sambo`

**Comment by sambo60** [comment]
I tried setting permissions in the ARK folder for anyone to modify/write to see if the message stops and it still persists.  How can I determine if I have a schedule task trying to run arkmanager? I do not remember setting up anything.

**Comment by sambo60** [comment]
Whatever it is doesn't seem to be impacting server.  I can do arkmanager start and server comes up.  I rechecked and was still getting same messages in journal. Then I joined the server gamer runs fine.  I exited game and I then did a arkmanager stop and then rechecked and it was still reporting same messages.  Is arkmanager always running in background?

**Comment by sambo60** [comment]
I did do this.  SO this is running in the background.  Do I need this always running in order to start my server up with arkmanager start?
If you want to install the arkmanager service, append the --install-service option to the install command.

**Comment by sambo60** [comment]
I used the following command to stop background service:
systemctl disable arkmanager.service

This took care of the runaway permission denied journal entries.  I was still able to do the arkmanager start and stop.  and the updating worked just fine too.  So I'm pretty happy with those results.  Still not sure what is going on with the service but I don't need it running all the time.

**Comment by klightspeed** [comment]
`arkmanager.service` is only for if you want the game servers to start with the server.  If you have selinux enabled, it's possible that the context systemd starts the service under is denied access to the ARK directory.

If you are starting the game servers another way, then `arkmanager.service` should be disabled.

**Comment by sambo60** [comment]
Thanks.  I'm new to Linux and have never set up a server so this was alot to take on for a newb but hey its working. Learned a ton.
