### ISSUE TITLE
Unable to get latest release - arkmanager v1.6

### ISSUE THREAD

**Issue by ysupport** [arkmanager/ark-server-tools#1140]
Morning,

I'm trying to upgrade my ark manager tools on server and keep getting the same error "Unable to get latest release"

Running arkmanager v1.6

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"

**Comment by klightspeed** [comment]
What is the output of `arkmanager --version`?

**Comment by ysupport** [comment]
Version: 1.6
Channel: master
Commit: 3b7709e
Release Tag: v1.6.52a
Blob SHA: ee3869d9ecbb7678219b4018936c365952634ebc

**Comment by klightspeed** [comment]
Apparently github responds with a redirect when the repo has been transferred.

You can try either editing `/usr/bin/arkmanager` in a texteditor and changing `arkstGithubRepo='FezVrasta/ark-server-tools'` on line 16 to `arkstGithubRepo='arkmanager/ark-server-tools'`, or re-installing using the netinstall script.

**Comment by ysupport** [comment]
Perfect, my path is '/usr/local/bin/arkmanager'.

Works for me.

arkmanager v1.6: Checking for updates...
Getting latest release...
A new version has been released: v1.6.54
* Fix arkNoPortDecrement when ark_Port not in instance config
* Add package manager overrides
* Use rconcmd listplayers for online players with epic
* Add testconfig command
* Output config warnings on stderr
* Update repo path

ARK Server Tools has been moved to the arkmanager github organisation, and now resides at https://github.com/arkmanager/ark-server-tools
Do you want to upgrade to v1.6.54? [Y/N] y
Getting commit for latest release...
Downloading installer
Running install.sh
A previous version of ARK Server Tools was detected in your system, your old configuration was not overwritten. You may need to manually update it.
A copy of the new configuration file was included in /etc/arkmanager. Make sure to review any changes and update your config accordingly!
ARK Server Tools successfully upgraded
Version: 1.6
Channel: master
Commit: 551fdb8
Release Tag: v1.6.54
Blob SHA: a1a9fd014d087230b7597debaaa5f2af5b9e0c07

**Comment by klightspeed** [comment]
This has now been added to the readme.

**Comment by ysupport** [comment]
Saves some more support tickets :) Should probably update my servers more often, "Don't fix it if it's not broken" system is easy and stable. Nice to have the epic additions.
