### ISSUE TITLE
Server often not coming online - even after hours of waiting

### ISSUE THREAD

**Issue by PT400C** [arkmanager/ark-server-tools#1143]
Hey,

is it a known bug that sometimes the ARK instances won't come online (server listening: false). That would require a restart of the linux server itself (sometimes multiple). Is there maybe any way to gather information about why the server won't come online exactly?

As for the reference, I'm running the server on a LXC container with Debian 10 as the OS. No special configurations - other server to client (and vice versa) software works completely fine.

Thanks in advance

PT400C

**Comment by klightspeed** [comment]
When it doesn't come up, is anything else listening on or bound to any of the configured ports?  Also note that instances need to have their `Port` at least 2 ports apart, as since June the server has bound to both `Port` and `Port+1`, where it used to only bind to `Port+1`

**Comment by PT400C** [comment]
> 
> 
> When it doesn't come up, is anything else listening on or bound to any of the configured ports? Also note that instances need to have their `Port` at least 2 ports apart, as since June the server has bound to both `Port` and `Port+1`, where it used to only bind to `Port+1`

Actually I currently have no other instances besides the default one running right now. So there shouldn't be any problems occuring from there. Do you maybe know a quick way of checking if the ports are currently being used / listened to. Maybe that could help me track down the root of this problem.

**Comment by klightspeed** [comment]
`netstat -antup` (`-a`=all, `-n`=no-resolve, `-t`=tcp, `-u`=udp, `-p`=processes) should show what ports are in use.

**Comment by PT400C** [comment]
`Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      211/sshd            
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      337/master          
tcp        0      0 [SERVER-IP]:39982      130.89.148.12:80        TIME_WAIT   -                   
tcp6       0      0 :::80                   :::*                    LISTEN      229/apache2         
tcp6       0      0 :::22                   :::*                    LISTEN      211/sshd            
tcp6       0      0 ::1:25                  :::*                    LISTEN      337/master          
udp    28416      0 0.0.0.0:27015           0.0.0.0:*                           13534/ShooterGameSe`

That's what it looks like when the server is started - though not coming online. I can't see any blocked / used ports to be honest 🤔

**Comment by klightspeed** [comment]
Do you have enough memory to fully start the server?  It needs at least 4GB of RAM.  Trying to use swap in lieu of RAM can result in the server not starting properly.

Another thing that can result in the server hanging on startup is incorrectly specifying the map - though that usually results in consistent failures and not random failures.

**Comment by PT400C** [comment]
@klightspeed Thank you very much with your continuing help and support! I eventually settled by just ignoring this problem. It didn't occur that often lately.

Thank you very much again! :)
