### ISSUE TITLE
Arkmanager & taskset with AMD Ryzen???

### ISSUE THREAD

**Issue by tobi-wankenobi** [arkmanager/ark-server-tools#1148]
Hi, we want to get a new server and now I wanted to ask if anyone has experience with Ark, the Arkmanager and taskset on an AMD Ryzen? 

Does taskset work with a Ryzen and does Ark Server work well on a Ryzen? 

Thank you and have a nice Sunday,
Tobias

**Comment by klightspeed** [comment]
On Zen 1, threads on a core are sequential - i.e. Core 0 has logical CPUs 0 and 1.
On Zen 2, threads on a core are n threads apart, where n is the number of cores - i.e. Core 0 on an 8-core Ryzen has logical CPUs 0 and 8.  This is similar to how threads are numbered on Intel CPUs with Hyperthreading.

Taskset does work with this.  You just need to be aware of the thread numbering, as putting two busy servers onto different threads of the same core will likely perform worse than putting them on different cores.  Giving each server too few logical CPUs is also likely to negatively affect performance.

**Comment by tobi-wankenobi** [comment]
First of all thanks for the answer. 

So if I take a Ryzen 1700x, I put server 1 on 0,1 server 2 on 2,3 etc?

**Comment by klightspeed** [comment]
> First of all thanks for the answer.
> 
> So if I take a Ryzen 1700x, I put server 1 on 0,1 server 2 on 2,3 etc?

Yes, that should work.

**Comment by tobi-wankenobi** [comment]
Thx
