### ISSUE TITLE
This flag has to be at the end of your commandline

### ISSUE THREAD

**Issue by TeH-BaK** [arkmanager/ark-server-tools#1149]
Hello!

I'm looking to use `?customdynamicconfigurl=<link>` in my configuration, but "**_This flag has to be at the end of your commandline_**"

Looking at my logs, the last flag in the command line is the cluster configs, which appears to be in the instances config.

Would i be right in assuming that using `arkflag_?customdynamicconfigurl=<link>` at the end of my instance configs it will always be the last item on the command line? I cant find any information on this specific setting with ark server tools.

Thanks for any feedback! :)

**Comment by klightspeed** [comment]
`?option`s are specified using `ark_option=value`.  i.e. you would use `ark_customdynamicconfigurl=https://your-server.example/your-config.ini`

To have an option appear last in the options string, make sure it is below all of the other options in your instance config, and that you don't have any `ark_` options in your `arkmanager.cfg`

We can probably add a custom option (e.g. `arkCustomDynamicConfigURL=url`) that will put a `customdynamicconfigurl=url` after the `server` option in the option string.

**Comment by TeH-BaK** [comment]
A custom option sounds like a grand idea, saves on complications due to unforseen config changes your end or incorrect updating of files user end!

And thanks for your feedback, i still find the option flags a bit confusing, especially settings things like events and what not. but i seem to get it working via a little trial and error ;)
e.g. if to use
`arkopt_ActiveEvent="Easter"`
or
`arkflag_ActiveEvent=Easter`

If you're happy to add this for the next release i'll hang on for updating my configs and use the new option, seems like a safer bet, especially if that can be set in the arkmanager.cfg rather than in each instance!

Thanks again!

**Comment by klightspeed** [comment]
https://superuser.com/questions/1070059/is-there-a-difference-between-a-command-line-flag-and-a-command-line-option

**Comment by TeH-BaK** [comment]
Nice information, thank you :+1: 
 
> We can probably add a custom option (e.g. `arkCustomDynamicConfigURL=url`) that will put a `customdynamicconfigurl=url` after the `server` option in the option string.

Is this likely to be implemented then, and if so, any kinda idea on a timescale?

Thanks again!

**Comment by klightspeed** [comment]
It is in v1.6.55

**Comment by TeH-BaK** [comment]
You're the best! thanks so much! :)

**Comment by TeH-BaK** [comment]
Sorry to bring this back up, but i need a little clarification

`arkCustomDynamicConfigURL="http://arkdedicated.com/dynamicconfig.ini"`
which would be the official settings example, i assume this is the right syntax.

Where is this placeable, both in instances and in arkmanager.cfg? I can't see it in any of the example configs!

Thanks once again, i just don't really want to experiment on my live cluster! :)

**Comment by klightspeed** [comment]
> arkCustomDynamicConfigURL="http://arkdedicated.com/dynamicconfig.ini"
> which would be the official settings example, i assume this is the right syntax.

Yes

> Where is this placeable, both in instances and in arkmanager.cfg? I can't see it in any of the example configs!

Yes, it can be in either the instance config or arkmanager.cfg.  I have now added it to the example instance config (commented out by default).

**Comment by TeH-BaK** [comment]
Thanks again, you're ever helpful as normal! :D

**Comment by TeH-BaK** [comment]
I'm having issues applying the settings i'm looking for, but i found a log probably explaining the issue.

`[2020.10.05-11.58.05:941][  0]Commandline:  "Genesis?SessionName=*x*x*x*x*?RCONPort=*x*x*x*x*?Port=*x*x*x*x*?QueryPort=*x*x*x*x*?AltSaveDirectoryName=*x*x*x*x*?GameModIds=*x*x*x*x*?ServerPVE=True?DifficultyOffset=5?OverrideOfficialDifficulty=5.0?DisableDinoTaming=False?bDisableDinoTaming=False?ServerPassword?TheMaxStructuresInRange=10500?useoptimizedharvestinghealth=True?ActiveTotalConversion=0?ConnectionTimeout=200000.0?DisableWeatherFog=true?InitialConnectTimeout=200000.0?MaxPlayers=123?P2PConnectionTimeout=200000?ServerPassword?listen?customdynamicconfigurl=http://145.239.204.16:8080/dynamicconfig.ini" -webalarm -structurememopts -NoTransferFromFiltering -clusterid=*x*x*x*x*-ClusterDirOverride=/home/desktop/ARK/clusterdata -DisableWeatherFog -ForceRespawnDinos -NoTransferFromFiltering -ServerRCONOutputTribeLogs -bAllowUnlimitedRespecs -bRawSockets -log -server -servergamelog -servergamelogincludetribelogs -serverlog -structurememopts -webalarm -DisableWeatherFog=true -UseDynamicConfig`

from the wiki:
`?customdynamicconfigurl=<link>	direct link to config file e.g.: arkdedicated.com/dynamicconfig.ini ; This flag has to be at the end of your commandline`

i think there was a mixup which of the commands needed to be at the end!

**Comment by TeH-BaK** [comment]
Actually i found some further info that might explain it.

looking at that file i see quotations around certain amount of it, i assume thats the actual commandline, and the rest is just mentioning the settings used.

https://survivetheark.com/index.php?/forums/topic/539382-customdynamicconfigurl-is-invalid/

i will investiage this.

**Comment by TeH-BaK** [comment]
never mind, its exactly as suggested. so i did his solution. nice bug rofl!
