### ISSUE TITLE
not listing all instances on @all

### ISSUE THREAD

**Issue by uricanezu** [arkmanager/ark-server-tools#1150]
after this update
arkmanager v1.6: Checking for updates...
Getting latest release...
A new version has been released: v1.6.55
* Warn when mods directory is not writable
* Add arkCustomDynamicConfigURL option
* Fix warn not detecting when server is not running
* Fix installmod potentially not detecting --validate option
* Fix chat cancel misdetection
* Improve robustness, based on shellcheck draft pull request from Alphakilo
Do you want to upgrade to v1.6.55? [Y/N] y
Getting commit for latest release...
Downloading installer
Running install.sh
A previous version of ARK Server Tools was detected in your system, your old configuration was not overwritten. You may need to manually update it.
A copy of the new configuration file was included in /etc/arkmanager. Make sure to review any changes and update your config accordingly!
ARK Server Tools successfully upgraded
Version: 1.6
Channel: master
Commit: 2379dec
Release Tag: v1.6.55
Blob SHA: 76d7738d03a5c5361ea771aa4128b14409b2674d

arkmanager status @all
Running command 'status' for instance 'aberration'
 Server running:   No
 Server listening:   No
 Server build ID:   5602851
 Server version:   313.49

lists just one instance

arkmanager list-instances
The following instances are available:
  @aberration: /etc/arkmanager/instances/aberration.cfg => /ssddrive/steam/aberration
  @extinction: /etc/arkmanager/instances/extinction.cfg => /ssddrive/steam/extinction
  @genesis: /etc/arkmanager/instances/genesis.cfg => /ssddrive/steam/genesis
  @ragnarok: /etc/arkmanager/instances/ragnarok.cfg => /ssddrive/steam/ragnarok
  @scorched: /etc/arkmanager/instances/scorched.cfg => /ssddrive/steam/scorched
  @thecenter: /etc/arkmanager/instances/thecenter.cfg => /ssddrive/steam/thecenter
  @theisland: /etc/arkmanager/instances/theisland.cfg => /ssddrive/steam/theisland
  @valguero: /etc/arkmanager/instances/valguero.cfg => /ssddrive/steam/valguero

**Comment by klightspeed** [comment]
v1.6.56 should fix this.

**Comment by uricanezu** [comment]
thanks :) was going crazy

**Comment by uricanezu** [comment]
sorted
