### ISSUE TITLE
Unable to upgrade-tools

### ISSUE THREAD

**Issue by arkcal** [arkmanager/ark-server-tools#1152]
I've installed arkmanager as unprivileged user and now i want to upgrade it.
If i execute 'arkmanger upgrade-tools' the script is asking for a sudo password.

How can i achieve the upgrade process without sudo rights?

**Comment by klightspeed** [comment]
Please check your `~/.arkmanager.cfg` - you should have `steamcmd_user="--me"`

**Comment by arkcal** [comment]
That's it. 
After the initial installation, i have changed the value of this variable to <the unprivileged user>.

Thanks a lot.
