### ISSUE TITLE
Mods arent working

### ISSUE THREAD

**Issue by TiltedPhosphor** [arkmanager/ark-server-tools#1153]
I installed the mods and put thee modIds into the arkmanager.cfg and my instance config. When I connect to the Server I can see  the Engrams from the mods but I am unable to learn them, other things like spawning dinos from mods arent working either. I tried updating the mods and server but the problem remains. Is there any command I didnt use to activate the mods? Thank you in advance

**Comment by klightspeed** [comment]
I'm guessing when you say you put the modIds in the config, that you put the mod IDs, separated by commas, into the `ark_GameModIds` setting?

**Comment by TiltedPhosphor** [comment]
Yes that is what I meant, I put this in the config 

`ark_GameModIds="2135314513,538986229,731604991,793605978" `

**Comment by klightspeed** [comment]
It's possible that some mods require extra configuration in `Game.ini` or `GameUserSettings.ini`.  A couple of those mods have not been updated in a while, and it's also possible a recent update to ARK has broken them.

**Comment by TiltedPhosphor** [comment]
I reinstalled the mods and made sure to put the ModIds in the  `GameUserSettings.in` and the instances, I had to install every mod individual and not together to get them to work.
