### ISSUE TITLE
arkmanager upgrade-tools not working

### ISSUE THREAD

**Issue by CorsairF4U** [arkmanager/ark-server-tools#1162]
$ arkmanager upgrade-tools
arkmanager v1.6: Checking for updates...
Getting latest release...
Unable to get latest release

Checked arkmanager which seems to point to :
https://api.github.com/repos/${arkstGithubRepo}/releases/latest

but it's not responding or otherwise working.

  |  
-- | --
message | "Not Found"
documentation_url | "https://docs.github.com/rest"

**Comment by klightspeed** [comment]
Please refer to the readme:

Known issue with updating
-------------------------
If updating from 1.6.53 or earlier, you will likely get the following message:
```
Unable to get latest release
```
If updating from 1.6.53 or earlier, and `arkstUnstable` is set, then it is likely to say that a hotfix is available, but fail to install it.

Please either:

* edit `arkmanager` wherever it is installed, and replace

`arkstGithubRepo="FezVrasta/ark-server-tools"`

with

`arkstGithubRepo="arkmanager/ark-server-tools"`

or
* re-install using the netinstall script below.

**Comment by CorsairF4U** [comment]
Thank you, I missed that it seems.
Please close issue.
