### ISSUE TITLE
arkmanager status shows more steam players than active steam players

### ISSUE THREAD

**Issue by Heyhoman** [arkmanager/ark-server-tools#1173]
The output of `arkmanager status` displays more steam players than are connected.

> Running command 'status' for instance 'main'
 Server running:   Yes 
 Server PID:   17165 
 Server listening:   Yes 
Server Name: Ark Server - (v321.1)
Steam Players: 4 / 10
Active Steam Players: 2
 Server online:   Yes 
 ARKServers link:   http://arkservers.net/server/xxx.xxx.xxx.xxx:27015 
 Steam connect link:   steam://connect/xxx.xxx.xxx.xxx:27015 
 Server build ID:   6084280 
 Server version:   321.1

**Comment by klightspeed** [comment]
`Steam players` shows the number of connections (from the Steam [A2S_INFO](https://developer.valvesoftware.com/wiki/Server_queries#A2S_INFO) query)
`Active Steam Players` uses the [A2S_PLAYER](https://developer.valvesoftware.com/wiki/Server_queries#A2S_PLAYER) query to get the list of players.

**Comment by Heyhoman** [comment]
I understand that. I'm still wondering where the other two connections might come from.

**Comment by klightspeed** [comment]
One possibility is players sitting at the loading screen or character creation screen.  I don't know if players where the client is waiting for the player to enter the server password are also included by the server.

**Comment by Heyhoman** [comment]
OK, I don't know who was stuck at the loading screen for at least 12 hours but I just restarted the server and now everything is fine.
Thanks for the clarification.
