### ISSUE TITLE
Game.ini

### ISSUE THREAD

**Issue by Chiller2019** [arkmanager/ark-server-tools#1174]
Hey there,

I have a Problem ... I edit the Game.ini from blank in this:

```
[/Script/ShooterGame.ShooterGameMode]
PoopIntervalMultiplier=3.000000
MatingIntervalMultiplier=0.100000
LayEggIntervalMultiplier=0.100000
EggHatchSpeedMultiplier=0.100000
BabyMatureSpeedMultiplier=5.000000
BabyFoodConsumptionSpeedMultiplier=5.000000
PerLevelStatsMultiplier_DinoTamed[0]=2.000000
PerLevelStatsMultiplier_DinoWild[7]=2.000000
```

for Fast Breeding and Push Stats.

My Problem is ... this dont have a function on the Arkmanager (Multyplayer-Server).
I test this in Singleplayer and it's work.

I don't know what i doing wrong or maybe It's a bug. Anyone can help me with this?

Kind regards

**Comment by Chiller2019** [comment]
Wrong Forum ^^ Sorry

**Comment by klightspeed** [comment]
Check that you are putting that the edited `Game.ini` file into the `ShooterGame/Saved/Config/LinuxServer` directory in the game server install directory.

You can have arkmanager write to `Game.ini` by either putting those settings into `/etc/arkmanager/instances/main.Game.ini` (assuming you're  using the `main` instance), or setting `arkGameIniFile` to the path to a file containing those settings.
