### ISSUE TITLE
Unable to start in docker environment

### ISSUE THREAD

**Issue by Niexiawei** [arkmanager/ark-server-tools#1177]
Unable to start centos7 image in docker environment

**Comment by klightspeed** [comment]
Please provide more information.  What error are you getting?

**Comment by Niexiawei** [comment]
Unable to start after installation
![image](https://user-images.githubusercontent.com/29922984/111030823-4deb3b80-843f-11eb-8cc0-f6578f20f374.png)
Will always be stuck on this page
There was no response

**Comment by klightspeed** [comment]
The `#` suggests you are running it as `root`, and hanging suggests that you have set the `steamcmd_user` to `root`, so:
* It sees it's running as root, so tries to re-run itself as `$steamcmd_user`
* It sees it's running as root, so tries to re-run itself as `$steamcmd_user`
* It sees it's running as root, so tries to re-run itself as `$steamcmd_user`
* It sees it's running as root, so tries to re-run itself as `$steamcmd_user`
* It sees it's running as root, so tries to re-run itself as `$steamcmd_user`
* It sees it's running as root, so tries to re-run itself as `$steamcmd_user`
* It sees it's running as root, so tries to re-run itself as `$steamcmd_user`
* It sees it's running as root, so tries to re-run itself as `$steamcmd_user`
* It sees it's running as root, so tries to re-run itself as `$steamcmd_user`
* It sees it's running as root, so tries to re-run itself as `$steamcmd_user`
* It sees it's running as root, so tries to re-run itself as `$steamcmd_user`
* It sees it's running as root, so tries to re-run itself as `$steamcmd_user`
* It sees it's running as root, so tries to re-run itself as `$steamcmd_user`
* It sees it's running as root, so tries to re-run itself as `$steamcmd_user`
* It sees it's running as root, so tries to re-run itself as `$steamcmd_user`
* It sees it's running as root, so tries to re-run itself as `$steamcmd_user`
* It sees it's running as root, so tries to re-run itself as `$steamcmd_user`
* It sees it's running as root, so tries to re-run itself as `$steamcmd_user`
* It sees it's running as root, so tries to re-run itself as `$steamcmd_user`
* It sees it's running as root, so tries to re-run itself as `$steamcmd_user`
* It sees it's running as root, so tries to re-run itself as `$steamcmd_user`
* It sees it's running as root, so tries to re-run itself as `$steamcmd_user`
* It sees it's running as root, so tries to re-run itself as `$steamcmd_user`
* It sees it's running as root, so tries to re-run itself as `$steamcmd_user`
* It sees it's running as root, so tries to re-run itself as `$steamcmd_user`
* It sees it's running as root, so tries to re-run itself as `$steamcmd_user`
* It sees it's running as root, so tries to re-run itself as `$steamcmd_user`
* It sees it's running as root, so tries to re-run itself as `$steamcmd_user`
* It sees it's running as root, so tries to re-run itself as `$steamcmd_user`
* It sees it's running as root, so tries to re-run itself as `$steamcmd_user`
* It sees it's running as root, so tries to re-run itself as `$steamcmd_user`
* It sees it's running as root, so tries to re-run itself as `$steamcmd_user`
* It sees it's running as root, so tries to re-run itself as `$steamcmd_user`
* It sees it's running as root, so tries to re-run itself as `$steamcmd_user`
* It sees it's running as root, so tries to re-run itself as `$steamcmd_user`
* It sees it's running as root, so tries to re-run itself as `$steamcmd_user`
* It sees it's running as root, so tries to re-run itself as `$steamcmd_user`
* It sees it's running as root, so tries to re-run itself as `$steamcmd_user`
* ^C

**Comment by Niexiawei** [comment]
The problem has been solved. Thank you very much
