### ISSUE TITLE
Feature Request: Add ability to see who is logged on

### ISSUE THREAD

**Issue by CorsairF4U** [arkmanager/ark-server-tools#1179]
It would be nice to see who is logged on so I know if it's someone I'm waiting for or someone else. I have been searching through the logs for a way to run a for loop and grep out player names to make a log but can't find that info anywhere. If possible it would be nice when I run a status to see not only how many but what player names are on the server.
Thank you for the work you put into this.

**Comment by klightspeed** [comment]
```
arkmanager rconcmd listplayers
```

**Comment by CorsairF4U** [comment]
Thank you!!
