### ISSUE TITLE
SteamCMD needs a subfolder called steamapps

### ISSUE THREAD

**Issue by Gamewalker** [arkmanager/ark-server-tools#1184]
Steam released a new update and install directory now needs a subfolder called steamapps.
If you dont have a subfolder called steamapps, you will get an error:
`ERROR! Failed to install app '376030' (Disk write failure)`

**Comment by NightDragon1** [comment]
Can confirm the issue. just fixed my docker image to create it.

**Comment by isaiasvallejos** [comment]
I had this problem yesterday, I solved it as follows:
- I ran the steamcmd install command without ark-server-tools (you can get the install command by running `ark-server-tools install --verbose`).
- In the install command, I removed the `force_install_dir` flag, allowing steamcmd to install ARK normally on steamapps folder.
- Then in my instance config file at ark-server-tools I changed the `arkserverroot` parameter to the ARK path inside the steamapps folder.

I hope it helps.

**Comment by Gamewalker** [comment]
Its enought to start, wait for the error to occur and create a 'steamapps' folder under your staging folder.
