### ISSUE TITLE
broadcast error

### ISSUE THREAD

**Issue by dragnod0** [arkmanager/ark-server-tools#1189]
Hi, 
if i use the `arkmanager broadcast @myinstanz "your message here"` command (as root) i become the error 

`Authentication failed at -e line 23`
RCON is enabled but i have no extra client installed.

**Comment by klightspeed** [comment]
Does it work if you run the command as the user you set the server up under?

Note also that each instance needs separate ports - including game, query and RCON ports.

RCON requires the server admin password, which is read from either `GameUserSettings.ini` or from the arkmanager instance config.  If a different server is listening on your configured ports, or if the game is running as a different user to that configured in `arkmanager.cfg`, then the server admin password is likely to be different, resulting in an authentication failure.

**Comment by dragnod0** [comment]
I found the mistake. I had special characters in my admin password.
After removing it, it works.
