### ISSUE TITLE
Error in "Arkmanager Backup" Command for Save of Genesis2

### ISSUE THREAD

**Issue by CaspyBXL** [arkmanager/ark-server-tools#1192]
When using the backup command for Genesis 2 Server something went wrong.
As you can see it tries to backup gen2.ark or gen2.tmp

I can see the profile is saved correctly but not the game map saves.

cp: cannot stat '/CLUSTER1/GENESIS2/ARK/ShooterGame/Saved/SavedArks/gen2.ark': No such file or directory
cp: cannot stat '/CLUSTER1/GENESIS2/ARK/ShooterGame/Saved/SavedArks/gen2.tmp': No such file or directory

When exploring in linux to the folder of the savegame :

XXX@XXX:~/CLUSTER1/GENESIS2/ARK_GEN2/ShooterGame/Saved/SavedArks$ ls -all
total 72488
drwxrwxr-x 2 xxxx xxxx 4096 Jul 18 01:49 .
drwxrwxr-x 5 xxxx xxxx 4096 Jul 18 01:49 ..
-rw------- 1 xxxx xxxx 96868 Jul 18 01:46 76561198023906459.arkprofile
-rw------- 1 xxxx xxxx 74117232 Jul 18 01:49 Gen2.ark

Could it be possible they changed the name into Gen2.ark for the game ?
Or has it always been like this and i'm the first one to mention it ?

U can see when i check the files in the .tar.bz2

tar -tf main.2021-07-18_01.51.21.tar.bz2

2021-07-18_01.51.21/
2021-07-18_01.51.21/76561198023906459.arkprofile
2021-07-18_01.51.21/Game.ini
2021-07-18_01.51.21/GameUserSettings.ini

In the log file /var/log/arktools$ 
cat arkmanager.log

2021-07-18 01:51:23: [main] Inconsistent casing in map name - gen2.ark does not exist, but Gen2.ark does

All the rest seems to work just fine as I'm used to ! Running a 7 map cluster with no issues, exception for Genesis2

Could there be a temp fix I could apply on my end ?

Extra info : 

Using Debian 9 x64 Server OS
-> arkmanager --version :::
Version: 1.6
Channel: master
Commit: 062b892
Release Tag: v1.6.60a
Blob SHA: 46d9072182d73f514c9f1f73bf7f44000c92c866

arkmanager v1.6: Checking for updates...
Getting latest release...
Your ARK server tools are already up to date

PS = Maybe it could come from this : 
# inside your GameUserSettings.ini file
serverMap="gen2"

I know the map is aliased by Wildcard to work with gen2 or Gen2 but don't know what the effect would be on map file naming.
I'll test this out and let you know !

Greetings,

CaspyBXL

**Comment by klightspeed** [comment]
> 2021-07-18 01:51:23: [main] Inconsistent casing in map name - gen2.ark does not exist, but Gen2.ark does
>
> serverMap="gen2"
>
> I know the map is aliased by Wildcard to work with gen2 or Gen2 but don't know what the effect would be on map file naming.

If Wildcard is aliasing names, then either we need to add an option to specify the name of the world file, or add a mapping into arkmanager that includes those aliases.

**Comment by klightspeed** [comment]
a5fb3dc now makes the inconsistent map naming a warning instead of an error, and copies the map in that case.

**Comment by CaspyBXL** [comment]
After testing on my home test server 

FYI
gen2 works
Gen2 works

Greetings and thanks for the fast fix !

Should I just run upgrade-tools command ?

**Comment by klightspeed** [comment]
v1.6.60b should be available for `upgrade-tools`

**Comment by CaspyBXL** [comment]
ARK Server Tools successfully upgraded
Version: 1.6
Channel: master
Commit: a5fb3dc
Release Tag: v1.6.60b
Blob SHA: 1babd4cddefddfa809ef43fdfba86230228f87e0

Thanks Alot !

PS : Where can one find your Tipping Jar ? xD
