### ISSUE TITLE
Question About the error [S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed

### ISSUE THREAD

**Issue by CaspyBXL** [arkmanager/ark-server-tools#1195]
Hello,

For some reason in my log monitor i can see since the 23 JULY this error come back.
However it seems to impact nothing [Updates, Mod Updates, Query on steam, Or even Steamconnect]
Everything works fine, but ... I do want to kindly ask what could cause this error to flood every time we restart the server it warns for this error

What Am I missing here ?

LOG FROM = /var/log/arktools/arkserver.log ::;;
______________________________________________________
2021-07-23 07:50:08: [main] 2021-07-23 07:50:08: Server PID: 536982
2021-07-23 07:50:09: [main] /usr/local/bin/arkmanager: line 1270: 416347 Aborted                 (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
2021-07-23 07:50:09: [main] [S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
2021-07-23 07:50:09: [main] Setting breakpad minidump AppID = 346110
2021-07-23 07:51:17: [main] 2021-07-23 07:51:17: server is up

LOG FROM = /var/log/arktools/arkmanager.log
_______________________________________________________
2021-07-23 07:50:03: [main] Stopping server; reason: restart
2021-07-23 07:50:07: [main] The server has been stopped
2021-07-23 07:50:07: stop
2021-07-23 07:50:08: restart
2021-07-23 07:50:08: [main] The server is starting...
2021-07-23 07:50:08: [main] The server is now running, and should be up within 10 minutes

Any advice ? Thanks !

**Comment by klightspeed** [comment]
Slow clap, wildcard

https://steamdb.info/patchnotes/7078164/
https://steamdb.info/patchnotes/7072972/
https://steamdb.info/patchnotes/7054306/

It looks like two different people with slightly different build directories (one with the `appmanifest_376030.vdf` and steam dlls, and one without) have been pushing updates to the ARK server.

Back to your topic, I'm guessing at some point in the past, Wildcard bypassed the Steam client check in the server, but in the latest build (7078164) they removed the bypass.

As I said in <https://github.com/arkmanager/ark-server-tools/issues/677#issuecomment-265275928>:
> That "error" can be ignored. It's just the Steam code looking for but not finding the Steam client.

**Comment by CaspyBXL** [comment]
Yes indeed you are correct on something about two clients.
There was a legacy install by steamcmd on this server and then after some OS and kernel upgrades to the server, they changed it to a manual install of steamcmd.

thanks for the quick reply !
Have a great day as always !

**Comment by dev-moribundus** [comment]
@klightspeed Hey klightspeed,
assuming i want to fix this mentioned error though, how can i achieve this?

**Comment by klightspeed** [comment]
> @klightspeed Hey klightspeed, assuming i want to fix this mentioned error though, how can i achieve this?

Assuming you're talking about the `[S_API FAIL] SteamAPI_Init() failed` "error", that'd probably be a UE4 developer question, which I am not.

**Comment by CaspyBXL** [comment]
@dev-moribundus You have to look into where an how you installed the steamcmd version.
in my case it was twice on the machine at two locations. and the logs and update info was in one place and the steamcmd was in another place. So I uninstalled both versions (One my 'apt remove' i believe it was on a  Debian server) and once manually. Then I did a clean install using the manual guide on the steam website.
Once it was installed, adapted the arkmanager config to point on the correct steamcmd file and then the problem was fixed !

I hope this helps.
If you still have some issues, I often have some spare time in the weekends, I could take a look on Discord or something and try to help you out !

**Comment by dev-moribundus** [comment]
@klightspeed you assuming correct. But what is UE4? Unreal Engine 4? What has this to do with SteamAPI?

@CaspyBXL no i tried many different ways to install steamCMD on linux, including the way you mentioned and every time i did a new clean install for linux before trying an new variant of steamCMD install, nothing helps... 
Can you give me a link to the steam Website? 
or is it this? https://developer.valvesoftware.com/wiki/SteamCMD

**Comment by klightspeed** [comment]
> @klightspeed you assuming correct. But what is UE4? Unreal Engine 4? What has this to do with SteamAPI?

The ARK server uses Unreal Engine 4.

The "error" is because it can't find a Steam client, which is entirely expected on a headless server.

**Comment by dev-moribundus** [comment]
@klightspeed understand... thanks for your effort!
