### ISSUE TITLE
Cluster Up- and Download not working

### ISSUE THREAD

**Issue by lhalb** [arkmanager/ark-server-tools#1196]
I set up a server cluster of two instances under Ubuntu 20.04. I have set all the ports and can access both servers individually. 
Ingame I see the `Travel to another Server` Button and I also see the respective other server (tested on both instances).

I can upload a tamed creature, but there is no chance to upload a survivor, which indicates, the directory of the cluster is not writeable. 

The structure of my instances looks like this (everything is installed under the user "ark" and all servers run with this user):

`/home/ark/ARK` --> directory of instance "TI"
`/home/ark/SE`  --> directory of instance "SE"
`/home/ark/ARK-Cluster`  --> directory where the Cluster data should be stored

I use a global `arkmanager.cfg` which looks like this: 
```
# Cluster Settings
arkopt_clusterid=${ClusterID}
arkflag_NoTransferFromFiltering=True
arkopt_ClusterDirOverride=/home/ark/ARK-Cluster

# configfiles for seperate instances
configfile_TI="/etc/arkmanager/instances/TI.cfg"
configfile_SE="/etc/arkmanager/instances/SE.cfg"

```

So I created an config-file under `instances` for The Island, that looks like this:
```
arkserverroot="/home/ark/ARK"
serverMap="TheIsland"

# Cluster Settings
arkopt_clusterid=${ClusterID}
```

And respectively an config file for Scorched Earth, that looks like this 
```
arkserverroot="/home/ark/SE"
serverMap="ScorchedEarth_P"

# Cluster Settings
arkopt_clusterid=${ClusterID}

```

I ran `ls -l` on the `/home/ark/` folder, which gave the following Output
```
drwxrwxr-x  8 ark ark 4096 Jul 29 07:40 ARK
drwxrwxr-x  4 ark ark 4096 Jul 29 07:26 ARK-Cluster
drwxrwxr-x  7 ark ark 4096 Jul 29 07:40 SE

```

So i assume, that the user `ark` should have permissions to write to `ARK-Cluster`

What am I missing here?

**Comment by CaspyBXL** [comment]
Hello,

Just to help you out

Could you try to write the configs as well in TI.cfg and SE.cfg above the clusterid as follows : 

# Cluster Settings
arkopt_ClusterDirOverride="/home/ark/ARK-Cluster"
arkopt_clusterid=${ClusterID}


I think in some cases the quotes matter.

As far as permissions go the folder need to be owned by the same user that launches your arkmanager start commands.
(to be sure I have always in the past set mine to 0775)

drwxr-xr-x  caspybxl caspybxl  4096 Jul 30 07:50 GENESIS
drwxrwxr-x  caspybxl caspybxl  4096 Jul 30 07:10 GENESIS2
drwxrwxr-x  caspybxl caspybxl  4096 Jul 28 17:46 EXTINCTION
drwxrwxr-x  caspybxl caspybxl  4096 Jul 30 12:25 ARK-BACKUPS
drwxrwxr-x  caspybxl caspybxl  4096 Jul 30 00:05 ARK-STAGING
drwxr-xr-x  caspybxl caspybxl  4096 Jul 30 21:45 STEAMCMD
drwxr-xr-x  caspybxl caspybxl  4096 Jul 30 21:45 CACHE
drwxrwxr-x  caspybxl caspybxl  4096 Jul 18 23:54 CLUSTERSHARE

**Comment by lhalb** [comment]
Thank you so much.
The dashes did the trick.
I still don't know, why some arkopts need dashes and others don't, but at least it works now.

**Comment by CaspyBXL** [comment]
Glad to have been helpful to you !
Have fun !
