### ISSUE TITLE
Multiple Arkmanager Processes per Server instance?

### ISSUE THREAD

**Issue by Haidies-AU** [arkmanager/ark-server-tools#1197]
Hi, My cluster of 10 has been running for well over a year with little to no problems.
The arkmanager software is 100% amazing.

I just wanted to confirm how many Arkmanager processes should be open for a 10 map cluster.

I have 10 Shootergame processes active, but 20 Arkmanager processes with 4 other Arkmanager processes that blink on and off

Im running the cluster on Centos7
Sorry in advance if this is listed somewhere else, I really did search everywhere I could think of for an answer before posting.

**Comment by klightspeed** [comment]
If you run `ps -AHF`, it should show the processes in a hierarchical tree.

As arkmanager is a bash script, everything (including delays) is done by running programs.
There will be one monitor process and one subprocess writing to the log, and the periodic check for whether the server is up will involve a subprocess.

**Comment by Haidies-AU** [comment]
Awesome, I just knew it would be something blindingly simple, Thank you so much :D
