### ISSUE TITLE
Ark Autosaveinterval Confirmation

### ISSUE THREAD

**Issue by Haidies-AU** [arkmanager/ark-server-tools#1200]
I use the following cronjob to save all instances every 20 minutes, works a treat.

*/20 * * * * /usr/local/bin/arkmanager --cronjob broadcast @all "World Save Commencing, you may experience some lag or rubber banding" >/dev/null 2>&1
*/20 * * * * sleep 10; /usr/local/bin/arkmanager --cronjob saveworld @all --args -- >/dev/null 2>&1

I also have in my gus.ini
AutoSavePeriodMinutes=20.000000

Why do i feel like im actually saving each instance twice every 20 minutes?

**Comment by klightspeed** [comment]
The autosave would save the world every 20 minutes from when the server started.  I don't know if the autosave keeps running when nobody is logged on - some servers will essentially enter a paused state when nobody is logged on.

**Comment by Haidies-AU** [comment]
so i am actually saving twice. Always thought the saves were a bit TOO laggy.
Is there any way to disable the games auto save and keep the cronjob instead.
or is just a case of set the games autosave to 999 and leave the cronjob to do its thing every 20

**Comment by klightspeed** [comment]
<https://ark.fandom.com/wiki/Server_configuration> suggests 9000000 (about 17 years) will effectively disable auto-save, but any value over 1440 (1 day) should do the trick if you restart daily.
