### ISSUE TITLE
Update downloads an old version instead of updating

### ISSUE THREAD

**Issue by asthomas** [arkmanager/ark-server-tools#1208]
I have a cron job set up to update my private server every night.  The current Linux Ark server version is 341.56.  Whenever my cron job runs, it back-dates my server to version 678.32.  The version number is obviously higher, but it is an old version from when Wildcard messed up their version numbering.

If I then run arkmanager install, my server is re-installed to the correct version.

I don't see anybody else reporting this, so it has to be something in my setup, but I have no idea what.  Can anybody suggest where to look to fix this?

**Comment by klightspeed** [comment]
When it updates to the wrong version, what buildid is it updating to?

If you are using a staging directory, please try clearing it.

**Comment by asthomas** [comment]
Ugh.  Thanks for the staging directory tip.  It's operator error.  I was updating my main instance and then copying the files to the other instances to save download bandwidth.  My script was not updating the main instance properly and my cron job was not sending me email so I did not notice.

**Comment by asthomas** [comment]
Found it.  Closed.
