### ISSUE TITLE
Server doesn't respond to /cancelupdate in-game

### ISSUE THREAD

**Issue by mattague** [arkmanager/ark-server-tools#1209]
I have been trying to setup restarts and updates to repsond to commands in game, but I can't seem to figure out how.  I have added `arkflag_servergamelog=true` to my instance config, I have set `chatCommandRestartCancel=/cu` in my main arkmanager.cfg.

I also noticed that while digging around in /usr/local/bin/arkmanager, at line 1816 it says `find "${arkserverroot}/${arkserverdir}/Saved/Logs" -name 'ShooterGame.*.log' -mmin -5 -print0 |`, but from looking in my ark server directory's Saved/Logs folder, the most recent log is named ShooterGame.log, with backups named ShooterGame-backup-{DATE}.log. When I view the ShooterGame.log file, I can see my chat from in game, including my attempts to cancel the restart/update, but arkamanager never seems to respond to them.

Could this be due to the naming difference of my logs, and if so, how could I rectify this issue?

**Comment by klightspeed** [comment]
Did you replace `ServerGame` with `ShooterGame` in your `/usr/local/bin/arkmanager`?

```
      find "${arkserverroot}/${arkserverdir}/Saved/Logs" -name 'ServerGame.*.log' -mmin -5 -print0 | 
```

`ServerGame.*.log` should contain chat, while `ShooterGame.log` will also contain stuff like the `Commandline`

**Comment by mattague** [comment]
I think I did, but im not 100% sure, i have changed that line back now, my only question is where would i find the `ServerGame.*.log` files? There don't seem to be any in that same folder.

**Comment by klightspeed** [comment]
Is the chat line still formatted like:
```
[2016.07.01-12.45.55:762][947]2016.07.01_12.45.55: klightspeed (Bob): /cancelupdate
```

If so, are the times UTC?

The update cancellation uses the regex `^\[(....)\.(..)\.(..)-(..)\.(..)\.(..):.*` to extract the date and time from the chat log, and assumes that the timestamp is in UTC.

**Comment by mattague** [comment]
Through some trial and error I got this working. Sorry for taking your time, it was a config issue on my part, and failure to just try restarting the entire server.

Thank you for your help though. This project is a godsend, and you are a saint.

**Comment by mattague** [comment]
I am now running into the same issue I think. This is what I get for not documenting my fic in the issue...

**Comment by mattague** [comment]
For posterity: Double check all this advice, and restart the physical server. Dont be dumb Matt
