### ISSUE TITLE
--arkopt,-opt is not behaving as expected

### ISSUE THREAD

**Issue by ThePowershellNinja** [arkmanager/ark-server-tools#1211]
Hi everyone!

I had a quick question, is anyone aware of an issue where if you pass something like `arkmanager run --verbose --arkopt,-NoBattlEye`, the server command line doesn't come out as expected?

I am expecting something like this:
  `2022-01-05 00:50:15: Running /app/server/ShooterGame/Binaries/Linux/ShooterGameServer TheCenter\?SessionName=JustToClayrify.net\ -\ MicahTest\?ServerPassword\?MaxPlayers=70\?GameModIds=731604991\,1609138312\,1400323349\,1342813568\,1315534671\,793605978\,816908578\?Port=9777\?QueryPort=47015\?RCONEnabled=True\?RCONPort=47020\?listen -log -log -NoBattlEye`
  
Instead, I get this:
  `2022-01-05 00:50:15: Running /app/server/ShooterGame/Binaries/Linux/ShooterGameServer TheCenter\?SessionName=JustToClayrify.net\ -\ MicahTest\?ServerPassword\?MaxPlayers=70\?GameModIds=731604991\,1609138312\,1400323349\,1342813568\,1315534671\,793605978\,816908578\?Port=9777\?QueryPort=47015\?RCONEnabled=True\?RCONPort=47020\?listen -log -log -NoBattlEye=-NoBattlEye`
  
It is important to note that if I specify `arkflag_NoBattlEye=true` in the `arkmanager.cfg`, it shows up like it should.
Does anyone know if this is a bug or a configuration issue on my side?

**Comment by cuphi** [comment]
...--arkopt,-NoBattlEye....


Is that comma supposed to be there or is it typo?  Bear in mind that I know ext to nothing about ark-server-tools, but I do that regex can get pissy about a comma.

**Comment by ThePowershellNinja** [comment]
This is out of `arkmanager --help`:
![image](https://user-images.githubusercontent.com/6169890/148150835-6d6685df-6893-4ce4-b477-bf851930ea60.png)

**Comment by klightspeed** [comment]
> ...--arkopt,-NoBattlEye....
> 
> Is that comma supposed to be there or is it a typo? Bear in mind that I know next to nothing about ark-server-tools, but I do that regex can get pissy about a comma.

Yes, the comma is supposed to be there.  v1.6.61 should fix the incorrect option.
