### ISSUE TITLE
Server not online

### ISSUE THREAD

**Issue by 1231sadqwf** [arkmanager/ark-server-tools#1214]
After I run 'arkmanager start' and I check the status after 1 hour, the server online keep stuck at offline
![image](https://user-images.githubusercontent.com/62546980/149747126-1f15e404-149a-41c0-8b1b-bec3423966ef.png)

**Comment by klightspeed** [comment]
Do you have any mods installed?  You have `0 / 0 players`, which is a sign that either a mod failed to initialize properly, or it failed to bind to a port.

**Comment by 1231sadqwf** [comment]
I didn't install any mod
![image](https://user-images.githubusercontent.com/62546980/149757575-b8a94f59-0f7e-443d-ae16-44c5dd4e6dab.png)

**Comment by 1231sadqwf** [comment]
I got this error
![image](https://user-images.githubusercontent.com/62546980/149758377-caf3a29f-8539-4517-bd0e-084c4576ba6c.png)

**Comment by klightspeed** [comment]
> I got this error ![image](https://user-images.githubusercontent.com/62546980/149758377-caf3a29f-8539-4517-bd0e-084c4576ba6c.png)

That "error" just means that it can't connect to the steam client, which is normal when not running on a server.

Do you have any other game servers running on the same host?  Also, are you trying to run the server on a low memory server (i.e. 4GB or less)?

**Comment by 1231sadqwf** [comment]
> > I got this error ![image](https://user-images.githubusercontent.com/62546980/149758377-caf3a29f-8539-4517-bd0e-084c4576ba6c.png)
> 
> That "error" just means that it can't connect to the steam client, which is normal when not running on a server.
> 
> Do you have any other game servers running on the same host? Also, are you trying to run the server on a low memory server (i.e. 4GB or less)?

no, and my server is 12gb
