### ISSUE TITLE
players 0/0 and map is blank

### ISSUE THREAD

**Issue by darknessdeadly** [arkmanager/ark-server-tools#1218]
when i start up my server for the first time it works normal.but if i shut it down and start again it has blank map and max players is 0/0.
and ive port forward all the ports.im only running one server at a time.and if i delete saves it works again but when i shut it down and start it back up the problem happens.

**Comment by klightspeed** [comment]
Do you have any mods installed?  Sometimes a mod (or a certain combination of mods) can either cause map corruption, or cause an error while loading a map.

**Comment by darknessdeadly** [comment]
> Do you have any mods installed? Sometimes a mod (or a certain combination of mods) can either cause map corruption, or cause an error while loading a map.

yup
2447186973,1136125765,1189824179,1287442228,1404697612,1591643730,1609138312,1967741708,2182894352,633831197,679529026,731604991,751991809,756389708,768023924,821530042,889745138

**Comment by klightspeed** [comment]
Unfortunately there's no easy way of finding out which mod is causing the issue, other than to use a process of elimination.
The usual course of action is to start with no mods, then add one mod at a time until you run into the error, exclude that mod, and continue until there are no mods left to test.
There may also be mod dependency issues at play (e.g. one mod depending on another not in your mod list, or a dependency of a mod coming after that mod in the mod list).
