### ISSUE TITLE
Run Command with @all

### ISSUE THREAD

**Issue by Diyagi** [arkmanager/ark-server-tools#1230]
Im having a issue trying to use the command `arkmanager run @all`, when i use this command, arkmanager dosent properly start all instances,
instead, it starts the first instance then hangs, it waits for this instance to exit (wait for an exit code) and then starts the next instance.

While i could use `arkmanager start @all`, it makes things harder inside a container environment, since after starting all instances, the command will then exit making the container stop.

I also tried `arkmanager start @all` with `arkmanager wait --all --stopped`, but during tests, whenever i restart the first instance, the wait command would exit making the container stop.

**Comment by klightspeed** [comment]
`arkmanager run` runs the instance in the foreground, and so can only run a single instance.

`arkmanager wait --all --stopped` without an instance specified will only wait on the default instance.
