### ISSUE TITLE
Cluster Files are not saved by the backup command (could this maybe be a feature added ?)

### ISSUE THREAD

**Issue by CaspyBXL** [arkmanager/ark-server-tools#1231]
Hello @klightspeed
In the past I have always made a custom backup of cluster folder (wich is not inside the server root but rather accessable folder outside of each server since the location is pretty much the same folder.

Example : 
Servers are in folders  = arkserverroot="/home/ark/XXX"
As Cluster folder shared by all server-instances = arkopt_ClusterDirOverride="/home/ark/clusters"

When we do the backup command it saves everything that is in : 
"/home/ARK/ISLAND/ShooterGame/Saved/"
profiles, map, tribute etc ...

But if for example a player just transfered and never connected to another map the profile and his tribute data is stored in the "/home/ark/clusters"

Would it be possible to include it to the general backup command and make ArkManager even better ?

For example logic would say
Step1 : check if arkopt_ClusterDirOverride is used
Step2 : fetch location
Step3 : add contents to the bzip when using 'arkmanager backup'

I could remain doing this manually but for example I often refer people to Arkmanager and a friend came to me saying his server wen out, and when restoring the data from his backups, some players transfered from servers the day before but never finished and connected to the other map, they intended to do it the day after ... so yeah bad luck cuz they basically lost everything they put in the transfer system including their char profiles, we managed to fetch their profiles from an older backup and restore their char but all the items and dino's for example where lost, we had to boot another instance just to let them refetch all their stuff and then manually copy it over wich took like 2 hours and extra ressources, we did it in the end, but there is kinda a better way to do this using arkmanager if you would not mind maybe writing that beautifull code and adding it as a feature, or even a separate command but something reliable and so people can use it and don't have to invent their own system on the side, again for me, I have been using my own script to backup this data every hour for many years using cron and linux tar commands, but it would be nice for people to have a way to use this in Arkmanager.

if you are missing info, or something is not clear, let me know !
I can always elaborate or share my experience, being an Ark Admin and hosting servers since 2017 !
Always using Arkmanager ofc and on Linux ^_^ Cuz F*** Windows or limited hosting company's

Well I hope you are doing well and everything is fine !
Kind regards and Greetings,
A forever Arkmanager Fan,

CaspyBXL

**Comment by klightspeed** [comment]
6e2c92549da33fa960012190ab146daadbc49c96 adds a `--cluster` option to the `arkmanager backup` command, which should include the cluster files in the backup.

**Comment by CaspyBXL** [comment]
Dear @klightspeed Thank you verry much sir !
