### ISSUE TITLE
Arkmanager Service

### ISSUE THREAD

**Issue by KGM6911** [arkmanager/ark-server-tools#1243]
Just did a fresh install and forgot to add --install-service when I installed.  I have my servers running and realized this when I rebooted and they didn't start.  How can I install the arkmanager service at this stage?   Will I need to redo my .cfg files or anything else?
Thanks!

**Comment by klightspeed** [comment]
Running the installer again should not overwrite your configs - performing an arkmanager upgrade uses the same install.sh script that is called by the netinstaller.

**Comment by KGM6911** [comment]
Thank you!
