### ISSUE TITLE
Discord Web Hook Variables 

### ISSUE THREAD

**Issue by Nytridr** [arkmanager/ark-server-tools#1246]
# Notifications
# discordWebhookURL="https://discordapp.com/api/webhooks/{webhook.id}/{webhook.token}"
 notifyMsgShuttingDown="Shutting down"
 notifyMsgStarting="{instance}.{ark_SessionName} Starting"
 notifyMsgServerUp="{instance}.{ark_SessionName} Server is up /n cosmicknights.net:{instance}.{ark_port}"
 notifyMsgStoppedListening="Server has stopped listening - restarting"
 notifyMsgServerTerminated="Server exited - restarting"
 notifyTemplate="{instance.ark_SessionName}: {msg}"
 noNotifyWarning=true
 notifyCommand='echo "$msg" | mailx -s "Message from instance ${instance} on server ${HOSTNAME}" "email@domain.com"'

Wondering if you could add something like this to be able to pull info out of the instance files before it post on Discord.  I have changed some of the stuff in the notify stuff.. so hopefully you can follow along with what I am trying to do.

**Comment by klightspeed** [comment]
If you want to include `${ark_SessionName}` in your notification templates, you should be able to set `notifyvar_SessionName="${ark_SessionName}"` in the instance file, then use `{SessionName}` in the notify templates.
