### ISSUE TITLE
Server Shows on Steam Servers

### ISSUE THREAD

**Issue by ECEstal** [arkmanager/ark-server-tools#1250]
But not in game. Not sure if this is a manager issue or an issue with the actual Ark Server

**Comment by ECEstal** [comment]
I can find it in the steam browser and add it to the favorites tab, but when I go in game it does not show up on the favorites list and cannot be connected to. Gives the Unable to query server for invite using both internal and external IP. I tested on a Windows install and I was able to connect both internally and externally, so I'm lead to believe that wildcard broke something on the linux servers

**Comment by klightspeed** [comment]
With trying to connect to the external IP, do you have port forwarding set up in your router, and does your router support hairpin routing?

**Comment by ECEstal** [comment]
> With trying to connect to the external IP, do you have port forwarding set up in your router, and does your router support hairpin routing?

Yes on both counts. I can actually switch the forwards to the windows install and connect as well. Seeing as I can’t connect within the lan even tells me this isn’t a port forwarding issue

**Comment by klightspeed** [comment]
Looking at the fact that it is bound to UDP ports 7777 / 7778, I thought the game ports used to be TCP ports and not UDP ports, but testing here (and looking back at a strace from last year) shows that it is binding to UDP ports.

Testing here with v357.11 (build ID 10903952) I am able to connect to a server hosted from my local Linux box, whether using the LAN option or (once my router decided to behave itself) connecting to my external IP address.

**Comment by ECEstal** [comment]
> Looking at the fact that it is bound to UDP ports 7777 / 7778, I thought the game ports used to be TCP ports and not UDP ports, but testing here (and looking back at a strace from last year) shows that it is binding to UDP ports.
> 
> Testing here with v357.11 (build ID 10903952) I am able to connect to a server hosted from my local Linux box, whether using the LAN option or (once my router decided to behave itself) connecting to my external IP address.

Alright, so something going wrong on my end. Thank you.

**Comment by ECEstal** [comment]
> Looking at the fact that it is bound to UDP ports 7777 / 7778, I thought the game ports used to be TCP ports and not UDP ports, but testing here (and looking back at a strace from last year) shows that it is binding to UDP ports.
> 
> Testing here with v357.11 (build ID 10903952) I am able to connect to a server hosted from my local Linux box, whether using the LAN option or (once my router decided to behave itself) connecting to my external IP address.

Any chance you guys have a discord server I could meet with someone and we could check some settings out? Used to run my own ark servers and had no issues back then. 2 days later I still can't connect to a ubuntu hosted server that I see steam server browser finding with no issues.
