### ISSUE TITLE
Using clusters

### ISSUE THREAD

**Issue by AlexanderMoebius** [arkmanager/ark-server-tools#1253]
I have setup multiple instances on the same machine to run as a cluster.

debian dedicated server (1 IP)
arkserverroot is the same for all instances
arkbackupdir is the same (I know, that this is not recommended, but should have nothing to do with the issue)
serverMap is different
ark_SessionName is different
ark_AltSaveDirectoryName is different for each server
arkopt_clusterid and arkopt_ClusterDirOverride are the same.
ports are different

What happens is that it is possible to join each server. Also items can be transferred. But by using the 'join another server' feature at an obelisk, no server is found.
By joining directly, I can join every server. But the character can not be transferred. (Character Transfer is activated, ark_PreventDownloadSurvivors=False)

The computer I use is at a different location. Therefore there should also not be a problem with NAT lookup I think.

Any idea?

**Comment by klightspeed** [comment]
Is the cluster id reasonably unique - e.g. a GUID or something that nobody else is likely to be using?

**Comment by AlexanderMoebius** [comment]
yes, it is.
And also also letters, no numbers or special characters

**Comment by AlexanderMoebius** [comment]
Problem is solved. Had nothing to do with ark manager, sry
