### ISSUE TITLE
ark_ALLOW_FLYER_SPEED_LEVELING=true do not work aswell as ark_BabyMatureSpeedMultiplier=20.0

### ISSUE THREAD

**Issue by EinsPhoenix** [arkmanager/ark-server-tools#1256]
We have tried to increase the growth rate of baby dinosaurs and enable speed leveling for flying dinos on a server, but unfortunately, it is not working. Can anyone help me?

**Comment by klightspeed** [comment]
`bAllowFlyerSpeedLeveling` and `BabyMatureSpeedMultiplier` go into `Game.ini` and not the server options string.
