### ISSUE TITLE
Mod Option Headers in GameUserSettings.ini

### ISSUE THREAD

**Issue by ventra007** [arkmanager/ark-server-tools#1262]
Hi,

Forgive me if this has been covered or asked somewhere else, but I'm failing to find the answers.

Where and how would we capture Mod settings in the config files?

Specifically, Structures Plus.
It requires the header "[StructuresPlus]" in the GameUserSettings.ini file, but i'm assuming the actual file where it needs to read it from is the arkmanager.cfg, but how do we capture the header and the subsequent configs we want to apply?

Will we just type it all out as per normal? or are there some prefixes required like the "ark_" and "arkopt_" ones?

Many thanks in advance.

**Comment by klightspeed** [comment]
The `ark_`, `arkopt_`, and `arkflag_` settings in `arkmanager.cfg` configure what options are passed on the server's command-line.  If no such options exist, then you will need to edit the `GameUserSettings.ini`.

**Comment by ventra007** [comment]
Hi,

Ok i see. So changes I make won't get overwritten by the arkmanager.cfg file?

**Comment by klightspeed** [comment]
The game server will generally only overwrite settings that are either specified on the command-line, modified by an admin in the game, or are considered by the game server to be invalid.
