### ISSUE TITLE
Confusion on ark_ , arkopt_ , and arkflag_

### ISSUE THREAD

**Issue by md-burden** [arkmanager/ark-server-tools#1273]
I am trying to get a server set up with a lot of the GameUserSettings changed. From reading other issues it is stated that ark_ , arkopt_ , and arkflag_ is used for command line arguments and everything else needs to be set in GameUserSettings.ini or Game.ini files.
The confusion I am having is how options like ark_MaxPlayers work if this is NOT a command line argument. I have not seen a list of variables that work in the arkmanager.cfg/main.cfg and what needs to be set in the GameUserSettings.ini/Game.ini files.

Can someone clear this up for me if possible?

**Comment by klightspeed** [comment]
In the options in <https://ark.wiki.gg/wiki/Server_configuration#Command_line_options>:
* `?option=value` is specified using `ark_option=value`
* `-option=value` is specified using `arkopt_option=value`
* `-option` is specified using `arkflag_option=true`
