### ISSUE TITLE
How to enter console either locally or externally.

### ISSUE THREAD

**Issue by Crepnut** [arkmanager/ark-server-tools#453]
Is there a way to get into the console window and see what's happening on the server chat wise or command wise trough Linux Terminal window? Tried to find any log files so i could read it etc.

When i use getchat it only gives me the last 15 lines in the chat, and i can't use it more than ones each session.

Tried remote tools but can't connect.

(I know that the lgsm have the console option)

**Comment by Jeanolos** [comment]
You could use screen -S arkserver arkmanager run @instance for having a console on a screen, but I'm not sure if it's showing things or if it's interactive

**Comment by klightspeed** [comment]
The `-servergamelog` option should log chat into the `ServerGame.log` file.

Shall we add e.g. a `watch-chat` command, which executes the `GetChat` RCON command every few seconds, and possibly also saves it to a log file?
