### ISSUE TITLE
Can somone make a video Tutorial?

### ISSUE THREAD

**Issue by acn0l0gia** [arkmanager/ark-server-tools#467]
Hello All,

My request is in the question. A lot of people are not really trusted with linux or don't understand all the steps to do for installing the ark server with mods. so maybe a short video tutorial should be welcome for helping those guys for the server configuration. I'm one of these guys XD. or if there is anyone that can help me out using skype / teamviewer to help me solve my issues. 

Thank you in Advance.

**Comment by spitfire1081** [comment]
At least a TUTORIAL, doesn´t need to be in video format.
I am having issues with the mods update.
Can anybody please explain how do we setup to update arkserver and mods?
