### ISSUE TITLE
Wishing to Contribute to Upstream

### ISSUE THREAD

**Issue by AsavarTzeth** [arkmanager/ark-server-tools#491]
Greeting to all the nice maintainers of the ark-server-tools project.

For about a year I have maintained a a personal fork of your project and adjusted it to fit my own use cases. During that time I have diverged quite a bit from upstream. This happened due to my own lack of time and most of my work was and remains to specific for merging with your own work.

However times have changed and I have decided to refocus and to try and contribute as much to you as possible. After all it is a win for everybody.

My time is of course still limited and I obviously can't spend too much of it on a script that manages game servers. I have a growing list of todo items so I feel the best way to do this is I simply start with sharing the best ideas I currently have, that are the most likely be accepted by everybody.

As an added note, most of my work will be focused on consistent styling (I know, boring/controversial?), security, quality of code, as well as some focus on systemd support and fixes specific to issues that occur on systems that use systemd for init. Obviously all of my systemd additions will be made 100% optional and intrusive to users of other init systems.

Now that the introductions all done, here are some of my todo items. Please tell me if you are interested in any of them so I can plan my work appropriately.
1. I wish to add some security checks on the configuration files. Specifically:
   - The ownership of the file should be the root user or the user that executes the script. Nobody else should ever be the user. That is what we have groups for.
   - Permissions should be something like mode 0600 or possibly 0640, 0660, the group octet is up for discussion. In any case others have no reason to read write or execute it.
   - Check syntax of the file. Basically we only need to allow lines that start with # (for comments) and variable=value lines. Anything else could be malicious code that had been inserted, which would be easy without the checks above.
   - Only when these checks pass does it source the file. Otherwise it will exit with an error sent to log.
2. I wish to rework the logging system you currently have to one that makes using the systemd journal (or anything that uses stderr directly) configurable. For this to work there needs to be a common error function. That function should be the only place that redirects output. A simple if statement could check for a configure option and do the redirect to stderr or the log file (like it does now).
3. When you stop the server you now support the usage of --saveworld. This works fine, but I would add a simple sanity check that checks if ark_RCONEnabled="True" first. It's not perfect, certainly does not beat something like checking if something is listening on ark_RCONPort. But it gets the work done without added dependencies.
4. Why did you remove ark_RCONPort by the way? Do you assume we use game config file directly. Also, you have not removed it from the documentation. If possible I would add this again, unless you have a good reason of course.
5. Is it somehow possible to redo parts like ark_ServerAdminPassword so that it instead writes to the `GameUserSettings.ini`? I don't know if I feel 100% okay with any user on the system being able to read the password by using `systemctl status`, `ps`, /proc/*, etc.
6. I wish to improve the systemd unit files. I could for example offer you the best, yet most system compatible, security mechanisms that are built into systemd. I am also a bit confused why you choose to do a arkmanager.init file that arkmanager.service calls. I am actually quite sure there is native support for what you wish to accomplish there.
7. When arkmanager looks for the main configuration file I wish to add an else to the first location that also looks in /usr/local/etc. I happen to follow certain practices and guidelines that means my configuration file will not be used if if located in my location of choice.
8. The styling on the functions are inconsistent which is often considered bad practice. I felt that area was one of the easiest to fix, if you would let me. Of course we would have to have a decision on what format I should use and which should be followed from that point and forward. Personally I follow the [Google Style Guide](https://google.github.io/styleguide/shell.xml?showone=Function_Names#Function_Names), but I will do anything you wish, or otherwise agree upon.
9. Constants should be on top, not hidden between functions. They should preferably be capitalized and they should be readonly which will ensure they remain constants. This is a hard one, but I would start with just moving the `# Variables` section above the installation functions, then set any variables that never need to be changed during runtime as readonly.

That is all for now. I know, it is a lot for a new contributor but as I explained above. Just take these as suggestions and anything you think is good I will do for you. If you have any questions or suggestions, please share.

Also tell me if you prefer split pull requests or all in one. I would go for split by feature so you can easier comment on specific issues and merge anything that is good as fast as possible.

**Comment by klightspeed** [comment]
> 3. When you stop the server you now support the usage of --saveworld. This works fine, but I would add a simple sanity check that checks if ark_RCONEnabled="True" first. It's not perfect, certainly does not beat something like checking if something is listening on ark_RCONPort. But it gets the work done without added dependencies.

The script currently retrieves the RCON port from either the arkmanager config or from `GameUserSettings.ini`.  It then tries to connect to the specified port.  As long as you have an iptables rule to accept packets on the loopback interface, if nothing is listening on the port there should be an immediate connection refused, and the shutdown should proceed.

> 4. Why did you remove ark_RCONPort by the way? Do you assume we use game config file directly. Also, you have not removed it from the documentation. If possible I would add this again, unless you have a good reason of course.

`ark_RCONPort` etc have been moved to the individual instance configs.

> 5. Is it somehow possible to redo parts like ark_ServerAdminPassword so that it instead writes to the `GameUserSettings.ini`? I don't know if I feel 100% okay with any user on the system being able to read the password by using `systemctl status`, `ps`, /proc/*, etc.

If you don't want to pass ServerAdminPassword on the commandline, you can put it into `GameUserSettings.ini`, and the script will use that for RCON commands.

> 6. I wish to improve the systemd unit files. I could for example offer you the best, yet most system compatible, security mechanisms that are built into systemd. I am also a bit confused why you choose to do a arkmanager.init file that arkmanager.service calls. I am actually quite sure there is native support for what you wish to accomplish there.

The `arkmanager.init` script retrieves the list of instances to run, and starts `arkmanager@<instance>.service` for each of those instances.

**Comment by AsavarTzeth** [comment]
Okay thank you for your answers.

> 
The script currently retrieves the RCON port from either the arkmanager config or from GameUserSettings.ini. It then tries to connect to the specified port. As long as you have an iptables rule to accept packets on the loopback interface, if nothing is listening on the port there should be an immediate connection refused, and the shutdown should proceed.

It is my bad for missing the details about RCON being in the the instance file. Can you be certain that the connection being refused won't add a delay? I also wonder does the script give proper feed back to a less technical user what the issue is?

I still think an added check combined with logging could improve performance and make debugging easier. But I accept that this is a minor issue. Remember though I am not bugging you about a minor issue, I am offering free improvements.

> 
If you don't want to pass ServerAdminPassword on the commandline, you can put it into GameUserSettings.ini, and the script will use that for RCON commands.

Well there you made me feel stupid. I knew that yet I posted it as an issue. I guess that is what I get for adding an issue late in the evening :)

> The arkmanager.init script retrieves the list of instances to run, and starts arkmanager@<instance>.service for each of those instances.

If that is all it need to do I can confirm that this is possible without your script, using only systemd built in mechanics. Debian for example is full of examples where they do this. I could make an example pull request for your consideration.

I feel you have picked apart my lesser ideas, but you have said nothing about the good ones. Are there any initial thoughts at all on the better points?

**Comment by klightspeed** [comment]
> 1. I wish to add some security checks on the configuration files. Specifically:
>   - The ownership of the file should be the root user or the user that executes the script. Nobody else should ever be the user. That is what we have groups for.

Making root the owner of files in /etc or /usr/local/etc makes sense.  User-local configs are owned by the user, as they are stored in `$HOME/.config/arkmanager/instances`

>   - Permissions should be something like mode 0600 or possibly 0640, 0660, the group octet is up for discussion. In any case others have no reason to read write or execute it.

This makes sense for instance configs, where those instance configs are owned by the user under which arkmanager runs.  It does not make sense for arkmanager.cfg, especially if the server administrator allows multiple users to manage ARK instances.

>   - Check syntax of the file. Basically we only need to allow lines that start with \# (for comments) and variable=value lines. Anything else could be malicious code that had been inserted, which would be easy without the checks above.

This could be done by either treating the config file like an ini file, and/or breaking the `getConfigVar()` function out of `runAsRoot()`.  Either that, or as mentioned below split the majority of the script out to a perl or python module, and use that language's config file parsing.

>   - Only when these checks pass does it source the file. Otherwise it will exit with an error sent to log.

Chicken and egg.  The log directory path is stored in the config file.  Would we define a default log path, use e.g. `logger`, or just print the error to stderr?

> 2. I wish to rework the logging system you currently have to one that makes using the systemd journal (or anything that uses stderr directly) configurable. For this to work there needs to be a common error function. That function should be the only place that redirects output. A simple if statement could check for a configure option and do the redirect to stderr or the log file (like it does now).

i.e. anything that would go to `arkmanager.log` or `arkserver.log` would instead be passed to a logger function?

That logger function would be responsible for setting the log tag (systemd `SYSLOG_IDENTIFIER`) set to e.g. `arkmanager@${instance}` if using syslog or jouornald, and if using log files it would be responsible for prepending the date/time to the log entry and splitting the logs out to separate files.

> 7. When arkmanager looks for the main configuration file I wish to add an else to the first location that also looks in /usr/local/etc. I happen to follow certain practices and guidelines that means my configuration file will not be used if if located in my location of choice.

This would probably be part of the config file parsing.  e.g.:
  - have a `SYSCONFDIR` constant that defaults to `/etc/arkmanager`
  - have a `--sysconfdir` parameter and `SYSCONFDIR` variable in `install.sh` that modifies that constant
  - have a `USERCONFDIR` constant that defaults to `.config/arkmanager`
  - have a `--userconfdir` parameter and `USERCONFDIR` variable in `install.sh` that modifies that constant
  - look for global variables in `${SYSCONFDIR}/arkmanager.cfg`, `${HOME}/.arkmanager.cfg` and `${HOME}/${USERCONFDIR}/arkmanager.cfg`.
  - look for instance variables in any of the above files, in the file specified by `cfgfile_${instance}` in one of the above files, or in one of `${SYSCONFDIR}/instances/${instance}.cfg` or `${HOME}/${USERCONFDIR}/instances/${instance}.cfg`

> 8. The styling on the functions are inconsistent which is often considered bad practice. I felt that area was one of the easiest to fix, if you would let me. Of course we would have to have a decision on what format I should use and which should be followed from that point and forward. Personally I follow the [Google Style Guide](https://google.github.io/styleguide/shell.xml?showone=Function_Names#Function_Names), but I will do anything you wish, or otherwise agree upon.

This would probably be part of a move toward implementing the core functionality of the script as a perl or python module, and have the arkmanager shell script be a wrapper script for that module.  I don't think the Google style guide would consider a 2300 line script to be small.

> 9. Constants should be on top, not hidden between functions. They should preferably be capitalized and they should be readonly which will ensure they remain constants. This is a hard one, but I would start with just moving the `# Variables` section above the installation functions, then set any variables that never need to be changed during runtime as readonly.

Probably would go along with splitting the upgrade / installation functions out to a separate `upgrade-arkmanager` script, which would be called by `arkmanager upgrade`.  This would simplify the part of the script that can potentially run as root.  Most of the constants would move to the aforementioned module.

>> The arkmanager.init script retrieves the list of instances to run, and starts arkmanager@.service for each of those instances.

> If that is all it need to do I can confirm that this is possible without your script, using only systemd built in mechanics. Debian for example is full of examples where they do this. I could make an example pull request for your consideration.

So systemd is able to start one instance for each `${instance}.cfg` file in a certain directory?

**Comment by AsavarTzeth** [comment]
> Making root the owner of files in /etc or /usr/local/etc makes sense. User-local configs are owned by the user, as they are stored in $HOME/.config/arkmanager/instances

So we agree that system installation paths should be root user and $HOME/.config should only be the executing user? The executing user should always be the same as the owner, right? I am basing this assumption on what we seem to agree upon next.

> This makes sense for instance configs, where those instance configs are owned by the user under which arkmanager runs. It does not make sense for arkmanager.cfg, especially if the server administrator allows multiple users to manage their own ARK instances.

Oh right, instances still need read access to arkmanager.cfg. I assume forcing everyone to use setup groups for this would be to expect to much by default? It does not stop the administrator from setting it up this way manually post installation though. So fair point there.

But we agree on instance files though, and since those are owned by regular users they are probably the greater risk anyways.

> This could be done by either treating the config file like an ini file, and/or breaking the getConfigVar() function out of runAsRoot(). Either that, or as mentioned below split the majority of the script out to a perl or python module, and use that language's config file parsing.

I have to admitt, in my fork I ripped out all support for running as root and so I had missed the getConfigVar function. Do I understand its current role is to parse the config file when you run as root?

I have no current experience outside of shell scripting so I could not help much with perl or python. But I am well aware of why this would be better and safer way of doing it. If someone is able to do it that would be great.

> Chicken and egg. The log directory path is stored in the config file. Would we define a default log path, use e.g. logger, or just print the error to stderr?

Very true, that is a bit of a problem. I guess my personal preference for stderr and the systemd journal contributed to that miss.

The problem with a default log path is we would preferably use what is default in arkmanager.cfg (that is /var/log/arkmanager), right? Does this directory always exist and do we have write access? even if we run arkmanager as a non root user?

Simply writing to stderr would probably be our only sane choice, at least for now. But since I would do that anyway I admit it is a slightly biased opinion.

> i.e. anything that would go to arkmanager.log or arkserver.log would instead be passed to a logger function?

> That logger function would be responsible for setting the log tag (systemd SYSLOG_IDENTIFIER) set to e.g. arkmanager@${instance} if using syslog or jouornald, and if using log files it would be responsible for prepending the date/time to the log entry and splitting the logs out to separate files.

Do I understand this correctly? You want to enable full support for the systemd journal, including compatibility with syslog behavior? Why?

All you need to do is offer two options. One is writing to the log file directly, like it does now. The other is to redirect to stderr and let systemd-journald handle the rest.

In any case, here is an (hasty) example of the timestamp function converted to a logger function:
```
logger() {
  if [[ "$log_type" == "systemd-journal" ]]; then
    echo "$(date +%T) $@" >&2
  else
    echo "$(date +%T) $@" >> "$logdir/$arkmanagerLog"
  fi
}
```

And here is a line that will call it:
```
logger "error: this is an error message."
```

I realize the timestamp function is currently used for other purposes than log output. This is just a quick example, based on it.

> This would probably be part of the config file parsing. e.g.:

> * have a SYSCONFDIR constant that defaults to /etc/arkmanager
* have a --sysconfdir parameter and SYSCONFDIR variable in install.sh that modifies that constant
* have a USERCONFDIR constant that defaults to .config/arkmanager
* have a --userconfdir parameter and USERCONFDIR variable in install.sh that modifies that constant
* look for global variables in ${SYSCONFDIR}/arkmanager.cfg, ${HOME}/.arkmanager.cfg and ${HOME}/${USERCONFDIR}/arkmanager.cfg.
* look for instance variables in any of the above files, in the file specified by cfgfile_${instance} in one of  the above files, or in one of ${SYSCONFDIR}/instances/${instance}.cfg or ${HOME}/${USERCONFDIR}/instances/${instance}.cfg

My initial idea was to have arkmanager look for this extra path as an else to /etc/arkmanager, which would just work (for now), like this:
```
if [ -f "/etc/arkmanager/arkmanager.cfg" ]; then
  source /etc/arkmanager/arkmanager.cfg
elif [ -f "/etc/arkmanager/arkmanager.cfg" ]; then
  source /usr/local/etc/arkmanager/arkmanager.cfg
fi
```
But I can see why you would want a more long term and well thought through solution.

As for your suggestions.
* Unfortunately anything dependent on install.sh would be of no use for me, because I don't use it and cannot be dependent on it.
* I like the idea of --sysconfdir and --userconfdir parameters but in my use case I would need to be able to do it from service files.
* Could you elaborate on the last two points? I am not quite sure I understand it properly. Is it arkmanager that looks for the variables in the listed files? If so does that not create a chicken and egg issue (specifying config dir in config file itself)?

For added perspective, this is how I currently handle instances and configuration. I enable arkmanager@(instancename/configfile) and that handles instance specific configuration just like most package maintainers seem to do it. The only issue to me is the global configuration path that remains hard coded (which I then need to change and maintain in my fork).

> This would probably be part of a move toward implementing the core functionality of the script as a perl or python module, and have the arkmanager shell script be a wrapper script for that module. I don't think the Google style guide would consider a 2300 line script to be small.

So in other words you have plans to rewrite a lot of the script, so why bother with the current styling? Because as the Google style guide says larger projects should probably not be written in shell. If that truly is your long term plan you have my full support. Unfortunately I currently know nothing about perl or python at this time, but that might change one day.

> Probably would go along with splitting the upgrade / installation functions out to a separate upgrade-arkmanager script, which would be called by arkmanager upgrade. This would simplify the part of the script that can potentially run as root. Most of the constants would move to the aforementioned module.

That sounds even better than what I hoped for. I admit I ripped out that entire part entirely so you would do me huge favor in terms of maintenance. As an added bonus, most constants would be at the top already if you excluded the upgrade / installation functions.

> So systemd is able to start one instance for each ${instance}.cfg file in a certain directory?

Well technically there are two ways of doing it. One way (probably the correct way) is to make a target unit instead of a service. You then add that target to the `[Install]` section of the arkmanager@.service file and enable the target.

Another way, which have become popular in Debian is to make the program.service part of the program@.service unit. Why they do this is because they need the ability to reload all instances as well Here I have posted an example from the Debian postgresql package.

```
# /lib/systemd/system/postgresql.service
# systemd service for managing all PostgreSQL clusters on the system. This
# service is actually a systemd target, but we are using a service since
# targets cannot be reloaded.

[Unit]
Description=PostgreSQL RDBMS

[Service]
Type=oneshot
ExecStart=/bin/true
ExecReload=/bin/true
RemainAfterExit=on

[Install]
WantedBy=multi-user.target
```
```
# /lib/systemd/system/postgresql@.service
[Unit]
Description=PostgreSQL Cluster %i
ConditionPathExists=/etc/postgresql/%I/postgresql.conf
PartOf=postgresql.service
ReloadPropagatedFrom=postgresql.service
Before=postgresql.service
```

So which way is the best one really depends if you need reloading. As far as I know the Unreal Engine is not capable of reloading configuration on the fly.

**Comment by klightspeed** [comment]
>> This could be done by either treating the config file like an ini file, and/or breaking the getConfigVar() function out of runAsRoot(). Either that, or as mentioned below split the majority of the script out to a perl or python module, and use that language's config file parsing.

> I have to admitt, in my fork I ripped out all support for running as root and so I had missed the getConfigVar function. Do I understand its current role is to parse the config file when you run as root?

`getConfigVar` extracts the value of a config variable from `/etc/arkmanager/arkmanager.cfg`, and sends it value to stdout, where it is then captured by command substitution.

> Do I understand this correctly? You want to enable full support for the systemd journal, including compatibility with syslog behavior? Why?
>
> All you need to do is offer two options. One is writing to the log file directly, like it does now. The other is to redirect to stderr and let systemd-journald handle the rest.

So, you're just talking about the logging that occurs in the service?  In that case, we can just redirect stdout to stderr in the arkmanager@.service file, since it runs `arkmanager run @instance`, which does not redirect its output to `arkserver.log`

> So in other words you have plans to rewrite a lot of the script, so why bother with the current styling? Because as the Google style guide says larger projects should probably not be written in shell. If that truly is your long term plan you have my full support. Unfortunately I currently know nothing about perl or python at this time, but that might change one day.

I was thinking about it, and it may actually be better to split up the monolithic script into a set of smaller scripts and function libraries, with the functions that are mostly Perl (such as `rconcmd`) split out to Perl scripts.  `arkmanager` would still live in `$EXECPREFIX/bin`, but it would just parse the arguments and call the appropriate script from `$EXECPREFIX/libexec/arkmanager`.

`arkmanager@.service` would then run something like `$EXECPREFIX/libexec/arkmanager/run-server @instance >&2`

> Well technically there are two ways of doing it. One way (probably the correct way) is to make a target unit instead of a service. You then add that target to the [Install] section of the arkmanager@.service file and enable the target.
>
> Another way, which have become popular in Debian is to make the program.service part of the program@.service unit. Why they do this is because they need the ability to reload all instances as well Here I have posted an example from the Debian postgresql package.

This would be fairly easy if we didn't worry about supporting the `configfile_*` options in `arkmanager.cfg`, and just supported auto-starting instances with a file or symlink present in e.g. `{,/usr/local}/etc/arkmanager/autostart-instances`
