### ISSUE TITLE
Is There a command to wipe out the server

### ISSUE THREAD

**Issue by spitfire1081** [arkmanager/ark-server-tools#496]
As the title, my question is if there is any kind of tool command to wipe out The Ark and player profiles. Is there?

**Comment by klightspeed** [comment]
This was also requested in a round-about way by @arkfrancegaming - we can add a `--wipe` option to `stop` and restart, and/or add e.g. a `wipesave` command.

**Comment by spitfire1081** [comment]
Thank you for the answer.

**Comment by rob-bb** [comment]
You can also just delete all the files in the save directory to wipe a server.

**Comment by morggin** [comment]
cd ark/Shootergame/Saved/SavedArks && rm -rf *
