### ISSUE TITLE
auto save/backup

### ISSUE THREAD

**Issue by bumbblebee** [arkmanager/ark-server-tools#505]
not so much an issue probably me not being new to this and not knowing where the setting is but i cant seem to find information on auto saving/backup up in the configs. is this done in the back ground or am i just missing it some where.

**Comment by klightspeed** [comment]
The script does not currently automatically perform backups - this can be done using a cron job (assuming the default config and install path):
```
*/15 * * * * /usr/local/bin/arkmanager backup
```
