### ISSUE TITLE
Suggested Option: Only update Ark on Major Version Changes

### ISSUE THREAD

**Issue by radonn24** [arkmanager/ark-server-tools#511]
Hi guys,

Just chatting with my friend about this today. Ark has released 2 minor version updates in the span of only a few hours today. So, my server is set to check for Ark updates, and mod updates, every 2 hours. As a result, my server has booted players a few times today, to preform these updates, which is somewhat annoying to some of the players. Which, raises this question:

Is there any current way to configure this tool to ONLY update on _major_ version updates to Ark, rather than _every_ version update? Or, if this is not already implemented, is this something that could be added?

Thanks for your efforts on creating this tool. It has been a godsend for my admin-ing duties. Cheers guys!

**Comment by klightspeed** [comment]
This would have to use an external service (such as the ARK wiki) to keep track of what the latest version is, as Steam only provides a Build ID and not the version.

**Comment by Lihis** [comment]
http://ark.gamepedia.com/Web_API#version

I have been following http://arkdedicated.com/version. As what I have been keeping my eye on that the version number bumps up the minor version number on hotfixes too.

And at least couple months back the version number from time to time was not in sync; there was new release in steam but http://arkdedicated.com/version reported the previous version number. I'm not sure how it is these days. So might not be the most reliable solution to check if the update is major or not.

**Comment by radonn24** [comment]
@Lihis Thank you for sharing those links.

It looks like major versions are reported here: http://arkdedicated.com/version/major

Not sure how actively it's updated, so, I am not sure if that is a reliable means to this end.

**Comment by Lihis** [comment]
@radonn24 I have not paid attention to the major version so I do not know does it share the same behaviour as I wrote on last part of my previous message.
