### ISSUE TITLE
Idea - Delay for Update for Players

### ISSUE THREAD

**Issue by talpidae** [arkmanager/ark-server-tools#523]
Hi!

I have an idea for your awesome tool. 
Dont know if its possibile - maybe im dreaming too much. 

So, Im running crontabs to automate (Mod)Updates.  which is a very nice feature. But sometimes there ar updates in primetime, where raids are going on. My idea was, to give the normal players an command, to do an Update later. I thought about an chatcommend, which had to be used of X% of connected players to force the server to an cancelupdate and do it later a day. Maybe only 1 time useable for each update. 

What do you think about it? Would it be possibile?

**Comment by klightspeed** [comment]
This has now been added to 1.6-dev.unstable

This monitors the ServerGame log (which requires the `arkflag_servergamelog=true` option), and cancels the update if `/cancelupdate` has been said in the last 5 minutes.

**Comment by talpidae** [comment]
Dammed thats awesome!
Would it be possible to set how many players, or better to set how many percent of connected players has to do this command? Think there will be some trolls if one command is enought to cancel the update. And is it possibile to flag players who had used this command? For trolls again, if they try to move the update over half day. Or maybe if an update got canceled, and the next update cant if this is easier for you.

**Comment by arkfrancegaming** [comment]
Be carefull about using servergame log https://survivetheark.com/index.php?/forums/topic/8280-server-game-log-server-stability-note-for-server-admins/

**Comment by klightspeed** [comment]
Unfortunately the other option would be to use the RCON GetChat command, which fetches the chat log buffer.  However, it also clears the chat log buffer, and so would not work if another RCON client is monitoring chat.

Another option would be a mod that monitors chat.  However, I think this is beyond the scope of this project.

**Comment by talpidae** [comment]
For Arma 2 and 3, there are tools to monitor the Server within BattleEye, but i dont know, if this is possible in ARK and how far BattleEye is implemented to it. Give me some hours (or days :P), i will search for other ways to do this. I think this could be a very nice and helpful feature.
