### ISSUE TITLE
AMP implementation request

### ISSUE THREAD

**Issue by ryan1161** [arkmanager/ark-server-tools#580]
I was wondering if it would be possible to use my AMP website console manger with this tool. Maybe talk to the dev at that website to see if it's even possible. I have ask one of the devs if it would be.[](https://cubecoders.com/AMP)

**Comment by klightspeed** [comment]
I'm guessing you're talking about: https://cubecoders.com/AMP

**Comment by ryan1161** [comment]
Yes it's the one at https://cubecoders.com/AMP. I have it installed already running a minecraft server and have another key for ARK but was wondering if I could use it to mange your tool with it.

**Comment by klightspeed** [comment]
One could develop a C# application module to manage arkmanager with AMP.  The server would be `arkmanager run @instancename`.  Configuration could be passed through environment variables.

Alternatively, one could implement an application module in C# that does most of what arkmanager does.
