### ISSUE TITLE
Server won't restart after update using systemd timer

### ISSUE THREAD

**Issue by OnigamiSama** [arkmanager/ark-server-tools#583]
So I have 3 servers running right now and I have a systemd timer that trigger the update --warn for all three every hours. Look like this

```
#!/bin/bash
# Ark Update Script
/usr/local/bin/arkmanager update @all --warn
```

The update is indeed done well but the server doesn't restart after, if there's no update the server is still running normaly. I tried using the script to update only one server but the result is the same.

**Comment by klightspeed** [comment]
If you are running the servers using systemd, you probably want something more like:
```
#!/bin/bash

for instance in $(/usr/local/bin/arkmanager list-instances --brief); do
  isactive=
  if systemctl is-active "arkmanager@$instance" >/dev/null 2>&1; then
    isactive=yes
  fi
  /usr/local/bin/arkmanager update "@$instance" --warn --no-autostart
  if [ -n "$isactive" ]; then
    if ! systemctl is-active "arkmanager@$instance" >/dev/null 2>&1; then
      systemctl start "arkmanager@$instance"
    fi
  fi
done

```
