### ISSUE TITLE
help needed for multiple instances

### ISSUE THREAD

**Issue by boistordu** [arkmanager/ark-server-tools#598]
Hi,

I'm running ark within a container from docker and I would like some help to be able to run 2 or 3 instances. 
Can some take a little bit of time to explain to me how do we normally run several instances of ark with arkmanager? 
thanks

**Comment by TOXid** [comment]
Tell me please what the trouble?
I try to run 2 instances, but the second instances not loading properly (0/0 players and no map).
In this time i can see in htop next: 1 CPU core 100% Load and ~6.6-6.8/12G of RAM.
After few minutes the second instance fall.

Running command 'status' for instance 'TheCenter'
 Server running:   Yes
 Server listening:   Yes
Server Name: Server2  SE cluster transfer - (v247.6)
Players: 0 / 0
Active Players: 0
 Server online:   Yes
 ARKServers link:   http://arkservers.net/server/1.1.1.1:27015
 Server build ID:   1347876
 Server version:   245.99
Running command 'status' for instance 'ScorchedEarth'
 Server running:   Yes
 Server listening:   Yes
Server Name: Server 1  SE cluster transfer - (v247.6)
Players: 0 / 70
Active Players: 0
 Server online:   Yes
 ARKServers link:   http://arkservers.net/server/1.1.1.1:27020
 Server build ID:   1347876
 Server version:   245.99

**Comment by klightspeed** [comment]
@TOXid make sure the instances are not trying to use the same ports.  That 0/0 players often means that one of the ports (such as the RCON port) is currently in use.

**Comment by TOXid** [comment]
Yes it was same RCON port. Even rcon was disabled...

**Comment by boistordu** [comment]
well @TOXid how did you done your installation for the second instance please? since I'm using a docker version ark + arkmanager I will have to migrate your way to a compatible way for docker

**Comment by boistordu** [comment]
@TOXid ?
