### ISSUE TITLE
--warn throwing 'find' error due to incorrect directory

### ISSUE THREAD

**Issue by Log1x** [arkmanager/ark-server-tools#606]
When doing `arkmanager restart @scorched --warn` manually, it is throwing an error due to `find` using a hardcoded directory.

```
steam@dev:~/servers/arkonia_server/backup$ arkmanager restart @scorched --warn
Running command 'restart' for instance 'scorched'
<RichColor Color="1.00, 0.00, 0.00, 1">[Attention]</><RichColor Color="0.45, 0.63, 0.72, 1">Ark</>onia Scorched Earth will shutdown in <RichColor Color="0.45, 0.63, 0.72, 1">15</> minutes.\n\n<RichColor Color="0.45, 0.63, 0.72, 1">Reason</>\nRestarting
Command processed
There are 17 players connected
find: `/home/steam/ARK/server1/ShooterGame/Saved/Logs': No such file or directory
```

I do not use `/home/steam/ARK/server1/ShooterGame/Saved/Logs` in any config file.

It will reoccurringly throw this error when it's supposed to be doing the broadcast instead.

https://log1x.com/screenshots/2016-09-18_14-25-16_cOZW1.png here's a screenshot so you can see what I mean.

The issue appears to be on [line 1275](https://github.com/FezVrasta/ark-server-tools/blob/master/tools/arkmanager#L1275). Looks like you simply just forgot to change the absolute path to use the variable instead.

**Comment by klightspeed** [comment]
This was fixed in v1.6.01
