### ISSUE TITLE
A few issues possibly

### ISSUE THREAD

**Issue by hirsty** [arkmanager/ark-server-tools#607]
Hello all,

First of all sorry for lack of detail I'm currently typing this on my phone. First issue seems to be on some restarts the server refuses to listen, the second being is the escaped command line arguments normal? The third...my map seems to be having issues with mods,seems it's half loaded...engrave are there but existing placed items aren't.....mods not out of date, I update on start, no building changes, everything is there but the mod structures

**Comment by klightspeed** [comment]
I think this was an issue with the ARK Server itself - one of the recent updates to the ARK server broke a lot of mods.
