### ISSUE TITLE
Arkmanager Command Not Found

### ISSUE THREAD

**Issue by Brodude1234** [arkmanager/ark-server-tools#611]
When I try to run "arkmanager install", it comes back with "command arkmanager not found" on CentOS. I  am not sure where to go from here.

Any assistance is appreciated.

**Comment by klightspeed** [comment]
Sounds like `/usr/local/bin` is not in your `$PATH`.  Try either adding `/usr/local/bin` to your `$PATH`, or `/usr/local/bin/arkmanager install`.  Also ensure you are not running `arkmanager` as root.

**Comment by Brodude1234** [comment]
Thank you so much for your response. With your help, I was able to get the server installed. Unfortunately, however, I cannot connect and when I type "arkmanager status" in the server it says "Server listening = No."

**Comment by kdulep** [comment]
try to install as root as specified in guide
