### ISSUE TITLE
Possible fix for auto updating mods version detection

### ISSUE THREAD

**Issue by hirsty** [arkmanager/ark-server-tools#615]
Hey guys why not add steam webapi to arkmanager.cfg and then use  https://api.steampowered.com/ISteamRemoteStorage/GetPublishedFileDetails/v1/?key= to check for mod update timestamp changes?

**Comment by klightspeed** [comment]
Don't need the key for public mods.

Something like:
```
isModUpdateAvailable(){
    local modid="$1"
    local instmft="$(sed -n '/^\t"WorkshopItemsInstalled"$/,/^\t[}]$/{/^\t\t"'"${modid}"'"$/,/^\t\t[}]$/{s|^\t\t\t"manifest"\t\t"\(.*\)"$|\1|p}}' <"$steamcmdroot/steamapps/workshop/appworkshop_${mod_appid}.acf")"
    local remmft="$(curl -s -d "itemcount=1&publishedfileids[0]=${modid}" http://api.steampowered.com/ISteamRemoteStorage/GetPublishedFileDetails/v1 | sed -n 's|^[[:space:]]*"hcontent_file": "\(.*\)",|\1|p')"
    if [[ -n "${remmft}" && "${instmft}" != "${remmft}" ]]; then
        return 0 # true
    fi
    return 1 # false
}
```

**Comment by hirsty** [comment]
Want me PR and look?

**Comment by klightspeed** [comment]
This has been added, and will check if the mod manifest in the workshop directory matches that in Steam before trying to download it.

Unfortunately there is no easy way to determine if the mod in the workshop directory matches the mod in the ShooterGame/Content/Mods directory without comparing the modification times on the files, as the mod info file does not include any sort of manifest.

**Comment by klightspeed** [comment]
This is in v1.6.02
