### ISSUE TITLE
Backup Error

### ISSUE THREAD

**Issue by Dragost** [arkmanager/ark-server-tools#618]
On v1.6.01 backup get Error with "arktributetribe" files. Bad generated path.

‘/home/steam/ARK/ShooterGame/Saved//home/steam/ARK/ShooterGame/Saved/SavedArks/

> Copying ARK tribute tribe files
>    _.arktributetribe cp: cannot stat ‘/home/steam/ARK/ShooterGame/Saved//home/steam/ARK/ShooterGame/Saved/SavedArks/_.arktributetribe’: No such file or directory
> cp: cannot stat ‘/home/steam/ARK/ShooterGame/Saved//home/steam/ARK/ShooterGame/Saved/SavedArks/_.arktributetribe’: No such file or directory
> cp: cannot stat ‘/home/steam/ARK/ShooterGame/Saved//home/steam/ARK/ShooterGame/Saved/SavedArks/_.arktributetribe.tmptributetribe’: No such file or directory

**Comment by klightspeed** [comment]
This should be fixed in v1.6.02
