### ISSUE TITLE
Upgrade over v245.99

### ISSUE THREAD

**Issue by Dragost** [arkmanager/ark-server-tools#619]
Hi,
I try to update the server but its return:

> Current version:  1354299
> Available version:  1354299
> Your server is up to date!

But on https://steamcommunity.com/app/346110/discussions/0/594820656447032287/ , they say the newest version is v247.81.

Is it normal? How can I update server to Scorched Earth?
I do not want to change the map, only update. :(

Thanks in advance.

**Comment by klightspeed** [comment]
Wildcard Studios included a `version.txt` in their files from about v244.  However, they removed that file in v245.99, thus the `version` in the output of `arkmanager status` showing that version.

https://steamdb.info/app/376030/depots/?branch=public shows the latest build ID (the version in the update output above) being 1354299, last updated 4 days ago.

If the 247.81 update was released less than 4 days ago, it sounds like it might be another case of Wildcard forgetting to update the Linux server build.

**Comment by Dragost** [comment]
Oh, thank you so much @klightspeed ^^.

**Comment by klightspeed** [comment]
Actually, I just checked and `version.txt` is still in the files being distributed -- looks like Wildcard just stopped updating it with v245.99
