### ISSUE TITLE
Don't see a donation link fix please

### ISSUE THREAD

**Issue by Flukethoughts** [arkmanager/ark-server-tools#623]
Don't see a donation link on the github please fix

**Comment by Alphakilo** [comment]
Ping the new overlord, @klightspeed

**Comment by klightspeed** [comment]
Open Source Collective sponsor link added

**Comment by klightspeed** [comment]
Open Source Collective is updating their eligibility criteria to require at least two representatives, so the current donations method is probably going to close soon.
