### ISSUE TITLE
Rconcmd Issue

### ISSUE THREAD

**Issue by khanate3641** [arkmanager/ark-server-tools#625]
All commands issued with rconcmd produce the response "Empty response at -e line 12."

arkmanager rconcmd "broadcast Hello" @server1 is the syntax that I have been using.

Any ideas as to what could be causing this response?

**Comment by klightspeed** [comment]
Does the ServerAdminPassword in your config contain any special characters?  Is the ServerAdminPassword set?

**Comment by khanate3641** [comment]
The ServerAdminPassword is set for both servers. Neither one uses anything outside of A-Z, 0-9.

**Comment by klightspeed** [comment]
What is the output of `arkmanager --version`

**Comment by khanate3641** [comment]
Version: 1.6
Channel: master
Commit: 0a02cc2
Release Tag: v1.6.03
Blob SHA: 9a322896756f522a84997fe882bb8c0470cbedd2

**Comment by klightspeed** [comment]
Please try upgrading arkmanager to v1.6.04

**Comment by khanate3641** [comment]
That appears to have worked, Thanks!
