### ISSUE TITLE
[Guide]Something helpful to new comers of the server clustered world 

### ISSUE THREAD

**Issue by badboysgaming** [arkmanager/ark-server-tools#633]
As i started my journey of learning cluster servers i have experimented with several things
Here are few things that other may find helpful:(each setting i post must be placed in each cfg file to work properly

I Imagine that several people not liking the fact you have to use same server files to run all the servers because you not able to have certain settings per server.. well no need to worry since ark server tools has a configuration file for each server its easy thing in the world !
**PVP Settings**
Lets say you want PvP on one server but don't want Pvp on second server easy 
add this line to each configuration file (CFG) 
`ark_ServerPVE=TRUE`
or vice versa
`ark_ServerPVE=FALSE`

**XP Rate**
add this ling to cfg file
`ark_XPMultiplier=50`(or what ever rate you want )

**Taming**
`ark_TamingSpeedMultiplier=50`

**Harvesting**
`ark_HarvestAmountMultiplier=10`

these are just some of the examples you can add to cfg file thanks to hard work of the guys of this tool your able to do a lot more then you would expect

Special note to high rate servers 
if you run high rate server but deal with roll on harvesting that makes server extremely lag when someone is harvesting 
here is what you can do to stop lag and server over load 
edit each resource here is my resource code from game.ini
`HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemConsumable_Berry_Amarberry_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemConsumable_Seed_Amarberry_C",Multiplier=2.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_AnglerGel_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_ApexDrop_Argentavis_C",Multiplier=2.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemConsumable_Berry_Azulberry_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemConsumable_Seed_Azulberry_C",Multiplier=2.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_BlackPearl_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemConsumable_CactusSap_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_ChitinPaste_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_Charcoal_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_Chitin_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_ChitinOrKeratin_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemConsumable_Veggie_Citronal_C",Multiplier=2.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemConsumable_Seed_Citronal_C",Multiplier=2.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_Clay_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_Crystal_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_KeratinSpike_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_Electronics_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_Fibers_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_Flint_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_Gasoline_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_Gunpowder_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_Hide_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_Horn_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_Keratin_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_LeechBlood_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemConsumable_Veggie_Longrass_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemConsumable_Seed_Longrass_C",Multiplier=2.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_ApexDrop_Megalodon_C",Multiplier=2.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemConsumable_Berry_Mejoberry_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemConsumable_Seed_Mejoberry_C",Multiplier=2.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_Metal_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_MetalIngot_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemConsumable_Berry_Narcoberry_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemConsumable_Seed_Narcoberry_C",Multiplier=2.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_Obsidian_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_Oil_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_Polymer_Organic_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_Pelt_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemConsumable_Seed_DefensePlant_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemConsumable_Seed_PlantSpeciesY_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_Polymer_C",Multiplier=10.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_PreservingSalt_C",Multiplier=10.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_Propellant_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_RareFlower_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_RareMushroom_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemConsumable_RawMeat_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemConsumable_RawMeat_Fish_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemConsumable_RawPrimeMeat_Fish_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemConsumable_RawPrimeMeat_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_RawSalt_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemConsumable_Veggie_Rockarrot_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemConsumable_Seed_Rockarrot_C",Multiplier=2.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_Sand_C",Multiplier=10.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_Sap_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_ApexDrop_Sauro_C",Multiplier=2.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemConsumable_Veggie_Savoroot_C",Multiplier=2.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemConsumable_Seed_Savoroot_C",Multiplier=2.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_Silicon_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_Silk_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_Sparkpowder_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemConsumable_Berry_Stimberry_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemConsumable_Seed_Stimberry_C",Multiplier=2.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_Stone_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_Sulfur_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_ApexDrop_FireWyvern_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_ApexDrop_LightningWyvern_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_ApexDrop_PoisonWyvern_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_Thatch_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemConsumable_Berry_Tintoberry_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemConsumable_Seed_Tintoberry_C",Multiplier=2.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_ApexDrop_Rex_C",Multiplier=2.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_Wood_C",Multiplier=20.0)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemConsumable_WyvernMilk_C",Multiplier=15.0)
`
adding all resources to game.ini with each multiplier
then what you want to do is edit your  GameUserSettings.ini
`HarvestAmountMultiplier=15.000000`
my case since i run cluster `ark_HarvestAmountMultiplier=15`
this setting on my 999x server gives you 300x resources per swing with dino or pick up which is more then enough on any server. mantis i can farm about 200k metal in 5 minutes

I hope so find these setting helpful

**Comment by KGM6911** [comment]
Hey, thanks for the post.  Do you know if the HarvestResourceItemAmountClassMultipliers all have to be on one line?  Or can they be on multiple lines to make it easier to read?  I know lots of the other multiplier overrides have to be on one line.   I look on http://ark.gamepedia.com/Server_Configuration and they mention it for most of the other types but not the harvest one.    Here's what they write for many of them:

The examples provided here are split into multiple lines for space considerations. In the configuration file, an entry must be placed on a single line.

**Comment by KGM6911** [comment]
Ahh, disregard, just found it says: Additional lines can be added with other resource types, such as Wood, Stone etc.
