### ISSUE TITLE
staging and updating mods

### ISSUE THREAD

**Issue by Flukethoughts** [arkmanager/ark-server-tools#640]
is there a way I can set a separate staging directory for each server. Because the cron job of updating ever 30 mins just ends up looping over itself and causing issues. To where I wake up and the servers haven't been up for like 5 hours because the task never completed correctly.

**Comment by klightspeed** [comment]
Put the `arkStagingDir` into your instance config.  However, be aware that in this case each instance will take up the full 5.5GB of disk space, and deduplication of files between instances will not occur.

**Comment by Flukethoughts** [comment]
with all of the servers being the same besides the maps is their any setting you could incorporate to make it download and then copy to all the servers in one update or does it have to download for each 6 servers independently each time

**Comment by klightspeed** [comment]
One possibility is:
* have an instance that has all of the mods but never runs
* Execute `arkmanager update @instance --update-mods --downloadonly` where `instance` is the above all-mods instance
* After that has finished, for each of the instances execute (possibly in parallel) `arkmanager update @instance --update-mods --no-download --warn`

e.g.
```
#!/bin/bash

/usr/local/bin/arkmanager update @allmods --update-mods --downloadonly
for instance in $(/usr/local/bin/arkmanager list-instances --brief); do
    if [ "$instance" != "allmods" ]; then
        /usr/local/bin/arkmanager update "@$instance" --update-mods --no-download --warn >>"${HOME}/update-${instance}.log" 2>&1 &
    fi
done

wait
```

**Comment by Flukethoughts** [comment]
okay thank you
