### ISSUE TITLE
Server name?!

### ISSUE THREAD

**Issue by thamathar** [arkmanager/ark-server-tools#642]
Hey guys, don't know what is wrong here, but even on the main.cfg the ark_SessionName="Name of server" but on the list I still get "Ark Server Tool"!? Why its this happening ?!

Thanks in advance

**Comment by klightspeed** [comment]
If you have performed a user-install, then `$HOME/.config/arkmanager/instances/main.cfg` will exist.  Remove this if you don't want it.

**Comment by thamathar** [comment]
Thanks will do that :D since I only want 1 config file for this

One last questions on the arkmanager.cfg I can setup every ark server options there with the start of ark_ right ?!

Thanks in advance

**Comment by klightspeed** [comment]
Yes, every option that can be specified in the instance config can also be specified in `arkmanager.cfg`
