### ISSUE TITLE
SERVER REQUEST

### ISSUE THREAD

**Issue by Flukethoughts** [arkmanager/ark-server-tools#643]
I was wondering if you would work on this
 Your session name may not contain special characters (eg. !![EU]!! Aw&some ARK) 
I would like to try to symlink my settings to make it easier to update them all at once. 
Please let me know if this would be possible.
For instance currently my servers are named moddedark.com then the map

**Comment by klightspeed** [comment]
You can put common settings into `arkmanager.cfg`

You can also put special characters into the name just as long as you know how to escape them for the shell.  e.g. most characters except `'` can go between `'` characters - e.g.
```
ark_ServerName='!![EU]!! Aw&some ARK'
```

To put a `'` in that, use `'\''`
```
ark_ServerName='John'\''s ARK'
```
