### ISSUE TITLE
Problems Restarting Server

### ISSUE THREAD

**Issue by Gumballz** [arkmanager/ark-server-tools#644]
I seem to be experiencing problems with 1 server.

After the server has stopped running (whether through update,restart or stop) and I attempt to restart, Arkmanager reports an update is in progress and the start is aborted.

All other servers start and stop just fine, just this one causing me headaches.  Any clues please ?

And no, there isn't any update in progress

**Comment by klightspeed** [comment]
The message should tell you the PID of the update process.  Check using `ps` what process has that PID.

If the process running under that PID is not arkmanager, then remove the `.ark-update.lock` file in your ARK server root.
