### ISSUE TITLE
Selecting download server for update checks?

### ISSUE THREAD

**Issue by Rob-bb** [arkmanager/ark-server-tools#648]
Hi

Recently I have been having problems with the update taking too long, and getting lots of this:

```
 Mod 661564024 not fully downloaded - retrying
 Downloading mod 661564024 ...
 Mod 661564024 not fully downloaded - retrying
 Downloading mod 661564024 ... |
```

Is there a way to select the download source for steamcmd?

**Comment by klightspeed** [comment]
As far as I know, the only way to influence where Steam downloads from is through the Region setting.  I don't know what convar or command is used to set this region setting.

**Comment by rob-bb** [comment]
I didn't have much luck with google either, the prevailing wisdom is it can't be done.
