### ISSUE TITLE
steamlogin

### ISSUE THREAD

**Issue by Flukethoughts** [arkmanager/ark-server-tools#649]
# config SteamCMD

steamcmdroot="/home/steam/steamcmd"                                 # path of your steamcmd instance
steamcmdexec="steamcmd.sh"                                          # name of steamcmd executable
steamcmd_user="steam"                                               # name of the system user who own steamcmd folder
steamcmd_appinfocache="/home/steam/Steam/appcache/appinfo.vdf"      # cache of the appinfo command
# steamlogin="anonymous"

looking into the page couldn't find anything on making it work with a login

**Comment by klightspeed** [comment]
You need to run `steamcmd` manually and execute the `login <username>` command before you can use the `steamlogin` setting in arkmanager.

This is only useful if you have private mods in the Steam workshop.
