### ISSUE TITLE
Automessage with crontab

### ISSUE THREAD

**Issue by ReaperBe7062** [arkmanager/ark-server-tools#650]
Hello,

i'm usign this amazign script for ark servers, but i need help i want to make automessages on my server and make a Countdown when my dedicated server gonna reboot every day a 4AM so like 

Automessage : This server reboot at 4AM everyday
then the shutdown of the server : arkmanager --warn --saveworld
after this my dedicated serveur gonna reboot with a crontab

when a make a crontab with arkmanager install-cronjob --minute=5 broadcast "This server reboot at 4AM everyday" but doenst work and make crash my server 

please help me 

thanks

**Comment by hirsty** [comment]
Try it without the cronjob first see if it works - i can see you havent specified a server

**Comment by ReaperBe7062** [comment]
Hello i want to try to set a automessage every day a 4am but my serveur doenst want to send this message 

here my crontab commande : 2 4 * * * /usr/local/bin/arkmanager broadcast "server reboot in 15 min"

but don't work :( 

but 

*/30 * * * * /usr/local/bin/arkmanager broadcast "Test"

is working

**Comment by klightspeed** [comment]
Check the timezone on your server.  Most cron daemons will run the commands in the timezone that was set in /etc/localtime or in /etc/default/cron when the cron daemon was started.  If not set, this will default to UTC.
