### ISSUE TITLE
Auto Update CronJob Restart Server

### ISSUE THREAD

**Issue by JonathanWoodell** [arkmanager/ark-server-tools#651]
I created a cronjob to update the server and it mods. I currently have two server running in a cluster and the problem I am having is that when the update happens only 1 server restarts its self the other I have to manually restart.

30 \* \* \* \* /usr/local/bin/arkmanager --cronjob update @all  --saveworld --backup --warn --update-mods --args

**Comment by tobi-wankenobi** [comment]
Same problem here. Two server in a cluster und only the first restarts after the update. i use the last version of arkmanager.

**Comment by eailes** [comment]
I thought the same was happening as well, however it appears it only processes one instance at a time.

For example:
30 * * * * /usr/local/bin/arkmanager --cronjob update @all --saveworld --backup --warn --update-mods --
@firstInstance
-updates download into staging dir
-arkmanager checks for players
--if players warn else restart immediate <--- this is where is gets complicated(kinda)
@secondInstance
-updates download into staging dir
-arkmanager checks for players
--if players warn else restart immediate

When players are connected the second instance has to wait the 15 mins to begin. So when the first server restarts, you might think the second one should restart at the same time. That does not happen. After the first 15min the @secondInstance begins and if players are connected warns for another 15mins. 30 Minutes later you should have the second instance restarted.

This has been my experience. I have not had the update fail yet.

btw I check every 60min, and my warn timer is 15min. My two instances are clustered in the same directory.

Hope this helps. I am not a contributor here, just a user.

**Comment by dahlskebank** [comment]
_Moving my comment to this thread, seeing as you guys have the same problem I have._

> One a sidenote for crontab, multi-instance and auto-update, the following is not working for me.
> `00 */2 * * * /home/ark/bin/arkmanager update --safe --warn --saveworld --update-mods @all`
> 
> Perhaps someone can fill me in here, but when that is run either via crontab or just command line, it doesn't stop both servers. It will start with the first server and if there is an update, it will countdown 15 minutes warning the players, saveworld, stop server, update, start server.
> 
> And then it starts to check for update for the second server. But these files have already been updated by the first server, so it won't update. Leaving the second server without getting updated... Even though the files are updated, the server isn't restarted so that the version number updates.
> 
> Am I doing this wrong? Is there some other way? I'd prefer to keep checking for updates automatically as often as possible, so that I can stop playing ARK and let the server run it's course. I run a nightly stop and saveworld of both servers so that I can get an offsite backup, so the second server will eventually be updated... still, I'd prefer it to auto-update every 2 hours like the other server.

**Comment by eailes** [comment]
Are your servers clustered and served from the same directory? It sounds like they might be. I was running that setup, and was experiencing the same update delays you described, however, I did not have the fail to update on the second instance.

What I did to resolve all my issues and provide a streamlined update was seperate all the instances into individual ark installs. Perform a download only update on the allmods instance. This downloads all mods to the steamcmd directory and places the game update into the staging directory. Then after that every instance except the all mods does a update with no download defined. They all run simultaneously. This was suggested in another issues post.

for all instances
`
arkopt_clusterid="yourcluster"
arkopt_ClusterDirOverride=/home/steam/yourcluster
arkStagingDir="/home/steam/Staging"
`


*/60 * * * * /home/steam/arkScripts/./update.sh >> /dev/null 2>&1
`
#!/bin/bash

/usr/local/bin/arkmanager update @allmods --update-mods --downloadonly
for instance in $(/usr/local/bin/arkmanager list-instances --brief); do
    if [ "$instance" != "allmods" ]; then
        /usr/local/bin/arkmanager update "@$instance" --update-mods --no-download --warn >>"${HOME}/update-${instance}.log" 2>&1 &
    fi
done

wait
`

Now I have noticed if your actual machine reboots, it will attempt to restart all instances even @allmods. So you may want to disable the service that does that.

**Comment by caindrac** [comment]
Is there anyone solution to this problem if we don't want to split the instances into different installations?

**Comment by Fendelgast** [comment]
Not ideal to have multiple instances of the install. What about an arkversion per instance, or a flag to restart all instances if any update is found ?
