### ISSUE TITLE
Bug with Servers logs

### ISSUE THREAD

**Issue by ReaperBe7062** [arkmanager/ark-server-tools#652]
Hello 
on my server i dont have logs form the chat or others logs 

and i have a message : find: "/ShooterGame/Saved/Logs": No file or fileof this type

who have a solution ? 

thanks

**Comment by klightspeed** [comment]
This should be fixed by commit 385a909 in v1.6.08

**Comment by ReaperBe7062** [comment]
Yeah Nice i need it
