### ISSUE TITLE
Server Settings being over written

### ISSUE THREAD

**Issue by mmitchell57** [arkmanager/ark-server-tools#656]
I have managed to get Ark Manager working on my Linux server. I was able to run all mod updates without issues. The server starts up fine and I can connect with my game. I do see mods are applied to the instance. However, the server configs don't seems to taking hold. Mainly the server name and player count, admin pass, and server pass. I've looked at the ArkManager.config, main.cfg, and gameusersettings.ini and set stuff in all of them. After restarting the GameUserSettings.ini reverts all those settings back and the time stamp is updated on the file. The main.cfg isn't changed and the ArkManager isn't either. Seems odd. Below are the main.cfg. Let me know if you need anything else. 

Main.cfg: 
-----------------------------------------------------------------------
# config environment
arkserverroot="/home/steam/ARK"                                     # path of your ARK server files (default ~/ARK)

# ARK server options - use ark_<optionname>=<value>
# comment out these values if you want to define them
# inside your GameUserSettings.ini file
serverMap="TheIsland"                                               # server map (default TheIsland)
#serverMapModId="469987622"                                         # Uncomment this to specify the Map Mod Id (<fileid> in http://steamcommunity.com/sharedfiles/filedetails/?id=<fileid>)
#ark_TotalConversionMod="496735411"                                 # Uncomment this to specify a total-conversion mod
#ark_RCONEnabled="True"                                              # Enable RCON Protocol
ark_RCONPort="27020"                                                # RCON Port
ark_SessionName="Swampy Island"  # if your session name needs special characters please use the .ini instead
ark_Port="7777"                                                     # ARK server port (default 7778)
ark_QueryPort="27015"                                               # ARK query port (default 27015)
ark_ServerPassword="xxxxxxxx"                        # ARK server password, empty: no password required to login
ark_ServerAdminPassword="xxxxxxxx"                               # ARK server admin password, KEEP IT SAFE!
ark_MaxPlayers="24"
ark_ServerPVE=True
ark_GameModIds="479295136,503911420,538827119,542244370,558079412,569786012,572277026,592595740,609380111,631241063,679500536,680481868,725398419,731604991,749466101,758608778,764755314,760884349"     #
# Uncomment to specify additional mods by Mod Id separated by commas
ark_AltSaveDirectoryName="TheIsland"                # Uncomment to specify a different save directory name

# ARK server flags - use arkflag_<optionname>=true
#arkflag_OnlyAdminRejoinAsSpectator=true     #Uncomment to only allow admins to rejoin as spectator
#arkflag_DisableDeathSpectator=true        #Uncomment to disable players from becoming spectators when they die

# ARK server options - i.e. for -optname=val, use arkopt_optname=val
#arkopt_StructureDestructionTag=DestroySwampSnowStructures

**Comment by klightspeed** [comment]
Wildcard's ARK server will overwrite GameUserSettings.ini with default settings if it contains any options it doesn't understand or if it contains any invalid characters.  It will also write any settings presented on its command-line (as set in arkmanager's config) to the GameUserSettings.ini

**Comment by mmitchell57** [comment]
Ok, i'm giving everything a once over again after taking a break. Lets see what happens. :)

**Comment by mmitchell57** [comment]
Ok, i went through all the files and double checked. All the configs look good. I went in and muffed up the gameusersettings.ini just to see what it would do. Upon a bootup it replaced the file with an entirely new one with all the default configs. If I go in and only update the servername and player count, it gets reset back to the default. I've attached the files if that helps. I'm lost at this point. 
[Main.txt](https://github.com/FezVrasta/ark-server-tools/files/570328/Main.txt)
[GameUserSettings.txt](https://github.com/FezVrasta/ark-server-tools/files/570329/GameUserSettings.txt)
[arkmanager.txt](https://github.com/FezVrasta/ark-server-tools/files/570330/arkmanager.txt)

**Comment by mmitchell57** [comment]
Here's some of the logs... Looks like it never registers the settings i've put in. 

[2016.11.03-20.40.48:402][  0]Log file open, 11/03/16 16:40:48
[2016.11.03-20.40.48:403][  0]ARK Version: 249.2
[2016.11.03-20.41.44:288][  0]Primal Game Data Took 55.45 seconds
[2016.11.03-20.42.55:601][  0]Server: "ARK Server Tools" has successfully started!
[2016.11.03-20.43.02:004][  0]Commandline:  "TheIsland?RCONEnabled=True?RCONPort=32330?SessionName=ARK Server Tools?Port=7777?QueryPort=27015?ServerPassword?ServerAdminPassword=keyboardcat?MaxPlayers=70?listen"
[2016.11.03-20.43.02:004][  0]Full Startup: 136.84 seconds (BP compile: 0.00 seconds)
[2016.11.03-20.43.02:004][  0]Number of cores 4

**Comment by klightspeed** [comment]
It sounds like you have performed both a system-install (i.e. `netinstall steam`) and a user-install (i.e. `netinstall --me`).  Since you are wanting to use the settings in `/etc/arkmanager/instances/main.cfg`, please remove `~/.config/arkmanager/instances/main.cfg`

**Comment by mmitchell57** [comment]
Ok, i do recall doing both installs now that you say it.  To prove how much of a linux newb I am, how do I view the .config/arkmanager/instances/main.cfg? I'm on centos 7.  I'm learning, but it takes me a bit sometimes.

**Comment by klightspeed** [comment]
```
cat /home/stusr/.config/arkmanager/instances/main.cfg
```

**Comment by mmitchell57** [comment]
Well looky there, by running that command i see the configs that would match what's happening on reboot. Let me clean that up. Just need to del the main.cfg?

**Comment by klightspeed** [comment]
Yes, delete that unwanted `main.cfg`

**Comment by mmitchell57** [comment]
As a follow up, i ended up screwing it up really bad, so I just re-installed the OS and then arkmanager.  After doing that, it all works great. Very smooth and very nice tool set. Thank you for your work. :)
