### ISSUE TITLE
Mod 111111111

### ISSUE THREAD

**Issue by rgutz** [arkmanager/ark-server-tools#657]
Sometimes installing a mod creates a "111111111" folder in Content/Mods
This breaks all future updates, because no mod with this id exists.  I've tried deleting this folder, but it breaks things.

I got updates working again by hacking your script, and adding an exclusion for this 'mod id'
I suggest the following change to the arkmanager script:

#
# Get the Mod IDs of the installed mods and the requested mods
#
getModIds(){
  (
    echo "${serverMapModId}"
    echo "${ark_TotalConversionMod}"
    echo "${ark_GameModIds}" | tr ',' '\n'
    find "${arkserverroot}/ShooterGame/Content/Mods" -maxdepth 1 -type d -printf "%P\n"
  ) | sort | uniq | grep '^[1-9][0-9]*$' | grep --invert-match '^111111111$'
}

**Comment by Gumballz** [comment]
Mod 111111111 is Primitive+ TC DLC
