### ISSUE TITLE
?OverrideOfficialDifficulty=5.0 issue

### ISSUE THREAD

**Issue by Tylaris** [arkmanager/ark-server-tools#658]
The newish option to override the difficulty setting (?OverrideOfficialDifficulty=5.0) has had us perplexed.  What's the syntax and where does it go?

We've tried it several different ways with no effect.

**Comment by Flukethoughts** [comment]
it works well for me this is the steps you need to do
1. go to the instance or the config of the arkmanager
2. the setting you want to place is ark_OverrideOfficialDifficulty=40.0 where 40 is the difficulty you want to use.
3. Next thing to do is to make sure you destroy all wild dinos and boom your good that's it.

**Comment by CaspyBXL** [comment]
@Flukethoughts 
Dear god you are the best ever, i did not even notice you can put this option like this in arkmanager.
Now i can use this on my multiple servers so i have the same lvl no matter what changes on ark !

Is this still correct for the island and the center ?
4.0 = 120 LVL WILD
5.0 = 150 LVL WILD
6.0 = 180 LVL WILD
