### ISSUE TITLE
--warn Countdown

### ISSUE THREAD

**Issue by Gumballz** [arkmanager/ark-server-tools#668]
Minor issue..

I have my warn interval at 15 minutes.  Previously it would do 15 min, 10 min, 5 min, 4min , 3min, 120 seconds.. and so on.

Now it does ..
15 mins
14 mins
9 mins
4 mins
3 mins
2 mins
120 seconds
90 and so on..

A minor issue

**Comment by TehMino** [comment]
Same issue here, i have the same weird countdown.
