### ISSUE TITLE
AppManifest Missing

### ISSUE THREAD

**Issue by mmitchell57** [arkmanager/ark-server-tools#680]
The auto update feature is not working for me now. The honest answer is that appmanifest is missing. I accidently deleted it thinking I was doing something else. How do I recreate? Any help is appreciated. I need to retain my world settings and backups. I do run world backups and saves.

**Comment by mmitchell57** [comment]
I uploaded the one from my client system and renamed it to match. Same game just server vs. client. I hope this works.

**Comment by klightspeed** [comment]
If you are using a staging directory, you can copy the `appmanifest_376030.acf` from there.

If not, the safest way would be to perform a `arkmanager update --validate`, which should re-create the appmanifest.
