### ISSUE TITLE
update @all or not?

### ISSUE THREAD

**Issue by Rob-bb** [arkmanager/ark-server-tools#683]
Hi what is better to do, call update with @all or do one server at a time?  Would there be any performance benefits to one way over the other?

**Comment by klightspeed** [comment]
At the moment, the `@all` will perform the command for each server in turn.

**Comment by rob-bb** [comment]
Even though they share the same mods (for cluster) will it download them twice?

**Comment by klightspeed** [comment]
arkmanager should only download the mods and server update once unless they are updated between two instances updating.

If you want to ensure that the mods and server update are downloaded once, then you could update one server instance normally, then update the rest of the server instances that use the same staging directory and same mods, adding the `--no-download` option to the `update` command.
