### ISSUE TITLE
Error when startup

### ISSUE THREAD

**Issue by peterkristel** [arkmanager/ark-server-tools#686]
Success! App '376030' fully installed.
root@csgoluckywinner:/home/steam# arkmanager run
Running command 'run' for instance 'main'
[  WARN  ]      Your ARK server exec could not be found.
/usr/local/bin/arkmanager: line 788: cd: /home/steam/ARK//home/steamcmd/server/ShooterGame/Binaries: No such file or directory
2016-12-11 13:16:35: start
2016-12-11 13:16:35: Running /home/steam/ARK//home/steamcmd/server/ShooterGame/Binaries/Linux TheIsland\?RCONEnabled=True\?RCONPort=32330\?SessionName=ARK\ Server\ Tools\?Port=7777\?QueryPort=27015\?ServerPassword\?ServerAdminPassword=keyboardcat\?MaxPlayers=70\?listen
/usr/local/bin/arkmanager: line 954: /home/steam/ARK//home/steamcmd/server/ShooterGame/Binaries/Linux: No such file or directory
2016-12-11 13:16:35: Server PID: 5854
2016-12-11 13:16:40: Bad PID ''; expected '5854'
2016-12-11 13:16:40: exited with status 0
root@csgoluckywinner:/home/steam#

**Comment by peterkristel** [comment]
arkstChannel="master"                                               # change it to a different branch to get non-stable versions
install_bindir="/usr/local/bin"
install_libexecdir="/usr/local/libexec/arkmanager"
install_datadir="/usr/local/share/arkmanager"

# config SteamCMD
steamcmdroot="/home/steam"                                 # path of your steamcmd instance
steamcmdexec="steamcmd.sh"                                          # name of steamcmd executable
steamcmd_user="steam"                                               # name of the system user who own steamcmd folder
steamcmd_appinfocache="/home/steam/Steam/appcache/appinfo.vdf"      # cache of the appinfo command
steamcmd_workshoplog="/home/steam/Steam/logs/workshop_log.txt"      # Steam workshop log
#steamlogin="anonymous"                                             # Uncomment this to specify steam login instead of using anonymous login

# config environment
arkserverexec="/home/steamcmd/server/ShooterGame/Binaries/Linux"        # name of ARK server executable
arkbackupdir="/home/steamcmd/ARK-Backups"                              # path to backup directory
arkwarnminutes="60"                                                 # number of minutes to warn players when using update --warn
arkautorestartfile="ShooterGame/Saved/.autorestart"                 # path to autorestart file
arkAutoUpdateOnStart="false"                                        # set this to true if you want to always update before startup
arkBackupPreUpdate="false"                                          # set this to true if you want to perform a backup before updating
#arkStagingDir="/home/steamcmd/ARK-Staging"                            # Uncomment to enable updates to be fully downloaded before restarting the server (reduces downtime while updating)

**Comment by Mysterius** [comment]
"/home/steam/ARK//home/steamcmd/server/ShooterGame/Binaries: No such file or directory"

This is obvious. There's a double slash before "home" in the path.
Try this : arkserverexec="home/steamcmd/server/ShooterGame/Binaries/Linux" # name of ARK server executable

**Comment by klightspeed** [comment]
`arkserverexec` should be the relative path of the executable within the ARK server directory - i.e. `ShooterGame/Binaries/Linux/ShooterGameServer`

**Comment by peterkristel** [comment]
arkmanager run
Running command 'run' for instance 'main'
[  WARN  ]      Your ARK server exec could not be found.
/usr/local/bin/arkmanager: line 788: cd: /home/steam/ARK/home/steamcmd/server/ShooterGame/Binaries: No such file or directory
2016-12-11 13:21:59: start
2016-12-11 13:21:59: Running /home/steam/ARK/home/steamcmd/server/ShooterGame/Binaries/Linux TheIsland\?RCONEnabled=True\?RCONPort=32330\?SessionName=ARK\ Server\ Tools\?Port=7777\?QueryPort=27015\?ServerPassword\?ServerAdminPassword=keyboardcat\?MaxPlayers=70\?listen
/usr/local/bin/arkmanager: line 954: /home/steam/ARK/home/steamcmd/server/ShooterGame/Binaries/Linux: No such file or directory
2016-12-11 13:21:59: Server PID: 5955
2016-12-11 13:22:04: Bad PID ''; expected '5955'
2016-12-11 13:22:04: exited with status 0
root@csgoluckywinner:/home/steam#

**Comment by Mysterius** [comment]
Disregard my answer, I didn't read slowly enough. The boss nailed it.

**Comment by peterkristel** [comment]
Now i have this:

**Comment by peterkristel** [comment]
arkmanager run
Running command 'run' for instance 'main'
[  WARN  ]      Your ARK server exec could not be found.
/usr/local/bin/arkmanager: line 788: cd: /home/steam/ARK/home/steamcmd/server/ShooterGame/Binaries/Linux: No such file or directory
2016-12-11 13:22:55: start
2016-12-11 13:22:55: Running /home/steam/ARK/home/steamcmd/server/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?RCONEnabled=True\?RCONPort=32330\?SessionName=ARK\ Server\ Tools\?Port=7777\?QueryPort=27015\?ServerPassword\?ServerAdminPassword=keyboardcat\?MaxPlayers=70\?listen
/usr/local/bin/arkmanager: line 954: /home/steam/ARK/home/steamcmd/server/ShooterGame/Binaries/Linux/ShooterGameServer: No such file or directory
2016-12-11 13:22:55: Server PID: 6037
2016-12-11 13:23:00: Bad PID ''; expected '6037'
2016-12-11 13:23:00: exited with status 0
root@csgoluckywinner:/home/steam#

**Comment by klightspeed** [comment]
```
arkserverroot=/home/steam/ARK
arkserverexec=ShooterGame/Binaries/Linux/ShooterGameServer
```

**Comment by peterkristel** [comment]
In this file is the server: /home/steamcmd/server/ShooterGame/Binaries/Linux

**Comment by peterkristel** [comment]
And this i have:

# config environment
arkserverexec="arkserverexec=ShooterGame/Binaries/Linux/ShooterGameServer"        # name of ARK server executable
arkbackupdir="/home/steamcmd/ARK-Backups"                              # path to backup directory
arkwarnminutes="60"                                                 # number of minutes to warn players when using update --warn
arkautorestartfile="ShooterGame/Saved/.autorestart"                 # path to autorestart file
arkAutoUpdateOnStart="false"                                        # set this to true if you want to always update before startup
arkBackupPreUpdate="false"                                          # set this to true if you want to perform a backup before updating
#arkStagingDir="/home/steamcmd/ARK-Staging"                            # Uncomment to enable updates to be fully downloaded before restarting the server (reduces downtime while updating)

**Comment by klightspeed** [comment]
Where is `arkserverroot`?

**Comment by peterkristel** [comment]
Idk

**Comment by peterkristel** [comment]
But i fixed 👍 
arkserverexec="arkserverexec=ShooterGame/Binaries/Linux/ShooterGameServer" # name of ARK server executable

"!!!!arkserverexec!!!!!=ShooterGame/Binaries/Linux/ShooterGameServer" # name of ARK server executable

**Comment by peterkristel** [comment]
root@csgoluckywinner:/home/steam# arkmanager run
Running command 'run' for instance 'main'
2016-12-11 13:26:53: start
2016-12-11 13:26:53: Running /home/steam/ARK/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?RCONEnabled=True\?RCONPort=32330\?SessionName=ARK\ Server\ Tools\?Port=7777\?QueryPort=27015\?ServerPassword\?ServerAdminPassword=keyboardcat\?MaxPlayers=70\?listen
2016-12-11 13:26:53: Server PID: 6210
Using binned.
4.5.1-0+UE4 7038 3077 402 6
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110

**Comment by Mysterius** [comment]
Means it's working. You're good to go.

**Comment by peterkristel** [comment]
When i tried to join there is not responding

**Comment by peterkristel** [comment]
Wait i gonna try to reboot everything :D

**Comment by peterkristel** [comment]
aroot@csgoluckywinner:~# arkmanager start
Running command 'start' for instance 'main'
/usr/local/bin/arkmanager: line 1048: getServerPid: command not found
The server is starting...
The server is now running, and should be up within 10 minutes

**Comment by peterkristel** [comment]
Server running:   Yes
 Server listening:   No

**Comment by Mysterius** [comment]
The listening bit can take 2 minutes to appear.

What's in your log file ? (/home/steam/ARK/ShooterGame/Saved/Logs)

**Comment by peterkristel** [comment]
[2016.12.11-12.26.56:164][  0]Log file open, 12/11/16 13:26:56
[2016.12.11-12.26.56:164][  0]ARK Version: 252.9
[2016.12.11-12.26.56:164][  0]PID: [PID]

**Comment by peterkristel** [comment]
and on steam < not responding >

**Comment by klightspeed** [comment]
The instance config should be in `/etc/arkmanager/instances/main.cfg` - this will contain settings such as the session name, port, etc.

If you have forced a user-install by specifying `--perform-user-install`:
```
A user-install will create ~/.config/arkmanager/instances/main.cfg
This config file will override /etc/arkmanager/instances/main.cfg
```

Also make sure nothing else is listening on the ports on which the ARK server listens as configured in your instance config (7778, 22015 and 32330)

**Comment by Mysterius** [comment]
Also, what's the ip of your server?

**Comment by peterkristel** [comment]
root@csgoluckywinner:/etc/arkmanager/instances# ls
instance.cfg.example  main.cfg

**Comment by peterkristel** [comment]
159.253.1.119

**Comment by klightspeed** [comment]
What is the output of `netstat -antup | grep 'ShooterGame'`

**Comment by peterkristel** [comment]
udp    17664      0 0.0.0.0:27015           0.0.0.0:*                           2156/ShooterGameSer

**Comment by peterkristel** [comment]
root@csgoluckywinner:/etc/arkmanager/instances# netstat -antup | grep ':\(7778\|32330\) '
root@csgoluckywinner:/etc/arkmanager/instances#

**Comment by klightspeed** [comment]
Good, so nothing else is listening on those ports.  It can take a while to start if you have slow storage or less than 4GB of RAM available.

**Comment by peterkristel** [comment]
Ok.

**Comment by Mysterius** [comment]
Are you sure your ports are opened in your firewall configuration?

**Comment by peterkristel** [comment]
Yes

**Comment by klightspeed** [comment]
If you run `top`, and sort by memory (`x < < <`), how much memory is `ShooterGameServer` taking, and what is your `KiB Mem` line?

**Comment by peterkristel** [comment]
2156 steam     20   0 2920964 851468   8068 D  8.0 83.3   0:51.53 ShooterGameServ
 2138 steam     20   0   14956   4292   2320 S  0.7  0.4   0:00.80 arkmanager
 3184 root      20   0   25720   2916   2436 R  0.3  0.3   0:00.03 top

**Comment by klightspeed** [comment]
Wait, 2.9G virt size and 800MB resident?  Do you only have 1GB of RAM?

**Comment by peterkristel** [comment]
On this yes but i replace to my dedicated [32 GB] xd

**Comment by klightspeed** [comment]
I hope you have at least 4GB of swap on a fast disk.

**Comment by peterkristel** [comment]
Dedicated Server - E3-1240V2 / 32GB DDR3 / 240GB SSD

**Comment by peterkristel** [comment]
Error! App '376030' state is 0x202 after update job.
applicationmanager.cpp (1106) : Assertion Failed: Failed to write app state file /home/steam/ARK/steamapps/appmanifest_376030.acf
applicationmanager.cpp (861) : Assertion Failed: m_bStateChangesSavedToDisk
Redirecting stderr to '/home/server/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...Created shared memory when not owner SteamController_Shared_mem
OK.
"@NoPromptForPassword" = "1"

**Comment by peterkristel** [comment]
klightspeed help plzz https://join.me/757-016-360

**Comment by klightspeed** [comment]
Do you have sufficient disk space?  Also make sure you are running everything under your `steam` user.

**Comment by peterkristel** [comment]
can you join ?

**Comment by peterkristel** [comment]
Is this automatic enabling the mods at the players?

**Comment by peterkristel** [comment]
root@server1:~# arkmanager restart
Running command 'restart' for instance 'main'
The server has been stopped
/usr/local/bin/arkmanager: line 268: /var/log/arktools/arkmanager.log: Permission denied
/usr/local/bin/arkmanager: line 2907: /var/log/arktools/arkmanager.log: Permission denied
/usr/local/bin/arkmanager: line 2981: /var/log/arktools/arkmanager.log: Permission denied
/usr/local/bin/arkmanager: line 1048: getServerPid: command not found
The server is now running, and should be up within 10 minutes
/usr/local/bin/arkmanager: line 268: /var/log/arktools/arkmanager.log: Permission denied

**Comment by peterkristel** [comment]
Is this automatic enabling the mods at the players?

**Comment by Mysterius** [comment]
> /usr/local/bin/arkmanager: line 268: /var/log/arktools/arkmanager.log: Permission denied

The user you're running arkmanager with doesn't have write permission in /usr/local/bin/arkmanager

As for 

> /usr/local/bin/arkmanager: line 1048: getServerPid: command not found

I've been having this too since I last updated arkmanager. Doesn't seem to do anything bad though.

**Comment by klightspeed** [comment]
> /usr/local/bin/arkmanager: line 268: /var/log/arktools/arkmanager.log: Permission denied

😞 
Please `chown steam:steam /var/log/arktools` (or whichever user you have set `steamcmd_user` to).

Also please stop running `arkmanager` as root and instead run it as `steam`

> /usr/local/bin/arkmanager: line 1048: getServerPid: command not found

0a1d808 should fix this error.

> Is this automatic enabling the mods at the players?

😕
