### ISSUE TITLE
can't execute this command

### ISSUE THREAD

**Issue by keithtp1** [arkmanager/ark-server-tools#687]
curl -sL http://git.io/vtf5N | sudo bash -s steam

**Comment by keithtp1** [comment]
system: Debian GNU/Linux 8 (jessie) 64-bit

**Comment by klightspeed** [comment]
Does the following work:
```
wget https://raw.githubusercontent.com/FezVrasta/ark-server-tools/master/netinstall.sh
bash netinstall.sh steam
```

**Comment by keithtp1** [comment]
i get this if i do that 

Getting latest release...
Unable to get latest release

**Comment by klightspeed** [comment]
You will need the following programs installed:
```
curl
lsof
sudo
```

**Comment by keithtp1** [comment]
installed it all and still does not work!

**Comment by klightspeed** [comment]
```
apt-get update
apt-get install curl lsof
```

After updating the APT cache and installing curl and lsof, try installing arkmanager again.
