### ISSUE TITLE
Update log no longer updating

### ISSUE THREAD

**Issue by Rob-bb** [arkmanager/ark-server-tools#690]
The arkmanger is no longer adding to or creating the update log, I have manually run update and it shows it is working on screen, but no log entries are created.  This started last night.  

There are entries in the steam workshop_log.txt file

**Comment by klightspeed** [comment]
The updates are currently being logged to `arkmanager.log`

**Comment by rob-bb** [comment]
Ahh, ok, cool thanks

**Comment by rob-bb** [comment]
Hi, would you be able to show in  the arkmanager log which instance is creating the log entry?

**Comment by klightspeed** [comment]
With v1.6.14, both arkmanager.log and arkserver.log should now contain the instance writing the log line.

**Comment by rob-bb** [comment]
Thnaks :)
