### ISSUE TITLE
Mods activation

### ISSUE THREAD

**Issue by ISaneI** [arkmanager/ark-server-tools#751]
I downloaded some mods but when i start the server they dont get loaded. When i try
 `arkmanager enablemod 510590313` 

it says 

`
Running command '510590313' for instance 'main'
arkmanager v1.6: unknown command '510590313' specifiedUsage: arkmanager [Commands]
`
..... and a list of commands

Can i just write the mod Numbers in the  `/shootergame/saved/config/linuxserver/GameUserSettings.ini` like i did without that tool?

**Comment by rlex** [comment]
i e in instance config (theisland.cfg for example)
```
ark_GameModIds="821530042,572277026,655261420,756389708,793605978,737297870,718412068,854186603"
```
