### ISSUE TITLE
Can I install an older version?

### ISSUE THREAD

**Issue by Enigmaticzor** [arkmanager/ark-server-tools#771]
Hello all,

I recently updated the server tools, and there seems to be an error for me where it receives signal 11 and crashes the server when I start it. My older server tools version did not have this problem and if I start without the server tools it works fine. Is there a way to install an older version of the server tools for the time being? (The one that actually worked)

Update: Error at the new version:

Signal 11 caught.
EngineCrashHandler: Signal=11
/usr/local/bin/arkmanager: line 1028: 30926 Segmentation fault      "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
2017-04-25 00:02:24: Bad PID ''; expected '30926'
2017-04-25 00:02:24: exited with status 0

**Comment by Enigmaticzor** [comment]
Update: This is the error im getting with the newer version.

Signal 11 caught.
EngineCrashHandler: Signal=11
/usr/local/bin/arkmanager: line 1028: 30926 Segmentation fault      "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
2017-04-25 00:02:24: Bad PID ''; expected '30926'
2017-04-25 00:02:24: exited with status 0

**Comment by klightspeed** [comment]
Signal 11 (Segmentation Fault) is coming from the ARK server itself, not from this tool.

The most common causes would be corrupt game files, corrupt save files, or bad mods.

Try:
* Backup everything in `ShooterGame/Saved` to another directory
* Perform a validation update, either using `arkmanager update --validate`, or using `steamcmd` using its `app_update 376030 validate` command.
* Update all of your mods, either using `arkmanager update --update-mods` or by using the `-automanagedmods` option to the ARK server.
* If the server still crashes immediately, then try moving the `Saved` directory somewhere else
* If the server still crashes immediately, then try removing all of the installed mods, and finding the mod or combination of mods that crashes the server.
* If it was a mod that was crashing the server, then try removing the Saved directory that was created by the game server, and moving your Saved directory back into place.

**Comment by Enigmaticzor** [comment]
I validated, for some reason my ShooterGameServer is gone after it. So something seems pretty messed up. (it was there before validating, now I no longer have a serverexec). Also I noticed the manager tries to run steam from /home/steam, which is not the directory I told it to use in the arkmanager.cfg. Is there a change in the tools regarding this or did my arkmanager just go rogue?

**Comment by klightspeed** [comment]
Did you perform a user-install? Check if `%HOME%/.arkmanager.cfg` or `%HOME%/.config/arkmanager/instances/main.cfg` exist.

**Comment by Enigmaticzor** [comment]
They do not exist. I noticed this morning however my Server EXEC is gone AGAIN. After not touching it since turning on the server last night.

Could there be any reason it seems to keep auto-deleting itself?

**Comment by klightspeed** [comment]
What user are you running `arkmanager` as?  If you didn't want the service, did you disable it?  Do you have any update cron jobs set up?

Was the server exec deleted after updating, or without running any other commands?

>> Check if %HOME%/.arkmanager.cfg or %HOME%/.config/arkmanager/instances/main.cfg exist.
>
> They do not exist.

Sorry for the confusion on variables - I meant `$HOME/.arkmanager.cfg` and `$HOME/.config/arkmanager/instances/main.cfg`, where `$HOME` is the home directory of the `steamcmd_user` specified in `arkmanager.cfg`

If you have specified a staging directory, is that staging directory writable by the specified user?
