### ISSUE TITLE
Checkup dates is only downloading some of the mods, then not updating them

### ISSUE THREAD

**Issue by Rob-bb** [arkmanager/ark-server-tools#801]
when I run Check update it downloads 11 of 22 mods.  

Then it declares all are update and does nothing.  I Know one of the mods it downloads has been updated, but it does not stop and restart, so I think it is not copying any files, and I don't know why it only downloads half of them.  

Command is:  arkmanager update --update-mods --warn --saveworld @one

All it shows in log is: 
```
2017-06-14 17:38:33: [one] Checking for update; PID: 20707
2017-06-14 17:39:44: [one] Your server is already up to date! The most recent version is 1887421.
```

Has been running for several months prior to this.  The mod I know has been updated is one of the 11 it decides to download.

**Comment by rlex** [comment]
Saw something similar, i usually do reinstallmod $modid @all

**Comment by Chingis-Khan** [comment]
Didn't know about the reinstallmod command, I was uninstalling then installing :)

**Comment by CaptSilver** [comment]
I run reinstall mod everytime there is an update. Keeps down issues. Just setup a cron job to do it automatically.
