### ISSUE TITLE
Server Cluster

### ISSUE THREAD

**Issue by ISaneI** [arkmanager/ark-server-tools#827]
I was reading some posts about more than one instance like ([#289](https://github.com/FezVrasta/ark-server-tools/issues/289) ) but I'm not sure about, how to setup a Cluster that the players can transfer dinos etc. around. Do I just need to let the `arkserverroot` the same? And does this also work if there are different mods on the servers? I'm sorry if this are dumb questions, but I can't try it out at the moment.. tomorrow the new server should be delivered and I want to set it up as fast as I can, my friends are already waiting for me :o. 

Thank you in advance

**Comment by deaerator** [comment]
Were you successful in getting a cluster working?

**Comment by ISaneI** [comment]
@deaerator Yeah I got it running for some month... But we started to renovate the basement and I had to turn off my servers... Got some new EthernetCables down there 10GB+ but the new ServerRack gets deliverd in week 11... and cause there is still a lot of dust I will wait until its deliverd. But cause I replaced one "old pc  server" (the like 10 year old 200gb disk broke with the ark server...) with some serious stuff I will setup everything again..
