### ISSUE TITLE
Constant crashes lately and errors

### ISSUE THREAD

**Issue by noodohs** [arkmanager/ark-server-tools#837]
I have my server installed on an Ubuntu server. My server was running flawlessly for months, but the past couple weeks it goes down almost every day. When I run certain commands, I get errors. Here is the chain of events from today, at the end of which I seem to no longer have an ARK server, so I am freaking out quite a bit.

> nick@server:~ $ arkmanager status
Running command 'status' for instance 'main'
 Server running:   No
 Server listening:   No
 Server build ID:   2051466
nick@server:~ $ arkmanager update --validate
Running command 'update' for instance 'main'
Checking for update; PID: 23096
The server is already stopped
Performing ARK update ... Update to  complete
touch: cannot touch '/home/nick/ARK/ShooterGame/Saved/.ark-update.time': No such file or directory
nick@server:~ $ arkmanager checkmodupdate
Running command 'checkmodupdate' for instance 'main'
[  WARN  ]      Your ARK server exec could not be found.
mkdir: cannot create directory â/home/nick/ARKâ: Permission denied
[  ERROR  ]     The ARK SavedArks directory is not writable, and saveworld will fail
Error: /usr/games/steamapps/workshop does not exist
nick@server:~ $ arkmanager upgrade-tools
arkmanager v1.6: Checking for updates...
Getting latest release...
Your ARK server tools are already up to date
nick@server:~ $ arkmanager install
Running command 'install' for instance 'main'
Creating the ARK server root directory (/home/nick/ARK)
mkdir: cannot create directory â/home/nick/ARKâ: Permission denied
Installing ARK server ... -mkdir: cannot create directory â/home/nick/.steamâ: Permission denied
mkdir: cannot create directory â/home/nick/.steamâ: Permission denied
mkdir: cannot create directory â/home/nick/.steamâ: Permission denied
mkdir: cannot create directory â/home/nick/.steamâ: Permission denied
ln: failed to create symbolic link '/home/nick/.steam/root': No such file or directory
ln: failed to create symbolic link '/home/nick/.steam/steam': No such file or directory
mkdir: cannot create directory â/home/nick/.steamâ: Permission denied
cp: cannot create regular file '/home/nick/.steam/steamcmd/': No such file or directory
cp: cannot create regular file '/home/nick/.steam/steamcmd/linux32/': No such file or directory
/usr/games/steamcmd: 24: exec: /home/nick/.steam/steamcmd/steamcmd.sh: not found
nick@server:~ $ sudo arkmanager install
[sudo] password for nick:
Running command 'install' for instance 'main'
Installing ARK server ... nick@server:~ $ arkmanager checkmodupdate
Running command 'checkmodupdate' for instance 'main'
[  WARN  ]      Your ARK server exec could not be found.
mkdir: cannot create directory â/home/nick/ARKâ: Permission denied
[  ERROR  ]     The ARK SavedArks directory is not writable, and saveworld will fail
Error: /usr/games/steamapps/workshop does not exist
nick@server:~ $ sudo arkmanager checkmodupdate
Signature not found in user keyring
Perhaps try the interactive 'ecryptfs-mount-private'
Running command 'checkmodupdate' for instance 'main'
[  WARN  ]      Your ARK server exec could not be found.
mkdir: cannot create directory â/home/nick/ARKâ: Permission denied
[  ERROR  ]     The ARK SavedArks directory is not writable, and saveworld will fail
Error: /usr/games/steamapps/workshop does not exist
nick@server:~ $ cd /usr/games/steamapps
-bash: cd: /usr/games/steamapps: No such file or directory
nick@server:/etc/arkmanager$ arkmanager status
Running command 'status' for instance 'main'
[  WARN  ]      Your ARK server exec could not be found.
mkdir: cannot create directory â/home/nick/ARKâ: Permission denied
[  ERROR  ]     The ARK SavedArks directory is not writable, and saveworld will fail
 Server running:   No
 Server listening:   No
 Server build ID:
nick@server:/etc/arkmanager/instances$ arkmanager install
Running command 'install' for instance 'main'
Creating the ARK server root directory (/home/nick/ARK)
mkdir: cannot create directory â/home/nick/ARKâ: Permission denied
Installing ARK server ... -mkdir: cannot create directory â/home/nick/.steamâ: Permission denied
mkdir: cannot create directory â/home/nick/.steamâ: Permission denied
mkdir: cannot create directory â/home/nick/.steamâ: Permission denied
mkdir: cannot create directory â/home/nick/.steamâ: Permission denied
ln: failed to create symbolic link '/home/nick/.steam/root': No such file or directory
ln: failed to create symbolic link '/home/nick/.steam/steam': No such file or directory
mkdir: cannot create directory â/home/nick/.steamâ: Permission denied
cp: cannot create regular file '/home/nick/.steam/steamcmd/': No such file or directory
cp: cannot create regular file '/home/nick/.steam/steamcmd/linux32/': No such file or directory
/usr/games/steamcmd: 24: exec: /home/nick/.steam/steamcmd/steamcmd.sh: not found

I have checked and there does not seem to be an ARK directory anymore, which has me really, really worried. I had tried the "install" command in the hopes that it would clear up whatever was causing the errors, but now I just don't know what's going on at all. We have put a LOT of work into this server, so I'm really hoping it isn't just gone. To my knowledge, things seemed to start going wrong after the last time I updated the server tools. I am thinking that maybe I should uninstall server tools and reinstall, but will that delete the server, too?

**Comment by noodohs** [comment]
Okay, I rebooted and at least the folders are there again. I really do not know what is going on. Usually rebooting the server seems to get the errors to go away, which makes no sense to me.

**Comment by klightspeed** [comment]
The missing directories and the permission denied messages under `/home/nick` suggest that either `/home` is being lazily unmounted, or another filesystem is being mounted over `/home` (where `/home/nick` exist on both the currently-mounted filesystem and either the root filesystem or the filesystem being over-mounted).

Check your crontab to see if any filesystems are being unmounted or mounted.  When it's working correctly, grab the output of `mount`, and compare that to the output of `mount` when it's not working.

`arkmanager` never calls `mount`, and will drop privileges to the `steamcmd_user` specified in arkmanager.cfg` if it is run as `root`.

**Comment by noodohs** [comment]
I have nothing in my crontab other than an "arkmanager update --update-mods" command.

**Comment by klightspeed** [comment]
Please compare the output of `mount` when everything is working correctly with the output of `mount` when you get the permission denied / file not found errors.

**Comment by noodohs** [comment]
Do you mean to just type "mount"? If so, here is what happens. We just did
a Dino wipe and it crashed shortly after. While I would normally blame that
on the wipe, we have done that many times before and had no issues. I left
it running for weeks on end where it happily auto updated and never once
crashed. Now it is a daily occurrence.

Welcome to Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-92-generic x
6_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

7 packages can be updated.
1 update is a security update.


Last login: Sun Aug 20 07:33:55 2017 from 192.168.1.1
nick@server:~$ arkmanager status
Running command 'status' for instance 'main'
 Server running:   No
 Server listening:   No
 Server build ID:   2053476
nick@server:~$ mount
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,nosuid,relatime,size=7895812
,nr_inodes=1973953,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,g
d=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,noexec,relatime,size=15
9792k,mode=755)
/dev/mapper/server--vg-root on / type ext4 (rw,relatime,err
rs=remount-ro,data=ordered)
securityfs on /sys/kernel/security type securityfs (rw,nosu
d,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relat
me,size=5120k)
tmpfs on /sys/fs/cgroup type tmpfs (rw,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nod
v,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-
groups-agent,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexe
,relatime)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,
odev,noexec,relatime,perf_event,release_agent=/run/cgmanage
/agents/cgm-release-agent.perf_event)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid
nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,n
suid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nod
v,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nod
v,noexec,relatime,hugetlb,release_agent=/run/cgmanager/agen
s/cgm-release-agent.hugetlb)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,node
,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,
oexec,relatime,pids,release_agent=/run/cgmanager/agents/cgm
release-agent.pids)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nod
v,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,node
,noexec,relatime,cpuset,clone_children)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev
noexec,relatime,blkio)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relat
me,fd=29,pgrp=1,timeout=0,minproto=5,maxproto=5,direct)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime)
mqueue on /dev/mqueue type mqueue (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relati
e)
/dev/sda1 on /boot type ext2 (rw,relatime,block_validity,ba
rier,user_xattr,acl)
cgmfs on /run/cgmanager/fs type tmpfs (rw,relatime,size=100
,mode=755)
lxcfs on /var/lib/lxcfs type fuse.lxcfs (rw,nosuid,nodev,re
atime,user_id=0,group_id=0,allow_other)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatim
,size=1589792k,mode=700,uid=1000,gid=1000)
/home/.ecryptfs/nick/.Private on /home/nick type ecryptfs (
w,nosuid,nodev,relatime,ecryptfs_fnek_sig=d0f9141d87b4570d,
cryptfs_sig=ea830b11e114dd0c,ecryptfs_cipher=aes,ecryptfs_k
y_bytes=16,ecryptfs_unlink_sigs)
nick@server:~$

**Comment by klightspeed** [comment]
```
/home/.ecryptfs/nick/.Private on /home/nick type ecryptfs (rw,nosuid,nodev,relatime,ecryptfs_fnek_sig=d0f9141d87b4570d,ecryptfs_sig=ea830b11e114dd0c,ecryptfs_cipher=aes,ecryptfs_key_bytes=16,ecryptfs_unlink_sigs)
```

You might want to move the ARK server to another directory - I suspect that systemd is unmounting `/home/nick` when you log out.

**Comment by noodohs** [comment]
I do everything over SSH, if that makes any difference. I'm not using screen, but it never caused any problems before. To clarify, are you suggesting that I should move it to, say, the root directory? That is, just generally out of the user folders for "nick"? Sorry, I am not super well-versed in these things, as you have probably surmised. It's just odd to me that everything was working so flawlessly before and now it is not. We may reformat and reinstall after Ark launches for real anyway, but it'll be good for me to know what to do/not to do after that to make sure this doesn't happen again.

**Comment by klightspeed** [comment]
It appears your home directory is being mounted from an encrypted directory.  I suspect that when your last SSH session logs out, systemd is terminating all background processes (including your ARK server), and unmounting your home directory.  This is a recent change in systemd under Ubuntu etc.

It's also possible that previously when it was working without issue, you had something holding open your session, and that is no longer the case.

Most services will run under a user created specifically created for the purpose of running the service.  It would be a good idea to do the same for your game server.

* Create a user (such as `ark-server`) to run the server under
  `useradd -m ark-server`
* As root, copy or move all of the server files to the user's directory
  `sudo rsync -av /home/nick/ARK/. /home/ark-server/ARK`
  `sudo rsync -av /home/nick/steamcmd/. /home/ark-server/steamcmd`
* Fix the ownership on the files
  `sudo chown -R ark-server:ark-server /home/ark-server/ARK`
  `sudo chown -R ark-server:ark-server /home/ark-server/steamcmd`
  `sudo chown -R ark-server:ark-server /etc/arkmanager
* Modify the `steamcmd_user` and root paths in your configs to the new user and paths
  `sudo $EDITOR /etc/arkmanager/arkmanager.cfg`
  `sudo $EDITOR /etc/arkmanager/instances/main.cfg`
* If you are using the systemd service, change the `User` setting in `/etc/systemd/system/arkmanager@.service`
* Run `sudo su ark-server` to switch to that user context (do not log in directly to that user using `ssh`, as otherwise you will likely be in the same situation as you are currently in).
* Start and manage the server as usual

You will need to remember to `sudo su ark-server` when you want to manage the game server.

**Comment by noodohs** [comment]
Well, this is promising! It was probably two months ago or so when I set everything up initially, I know I have installed a few Ubuntu updates since then (or at least it told me a system restart is required when I logged in). Thank you very much. What I normally do is go in via SSH (usually either Putty on my desktop or Connectbot on my phone), start the server, then exit the session. The server will stay up for a day or so, usually, then it goes down.

To clarify, do I need to reinstall Ark Server Tools? I'm guess not since they are in /etc instead of under the nick user. I will presumably need to edit the config files to point them to the new locations, though.

**Comment by klightspeed** [comment]
If `arkmanager` has been installed system-wide (i.e. it's in `/usr/bin` or `/usr/local/bin`), then a re-install is not necessary.

**Comment by noodohs** [comment]
Awesome. I will give this all a go in the next couple days here and hopefully that will sort it out. Thank you very much for all your help!

**Comment by noodohs** [comment]
Actually quick question, I don't seem to have a steamcmd directory in /home/nick for some reason, though I do have a file that is called steamcmd. The command to move it doesn't seem to work - just says it's not a directory. Am I doing something wrong? Should I just reinstall it as the "arkserver" user?

**Comment by klightspeed** [comment]
Your previous logs suggest you are using the `steamcmd` installed in Ubuntu.

Since `steamcmd` is a file, this suggests that you have at some point copied the `steamcmd` executable to your home directory.  If `steamcmd_exec` is pointing to that file, then copy it normally from `/home/nick` to `/home/ark-server`.

**Comment by noodohs** [comment]
The arkmanager.cfg file actually points to /usr/games with file "steamcmd" as the exec. Since that is not under the "nick" user, presumably, do I need to do anything with it?

**Comment by klightspeed** [comment]
Since it points to the system-installed `steamcmd`, you should not need to move `steamcmd` from `/home/nick` to `/home/ark-server`

**Comment by noodohs** [comment]
When I run arkmanager status after moving everything, it says:
arkserver@server:~ $ arkmanager status
[  ERROR  ]     You have not rights to write in the log directory.
Running command 'status' for instance 'main'
[  ERROR  ]     You have not rights to write in the log directory.
 Server running:   No
 Server listening:   No
 Server build ID:   2053476

Do I need to worry about that? I see that the Steam stuff is in the /home/nick/.steam hidden folder, not sure if that's related? Didn't change ownership of any of the steam stuff since I didn't move any of it, so that may also be related.

**Comment by klightspeed** [comment]
```
chown -R arkserver:arkserver /var/log/arktools
```

**Comment by noodohs** [comment]
Yup, that did it. Thanks again for all your help and sorry for all the questions. Appears to be up and running, fingers crossed!

**Comment by noodohs** [comment]
Okay, been about two days without issue, even updated itself after I updated the crontab to do so. You're the man, thanks!
