### ISSUE TITLE
Server shows as running even though it's not

### ISSUE THREAD

**Issue by noodohs** [arkmanager/ark-server-tools#840]
When I run the status, this is the output:

> arkserver@server:/home/nick$ arkmanager status
> Running command 'status' for instance 'main'
>  Server running:   No
>  Server listening:   Yes
> Server Name: Dino Fight Club - (v265.51)
> Players: 0 / 10
> Active Players: 0
>  Server online:   Yes
>  ARKServers link:   http://arkservers.net/server/69.255.147.239:27015
>  Server build ID:   2066619

It also shows in the server list in Steam. That makes no sense to me. This is after rebooting the entire server computer, too, and not having input any commands. I don't remember arkmanager being set to start on boot and it's causing a lot of problems with me logging in. I am also not able to issue the "stop" command since it thinks there is no server running. On top of that, if I issue the "start" command, THEN issue a "stop" command, I end up with the same output as above again. Something is going horribly wrong and I don't know what it is.

If it means anything, I recently moved my server files from the "nick" user to the "arkserver" user on my server because it kept going down. I also updated the permissions and all that. It has been working fine all week since doing that until now and I can't figure out what's going on.

On further looking, when I run the "top" command, I see this;

> 1499 nick      20   0 8760056 5.228g  60364 S  71.7 34.5   2:37.93 ShooterGameServ

So it's definitely starting for some reason. How do I stop it? Why is it doing this?

**Comment by klightspeed** [comment]
What is the output of `systemctl status arkmanager@main`?

To stop this service from starting at startup, try:
```
systemctl disable arkmanager
```

**Comment by noodohs** [comment]
The output (this is after killing the ShooterGameServ process via top) is:

> nick@server:~$ systemctl status arkmanager@main
> â arkmanager@main.service - Daemon to start an ark server instance
>    Loaded: loaded (/etc/systemd/system/arkmanager@.service; static; vendor preset: enabled)
>    Active: inactive (dead)
> 
> Aug 27 22:22:10 server arkmanager[1442]: Setting breakpad minidump AppID = 346110
> Aug 27 22:22:14 server arkmanager[1442]: 2017-08-27 22:22:14: Bad PID ''; expected '1499'
> Aug 27 22:26:53 server arkmanager[1442]: Using binned.
> Aug 27 22:26:53 server arkmanager[1442]: 4.5.1-0+UE4 7038 3077 402 7
> Aug 27 22:26:53 server arkmanager[1442]: /home/buildbot/buildslave/steam_rel_client_linux64/build/src/clientdll/applicationmanager.cpp (3004) : Assertion Failed: CApplicationManager::GetMountVolume: invalid index
> Aug 27 22:26:53 server arkmanager[1442]: /home/buildbot/buildslave/steam_rel_client_linux64/build/src/clientdll/applicationmanager.cpp (3004) : Assertion Failed: CApplicationManager::GetMountVolume: invalid index
> Aug 27 22:26:53 server arkmanager[1442]: /home/buildbot/buildslave/steam_rel_client_linux64/build/src/clientdll/applicationmanager.cpp (3155) : Assertion Failed: m_vecInstallBaseFolders.Count() > 0
> Aug 27 22:26:53 server arkmanager[1442]: CtrlCHandler: Signal=15
> Aug 27 22:26:53 server arkmanager[1442]: /usr/local/bin/arkmanager: line 1110:  1499 Aborted                 (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
> Aug 27 22:26:53 server arkmanager[1442]: 2017-08-27 22:26:53: exited with status 0

Also annoying is that a lot of the stuff we had put up is now gone, but I suspect that could be related to an Extinction Core update. The only other thing I have done recently is delete the old ARK folder from the nick user.

I am fine with the server starting a startup if it is going to work correctly, but as of now that does not seem to be the case.

**Comment by klightspeed** [comment]
> 1499 nick 20 0 8760056 5.228g 60364 S 71.7 34.5 2:37.93 ShooterGameServ

That looks like it's still starting as `nick` rather than as `arkserver`.

Please check that `steamcmd_user=arkserver` in `arkmanager.cfg`

Also if there is a `User` setting in `/etc/systemd/system/arkmanager@.service`, check that it is set to `arkmanager` rather than `nick`

**Comment by noodohs** [comment]
arkmanager.cfg was set correctly, but the other setting was still on nick. Hopefully that should do it. Thanks (again)!

Totally unrelated, but I've not had to restore from a backup before. When Extinction Core updated, a lot of our dinos and structures disappeared, so I want to restore from a backup. I have the backups, just not sure what to do with them...

**Comment by klightspeed** [comment]
The backups made using `arkmanager backup` contain the `.ark` (map), `.arktribe` (group) and `.arkprofile` (player) and `.arktributetribe` files from the saved arks directory (default `Saved/SavedArks`), and the `GameUserSettings.ini` and `Game.ini` files from `Saved/Config/LinuxServer`
