### ISSUE TITLE
small mod updates fails

### ISSUE THREAD

**Issue by postpapa** [arkmanager/ark-server-tools#896]
hey,

we're running 3 server with your tool and running this script every 20 min to check for update 

```
#!/bin/sh

HOME=/home/ark
TODAY=$(date +"%Y-%m-%d")
LOGFILE=$HOME/log/$TODAY-cron.log

echo "$(date): updating all ark instances..." >> $LOGFILE
/usr/local/bin/arkmanager update @all --warn --saveworld --update-mods --backup >> $LOGFILE
```

problem is, when mod updates are very small < ~2 MB it only noticed the update for the first server and for the other 2 it says
`Your server is already up to date!`

is there any way to fix it?

great work btw :)

**Comment by klightspeed** [comment]
Do the game servers share the same directory?

**Comment by postpapa** [comment]
nope, they have all different game folders

**Comment by dahlskebank** [comment]
I had the same issue and changed it to update each server individually, with some time delay to avoid issues. Could perhaps be solved by using staging dir, or that is what caused the problem to begin with. Either way, don't use @all and it's a fix!

**Comment by postpapa** [comment]
We are using a stagingDir. And if I run "arkmanager update @ark2 --update-mods" after it failed it says "already up to date" too

**Comment by klightspeed** [comment]
What does `arkmanager checkmodupdate @ark2` show?

**Comment by postpapa** [comment]
i'll try....but first i have to push a small update to my test mod :D

**Comment by postpapa** [comment]
`arkmanager checkmodupdate @ark4
Running command 'checkmodupdate' for instance 'ark4'
Error: /home/ark/steamcmd/steamapps/workshop does not exist`

**Comment by klightspeed** [comment]
v1.6.36 should now look for the steam workshop directory.

**Comment by postpapa** [comment]
so i have to run 
`arkmanager update @all`
and 
`arkmanager checkmodupdate @all`
?

**Comment by klightspeed** [comment]
Upgrading to v1.6.36 should fix that `Error: /home/ark/steamcmd/steamapps/workshop does not exist`, which is likely the cause of not updating mods.

**Comment by postpapa** [comment]
ah okay. so i can run my first script and it should work. i'll come back to report you the results

**Comment by SinisterSole** [comment]
@klightspeed
So I am wondering if the --update-mods(modupdate) is looking at the staging directory and not the server mods directory. I am having a simular issue as @postpapa
It seems that if I update 'center' first, then 'island' and 'scorched' do not update. Or if I update 'island' first, then 'center' and 'scorched' do not.
I have a wall of text if you can have a look.

**Comment by SinisterSole** [comment]
I have a band aid on mine until this gets resolved:
crontab -e
0 1 * * * /home/*****/bin/arkmanager --cronjob update @all --warn --saveworld --backup --update-mods --args -- > /home/*****/cronlogs/arkupdtcron-`date +\%Y-\%m-\%H\ \%k:\%M:\%S`.log
0 2 * * * /home/*****/bin/arkmanager --cronjob installmods @all --args -- > /home/*****/cronlogs/arkinstmodcron-`date +\%Y-\%m-\%H\ \%k:\%M:\%S`.log
0 3 * * * /home/*****/bin/arkmanager --cronjob restart @all --warn --saveworld --args -- > /home/*****/cronlogs/arkrstrtcron-`date +\%Y-\%m-\%H\ \%k:\%M:\%S`.log

Updates ALL at 01:00
Installs ALL mods at 02:00
Restarts ALL at 03:00

**Comment by SinisterSole** [comment]
@klightspeed
Shouldn't the lines starting at 1768 be modupdate=1 ?
Below is what is currently in v1.6.38

if [ -n "$modupdate" ]; then
    if [ -z "$nodownload" ]; then
      if ! doDownloadAllMods; then
        modupdate=
      fi
    fi
    if ! isAnyModUpdateNeeded; then
      modupdate=
    fi
  fi

**Comment by SinisterSole** [comment]
NVM, fixes may issue with mod updates in all instances but restarts server even if no updates needed.

**Comment by SinisterSole** [comment]
@klightspeed
Does the script care where the arkStagingDir= goes?
The arkmanager.cfg or the instance.cfg?
I have moved that setting into the instance.cfg and remarked it from the arkmanager.cfg  to see if it works on all instances but of course this would be the week there would be no mod updates...

**Comment by postpapa** [comment]
s+ updated an hour ago :P

**Comment by klightspeed** [comment]
Settings in the instance config override settings in `arkmanager.cfg`

**Comment by SinisterSole** [comment]
@klightspeed
I had it in both the global and the instance.cfg but still had only one
updating mods.

Just confirmed that putting arkStagingDir= in the instance.cfg and
remarking it from the arkmanager.cfg fixes my issue of "all instances not
updating mods properly".

Thanks everyone :)

**Comment by OverMind79** [comment]
is here something new i need that fix to
