### ISSUE TITLE
Ark reset maps random after updates

### ISSUE THREAD

**Issue by Chriz0815** [arkmanager/ark-server-tools#932]
Hi i have a issue for some time now it happened 6-7 times in the last 3 Month. Im running Ark in a Cluster with all maps. Sometimes after Wildcard release a update and the arkmanager starts to update them and starting the servers again im losing the map save state and it will be a fresh map, profiles painting cash and so on never got reseted or deleted. Mostly happen on Ragnarok and Aberation.

I have a cronjob running checking every hour for an update.
And a cronjob for autobackup wich is working fine

Here are my configs
[arkmanagerCLUSTER.zip](https://github.com/FezVrasta/ark-server-tools/files/1792528/arkmanagerCLUSTER.zip)

Here are the logfiles (all passwords got removed)

[logs.zip](https://github.com/FezVrasta/ark-server-tools/files/1792594/logs.zip)

last time it was happening was 2018-03-07 19:01:31 on ragnarok and aberation

what im doing wrong?

**Comment by Hulth** [comment]
I have seen this several times as well on Ragnarok, Aberration and The Island. Thinking it's a Wildcard issue since it fails to load the map sometimes on startup.

**Comment by Chriz0815** [comment]
Since i reported this it never happend again. I think it was maybe a weird wildcard issue.
