### ISSUE TITLE
newbie in need of help

### ISSUE THREAD

**Issue by Carmichaeldb** [arkmanager/ark-server-tools#962]
Good day, I am very new with Ark Server Tools, and Linux entirely. My admin had highly suggested using Linux and ark server tools on our new server (upgraded from our old windows one), and we just got it set up and going except we don't have our server configured to do our auto restarts, auto updates, and restart countdown timers. Unfortunately, things have happened suddenly where he is unable to get online to continue to help me configure this, and I have absolutely no idea what I am doing. I see in the config file the example but i'm not all that sure how to work it. for update warning messages it says %d is a replacement for the number, do I add a number here and how do I make it use that number timer for a countdown before restarting? Sorry I am really confused. All I need is 15 minute countdown for restarts, auto start the server on crashes, auto updates, and a daily restart at 4am est.

**Comment by SinisterSole** [comment]
In the arkmanager,cfg file there is a line like this
arkwarnminutes="60"                                                 # number of minutes to warn players when using update --warn
Change the arkwarnminutes to what every you like.

The warning message should be ok unmodified.

As for the 4AM restart, you need to edit crontab in linux and add arkmanager restart @all

**Comment by SinisterSole** [comment]
I almost forgot, you have to add a cronjob for the update to work also. Mine checks for update every 4 hrs and looks like this
0 0,4,8,12,16,20 * * * /home/xxxxx/bin/arkmanager update --warn --saveworld --backup --update-mods @all

Here is the man page for crontab in linux
http://man7.org/linux/man-pages/man5/crontab.5.html
