### ISSUE TITLE
arkmanager .cfg file, Extinction Map Setting

### ISSUE THREAD

**Issue by freakyy85** [arkmanager/ark-server-tools#982]
Hi! I'm wondering, as ARK Extinction gets released in less than 1 hour, what will the map have to be set to in the .cfg of the server for Extinction? Thanks! :)

**Comment by klightspeed** [comment]
I don't know - the dedicated server does not appear to come with any new map or any new map mod.

From the steam store, it looks like it releases at midnight UTC.

**Comment by Redeye123** [comment]
Extinction without the _P this time

**Comment by N-Rico** [comment]
Is this working for you? I've set Extintion in the cfg file for the instance but it keeps starting up with TheIsland.

**Comment by freakyy85** [comment]
Yes it works. Map set to “Extinction”. You need the latest server files: arkmanager update –update-mods @instance

 

Von: N-Rico <notifications@github.com> 
Gesendet: Mittwoch, 7. November 2018 08:16
An: FezVrasta/ark-server-tools <ark-server-tools@noreply.github.com>
Cc: Uwe Pfeifer <freaky@freakyonline.de>; Author <author@noreply.github.com>
Betreff: Re: [FezVrasta/ark-server-tools] arkmanager .cfg file, Extinction Map Setting (#982)

 

Is this working for you? I've set Extintion in the cfg file for the instance but it keeps starting up with TheIsland.

**Comment by zavg** [comment]
I experience the same issue as @N-Rico

**Comment by N-Rico** [comment]
I noticed I had the setting in the cfg file spelled with a capitol 'S' (ServerName instead of serverName), I will try if it works later (have the server running from the console in a screen session now)

**Comment by TeH-BaK** [comment]
I'm still having the same issue, pops up as the island instead of extinction, i've tried "arkmanager update --update-mods @instance" alongside a bunch of other commands, forced updates and such, it still acts like the map doesn't exist for me and just defaults to island. I have googled plenty for nothing useful to help with this problem.

**Comment by TeH-BaK** [comment]
the only idea I've came up with is it might be related to the fact i have "extinction core" installed as a mod on another cluster that the manager runs. and that the mods short name being 'extinction' is causing issues. but if i remove that mod... i'll be losing that cluster. Any thoughts or confirmations that extinction core could be causing some issues?

**Comment by TeH-BaK** [comment]
Turns out that was the problem, uninstalled the mod and it loads up fine.

**Comment by TeH-BaK** [comment]
extinction core mod files were causing issues for me, once i removed the mods files everything worked fine.

**Comment by N-Rico** [comment]
Problem is solved for me as well! (wrong capitalization on the serverMap property in cfg)
