### ISSUE TITLE
[  WARN  ]      Your ARK server exec could not be found.

### ISSUE THREAD

**Issue by freakyy85** [arkmanager/ark-server-tools#983]
Since now everything worked. I just did an arkmanager update --update-mods @all and now, it stopped working with the error: [  WARN  ]      Your ARK server exec could not be found. - can anyone help me?

**Comment by Redeye123** [comment]
It appears ark forgot to upload the linux binaries that folder contains only steamclient.so

**Comment by CaspyBXL** [comment]
They messed up bad ... every linux server with auto update will go down ...
BUILD 3283435 does not containt the Linux Exec ...
GREAT JOB TO WILDCARD WOHHOWW !

**Comment by thmhoag** [comment]
Thanks for posting this... was wondering if it was just me or not

**Comment by mcrosson** [comment]
https://twitter.com/Jatheish/status/1060017301448282113 just landed...
