### ISSUE TITLE
Arkmanager stop issue

### ISSUE THREAD

**Issue by waltzie** [arkmanager/ark-server-tools#990]
I've a strange issue, when i execute "arkmanager stop @all" (user steam account), lot of files.mod into Mods directory are deleted.
Is is a ShooterGame issue ?!
How can i debug it? Logs?

Thanks

**Comment by klightspeed** [comment]
Sounds very similar to the issue encountered in #789 - apparently a setting in Game.ini was causing this issue for them.

**Comment by waltzie** [comment]
Dear Ben,

yes it’s the same issue.

I found the way to solve it here: https://ark.gamepedia.com/Talk:244.3 but it does not work !

Solution … just remove the switch                                       

 

Thanks Walter 

 

Da: Ben Peddell [mailto:notifications@github.com] 
Inviato: lunedì 26 novembre 2018 23:41
A: FezVrasta/ark-server-tools <ark-server-tools@noreply.github.com>
Cc: Walter Summonte <walter@summonte.com>; Author <author@noreply.github.com>
Oggetto: Re: [FezVrasta/ark-server-tools] Arkmanager stop issue (#990)

 

Sounds very similar to the issue encountered in #789 <https://github.com/FezVrasta/ark-server-tools/issues/789>  - apparently a setting in Game.ini was causing this issue for them.
