### ISSUE TITLE
Will ark-server-tools be modified to support Atlas?

### ISSUE THREAD

**Issue by Rob-bb** [arkmanager/ark-server-tools#992]
Will ark-server-tools be modified to support Atlas?

**Comment by klightspeed** [comment]
If ATLAS doesn't allow private servers, or no Linux server is released, then this is moot.

If a Linux server is released, but it doesn't use Unreal engine, then it would make more sense to create a separate ATLAS server tools.

Even if it does use Unreal engine, some stuff (e.g. backups and mods) are built around how ARK does stuff and would need either tweaking or rewriting to support another game server (such as ATLAS).

**Comment by Rob-bb** [comment]
Yea, They will allow private servers, I can't be sure on linux yet that much info  they havn't given, but it is based on modification of the same server and client they used to build ARK (that is using WildCards own version of UE4)

**Comment by CaspyBXL** [comment]
@Rob-bb 

For now after speaking with 2 wildcard fanboi's they seem not wanting to do the Linux version of the game ...

I hope they change their mind ... because we all know how we feel about Windows for game servers ... xD

**Comment by Rob-bb** [comment]
@CaspyBXL Where did this info come from?  And do you mean they don't want to release a linux client or  they don't want to release a linux server?

**Comment by CaspyBXL** [comment]
During a twitch event from the devs they talked about Linux, said yes for a client but server was not in the cards for now. They did however add it was not yet fixed and could change that.

**Comment by Rob-bb** [comment]
Damn, if anything I would have thought the client would be the one they would drop

**Comment by CaspyBXL** [comment]
It would be a shame Rob, I must admit !

**Comment by Rob-bb** [comment]
@CaspyBXL and @klightspeed The yare doing Linux servrs for Atlas after all :)

**Comment by klightspeed** [comment]
The appid for the server is 1006030, while the appid for the client is 834910.
i.e.
appid=1006030
mod_appid=834910
serverMap=Ocean
ark_ServerX=x
ark_ServerY=y
ark_QueryPort=23456
ark_Port=12345
ark_SeamlessIP=1.2.3.4

Note however that the Atlas cluster needs somewhat more setup than an ARK cluster - it needs a Redis server (`redis-server`), and one game server instance per grid square, as well as server config files created by the Atlas server grid editor (which are copied to the same directory as the game server executable.

See https://www.playatlas.com/index.php?/forums/topic/9735-unofficial-dedicated-server-guide/ for a guide on Windows setup (you should be able to replace Win64 with Linux and backslashes with forward slashes).

**Comment by paperrain** [comment]
> 
> 
> The appid for the server is 1006030, while the appid for the client is 834910.
> i.e.
> appid=1006030
> mod_appid=834910
> serverMap=Ocean
> ark_ServerX=x
> ark_ServerY=y
> ark_QueryPort=23456
> ark_Port=12345
> ark_SeamlessIP=1.2.3.4
> 
> Note however that the Atlas cluster needs somewhat more setup than an ARK cluster - it needs a Redis server (`redis-server`), and one game server instance per grid square, as well as server config files created by the Atlas server grid editor (which are copied to the same directory as the game server executable.
> 
> See https://www.playatlas.com/index.php?/forums/topic/9735-unofficial-dedicated-server-guide/ for a guide on Windows setup (you should be able to replace Win64 with Linux and backslashes with forward slashes).

We don't need any update? Can we run ATLAS with same ark tools? Only adding the variables of ATLAS?

Thanks!

**Comment by klightspeed** [comment]
As long as you keep any Atlas staging directory separate from any ARK staging directory (or run from a shared directory using AltSaveDirectoryName), arkmanager should be able to install, update and run the server.

I haven't run up a server myself yet - just downloaded the game server so far and checked the directory structure (essentially the same as ARK except with that extra AtlasTools directory with the Redis installer).

**Comment by Rob-bb** [comment]
Yes, and we should probably run a proper redis server on Linux anyway, thanks for the heads up @klightspeed

**Comment by BoiseComputer** [comment]
I have started a fork to see if I can get it working. Feel free to give any input. https://github.com/BoiseComputer/atlas-server-tools

**Comment by Rob-bb** [comment]
@BoiseComputer I don't understand, I think it is already working isn't it?  I cant run a server yet because the atlas server is borked on Ubuntu with a libcurl issue, but ark-server-tools did correctly install the server adn attempt to start it. The issues is in the actual ATLAS server code.

**Comment by BoiseComputer** [comment]
I want to install this on a server that is already running ARK server tools. I'm forking it so I can run them separately without issues.

**Comment by klightspeed** [comment]
Probably a good idea to keep the two server tools separate, as atlas-server-tools will likely need to evolve to handle ATLAS-specific stuff, just as ark-server-tools has evolved to handle ARK-specific stuff.

I don't know if anybody would want to run separate ATLAS grids on the same server, just as you can run separate ARK clusters or separate individual ARK servers on the same server.  I also don't know how ATLAS handles staggered updates, or if all of the servers need to be updated at the same time.

**Comment by BoiseComputer** [comment]
I've been running a grid on a server host. When running an update on the main instance it restarts all connected instances to apply the update.

**Comment by BoiseComputer** [comment]
I have tested running  a 2x2 grid managed by the altered version of the ARK Server Tools. I need to do some documentation on editing the json file. That is different than anything in ARK.
