### ISSUE TITLE
Mods fail to update

### ISSUE THREAD

**Issue by TruWrecks** [arkmanager/ark-server-tools#996]
Since the Extinction update to 288.110 my Ark servers will not stay up to date when mod updates are available.

I am using the script:

arkmanager update --update-mods --warn --saveworld @all

I am using crantob to run this every 20 minutes. It is updating 4 servers. Some servers are getting updates correctly but others fail. I need to delete the staging directory every few days to keep the mods updating properly. That defeats the purpose of the staging directory.

I have performed a surface scan on my drives with no issues found. I have tried changing the staging directory. So far I am stumped.

This worked great for several weeks prior to the update to 288.110. Makes me wonder if Steam changed something that requires an update.

Please advise.

**Comment by TruWrecks** [comment]
I am using ark_GameModIds="to define the mods." 

ark_GameModIds="1139371102,895711211,849985437,731604991,764755314,742077869,771393043,646366838,899250777,538827119,889745138,664477965,566887000,821530042,756389708,751991809,741203089,1497827043,1199589888,1440414363,834667662,1404697612,1313029740,558079412" 

I copied the mods directory to another directory and did a diff. There was only mod 756389708 was different. Deleting the directory was the only way the server would update everything.

**Comment by TruWrecks** [comment]
Here is a config from one of the servers with the sensitive info removed.

# config environment
arkserverroot="/home/steam/Ark/Lore/CarnioAberration"                                     # path of your ARK #server files (default ~/ARK)

# ARK server options - use ark_<optionname>=<value>
# comment out these values if you want to define them
# inside your GameUserSettings.ini file
serverMap="Aberration_P"                                               # server map (default TheIsland)
#serverMapModId=""                                         # Uncomment this to specify the Map Mod Id (<fileid> in http://steamcommunity.com/sharedfiles/filedetails/?id=<fileid>)
#ark_TotalConversionMod=""                                 # Uncomment this to specify a total-conversion mod
ark_RCONEnabled="True"                                              # Enable RCON Protocol
ark_RCONPort=""                                                # RCON Port
ark_SessionName="Carnio-Lore-Aberration"                                  # if your session name needs special characters please use the .ini instead
ark_Port="7797"                                                     # ARK server port (default 7778)
ark_QueryPort="27035"                                               # ARK query port (default 27015)
ark_ServerPassword=""                                               # ARK server password, empty: no password required to login
ark_ServerAdminPassword=""                               # ARK server admin password, KEEP IT SAFE!
ark_OverrideOfficialDifficulty=5.0
ark_MaxPlayers="20"
ark_GameModIds=ark_GameModIds="1139371102,895711211,849985437,731604991,764755314,742077869,771393043,646366838,899250777,538827119,889745138,664477965,566887000,821530042,756389708,751991809,741203089,1497827043,1199589888,1440414363,834667662,1404697612,1313029740,558079412"                      # Uncomment to specify additional mods by Mod Id separated by commas
ark_AltSaveDirectoryName="clusters/CarnioLoreCluster/Aberration"                                    # Uncomment to specify a different save directory name

# ARK server flags - use arkflag_<optionname>=true
#arkflag_OnlyAdminRejoinAsSpectator=true                            # Uncomment to only allow admins to rejoin as spectator
#arkflag_DisableDeathSpectator=true                                 # Uncomment to disable players from becoming spectators when they die

# ARK server options - i.e. for -optname=val, use arkopt_optname=val
#arkopt_StructureDestructionTag=DestroySwampSnowStructures
#arkflag_PreventDiseases=true
#arkflag_PreventDownloadSurvivors=true
#arkflag_PreventDownloadItems=true
arkflag_PreventDownloadDinos=true
#arkflag_PreventUploadSurvivors=true
#arkflag_PreventUploadItems=true
arkflag_PreventUploadDinos=true
arkflag_PreventOfflinePvP=true
arkopt_MapPlayerLocation=True
arkopt_ServerCrosshair=True
arkopt_AllowThirdPersonPlayer=True
arkopt_ShowFloatingDamageText=True
arkopt_listen=""
arkflag_exclusivejoin=""
arkflag_server=""
arkflag_NoTransferFromFiltering=""
arkopt_clusterid="CarnioLoreCluster"
arkflag_ForceAllowCaveFlyers=""
arkflag_USEALLAVAILABLECORES=""
arkflag_NoBattlEye=""
arkflag_ForceRespawnDinos=""
arkflag_log=""

**Comment by TruWrecks** [comment]
arkmanager.cfg

arkstChannel="master"                                               # change it to a different branch to get non-stable versions
install_bindir="/usr/local/bin"
install_libexecdir="/usr/local/libexec/arkmanager"
install_datadir="/usr/local/share/arkmanager"

# config SteamCMD
steamcmdroot="/home/steam/steamcmd"                                 # path of your steamcmd instance
steamcmdexec="steamcmd.sh"                                          # name of steamcmd executable
steamcmd_user="steam"                                               # name of the system user who own steamcmd folder
steamcmd_appinfocache="/home/steam/Steam/appcache/appinfo.vdf"      # cache of the appinfo command
steamcmd_workshoplog="/home/steam/Steam/logs/workshop_log.txt"      # Steam workshop log
#steamlogin="anonymous"                                             # Uncomment this to specify steam login instead of using anonymous login

# config environment
arkserverexec="ShooterGame/Binaries/Linux/ShooterGameServer"        # name of ARK server executable
arkbackupdir="/home/steam/ARK-Backups"                              # path to backup directory
arkwarnminutes="10"                                                 # number of minutes to warn players when using update --warn
arkautorestartfile="ShooterGame/Saved/.autorestart"                 # path to autorestart file
arkAutoUpdateOnStart="false"                                        # set this to true if you want to always update before startup
arkBackupPreUpdate="true"                                          # set this to true if you want to perform a backup before updating
arkStagingDir="/home/steam/Ark/ARK-Staging/"                            # Uncomment to enable updates to be fully downloaded before restarting the server (reduces downtime while updating)
steamdataroot=/home/steam/Ark

# Options to automatically remove old backups to keep backup size in check
# Each compressed backup is generally about 1-2MB in size.
#arkMaxBackupSizeMB="1024"                                            # Set to automatically remove old backups when size exceeds this limit
arkMaxBackupSizeGB="10"                                             # Uncomment this and comment the above to specify the limit in whole GB

# Update warning messages
# Modify as desired, putting the %d replacement operator where the number belongs
#msgWarnUpdateMinutes="This ARK server will shutdown for an update in %d minutes"
#msgWarnUpdateSeconds="This ARK server will shutdown for an update in %d seconds"
#msgWarnRestartMinutes="This ARK server will shutdown for a restart in %d minutes"
#msgWarnRestartSeconds="This ARK server will shutdown for a restart in %d seconds"
#msgWarnShutdownMinutes="This ARK server will shutdown in %d minutes"
#msgWarnShutdownSeconds="This ARK server will shutdown in %d seconds"
msgWarnCancelled="Restart cancelled by player request"

msgWarnReason="This ARK server will {reason} in {time}"
msgTimeMinutes="{minutes} minutes"
msgTimeSeconds="{seconds} seconds"
msgReasonUpdateApp="restart for an update to ARK"
msgReasonUpdateMod="restart for an update to mod(s): {modnamesupdated}"
msgReasonUpdateAppMod="restart for an update to the game and an update to mod(s): {modnamesupdated}"
msgReasonRestart="restart"
msgReasonShutdown="shutdown for maintenance"

# Notifications
# discordWebhookURL="https://discordapp.com/api/webhooks/{webhook.id}/{webhook.token}"
# notifyMsgShuttingDown="Shutting down"
# notifyMsgStarting="Starting"
# notifyMsgServerUp="Server is up"
# notifyMsgStoppedListening="Server has stopped listening - restarting"
# notifyMsgServerTerminated="Server exited - restarting"
# notifyTemplate="Message from instance {instance} on server {server}: {msg}"
# noNotifyWarning=true

# Restart cancel chat command
chatCommandRestartCancel="/cancel"

# ARK server common options - use ark_<optionname>=<value>
# comment out these values if you want to define them
# inside your GameUserSettings.ini file
#serverMap="TheIsland"                                               # server map (default TheIsland)
#serverMapModId="469987622"                                         # Uncomment this to specify the Map Mod Id (<fileid> in http://steamcommunity.com/sharedfiles/filedetails/?id=<fileid>)
#ark_TotalConversionMod="496735411"                                 # Uncomment this to specify a total-conversion mod
#ark_RCONEnabled="True"                                              # Enable RCON Protocol
#ark_ServerPassword=""                                               # ARK server password, empty: no password required to login
#ark_ServerAdminPassword="keyboardcat"                               # ARK server admin password, KEEP IT SAFE!
#ark_MaxPlayers="70"
#ark_GameModIds="487516323,487516324,487516325"                     # Uncomment to specify additional mods by Mod Id separated by commas
#ark_AltSaveDirectoryName="SotF"                                    # Uncomment to specify a different save directory name

# ARK server flags - use arkflag_<optionname>=true
#arkflag_OnlyAdminRejoinAsSpectator=true                            # Uncomment to only allow admins to rejoin as spectator
#arkflag_DisableDeathSpectator=true                                 # Uncomment to disable players from becoming spectators when they die

# ARK server options - i.e. for -optname=val, use arkopt_optname=val
#arkopt_StructureDestructionTag=DestroySwampSnowStructures
arkflag_serverlog=true

# config Service
logdir="/var/log/arktools"                                          # Logs path (default /var/log/arktools)

# steamdb specific
appid=376030                                                        # Linux server App ID
mod_appid=346110                                                    # App ID for mods

# Mod OS Selection
mod_branch=Windows
# Add mod-specific OS selection below:
#mod_branch_496735411=Windows

# alternate configs
# example for config name "ark1":
#configfile_ark1="/path/to/config/file"

defaultinstance="RodiniaSub"

**Comment by klightspeed** [comment]
Be aware that steamcmd stores its data (including mods) in its own directory in the user's home directory.  Running concurrent steamcmd commands under the same user can cause problems.

There is no option that I am aware of to change where steamcmd downloads mods.  The staging directory is used by arkmanager as the download directory for the steamcmd `app_update` command, and for extracting workshop mods from steamcmd's workshop directory.
