### ISSUE TITLE
Is server configuration broken?

### ISSUE THREAD

**Issue by dirkniblick** [arkmanager/ark-server-tools#999]
I run a dedicated server on CentOS 7 for my son and his friends.  He asked me to update it last night.  Since then, I've been trying to configure arkmanager and, by extension, the ark server with the configs I had running a couple months ago.  So far, I've been unable to use arkmanager to configure **any** options in /etc/arkmanager/arkmanager.cfg or /etc/arkmanager/instances/main.cfg.  An extremely basic one is MaxPlayers.  I want to set it to 12 (or anything).  I've added in /etc/arkmanager...
```
arkmanager.cfg:ark_MaxPlayers="12"
instances/main.cfg:ark_MaxPlayers="12"
instances/main.cfg:arkflag_MaxPlayers="12"
instances/main.cfg:arkopt_MaxPlayers="12"
```
...and none of this works.  I added the arkflag and arkopt lines out of desperation and it still didn't work.  I see MaxPlayers is set in the process...

`/opt/steam/ARK/instances/main/ShooterGame/Binaries/Linux/ShooterGameServer Ragnarok?RCONEnabled=True?RCONPort=32330?SessionName=ark.spolem.net?Port=7777?QueryPort=27015?ServerPassword=xxx?ServerAdminPassword=xxx?MaxPlayers=12?...`

...but the status still shows 70 players.  The Game.ini is empty and the GameUserSettings.ini gets rewritten every time I restart the server (despite there being a "version=5" in there).

Now, I realize that the ark dedicated server isn't really great software/code in the first place so I don't know where the problem lies, but I don't seem to be able to get arkmanager to function like it should and/or did just a few months ago.  Is there something I'm doing incorrectly here?

**Comment by klightspeed** [comment]
Are you adding any settings to GameUserSettings.ini yourself?

Are any of the options you are setting getting written to GameUserSettings.ini?

The fact that the options are on the command-line suggests that either the server is failing to process an option and any following options are ignored, or whatever is causing it to write the default config (which could be an error during option processing) is causing it to ignore options passed on the command-line.

If you go down the options, which one is the last one the server correctly processes?

**Comment by klightspeed** [comment]
What editor are you using to write `GameUserSettings.ini`?  It should be writing the file as ASCII with no accented characters and without a UTF8 byte order mark.  I.e. if you pipe the file into `xxd` or `od -tx1`, the first byte should be `5b` (`[`).

Does it work if you change the SessionName to one without a domain?

Does it work if you try using a clean `GameUserSettings.ini` and only use the command-line up to and including `MaxPlayers=12`, possibly changing the SessionName to one without a domain?

**Comment by dirkniblick** [comment]
I'm using VIM to edit the files so I should be good there.  I can make the SessionName whatever I want and it'll change or MaxPlayers even, which really isn't the problem.  What I want to change are things like LayEggIntervalMultiplier, PlayerHarvestingDamageMultiplier, etc. and these are things I can't change at the command line.

**Comment by klightspeed** [comment]
Those settings are `Game.ini` settings, and not `GameUserSettings.ini` settings.  The options on the command-line map to `GameUserSettings.ini` settings.

Unknown options in `GameUserSettings.ini` can cause the server to reject the config.

See ark.gamepedia.com/Server_Configuration for what options go where.

**Comment by klightspeed** [comment]
It looks like that website has `KickIdlePlayersInterval` in the wrong file - from what I can find, KickIdlePlayersPeriod is a `GameUserSettings.ini` config option and not a `Game.ini` config option.

Note that settings from `Game.ini` are _not_ copied by the server to `GameUserSettings.ini`.

**Comment by dirkniblick** [comment]
Is there a more accurate website for this information?  For such a money maker, ARK has some pretty terrible documentation.

**Comment by klightspeed** [comment]
I don't know.  All of the documentation available has been pieced together by the community from the sparse patch notes provided by Wildcard.

Note that arkmanager is also a community project, and is not supported by or affiliated with Wildcard.

**Comment by dirkniblick** [comment]
Oh, I understand all of that.  Believe me, I'm not angry with anyone.  I just want to know what it is that I'm doing wrong but it seems nobody really knows what the Dedicated Server actually does besides the developers.

**Comment by CaspyBXL** [comment]
@dirkniblick 
I can propose help this weekend if you want.
We could set up some kind of vocal (teamspeak/skype/whatsapp) and I could join a Teamviewer session or Anydesk session where you have control and I have vision. So I could better understand what you are doing wrong or placing wrongly if you still need the help ofc !

**Comment by LotekHeavy** [comment]
just a side note. I had the problem, too that my Ragnarok Server always display 0/70 Players and I could never connect. The solution was that in my case I wrote for the serverMap="Ragnorak" (Ragnarok would be correct), and I was looking in the config files and firewals one hour without seeing it :-)

**Comment by BBarfryyy** [comment]
Hello,
It seems i have the same issue... except im not running my server on centos but ubuntu, and without ark manager. Did someone find the solution ?
Thank you

**Comment by CaspyBXL** [comment]
@BBarfryyy 
All I can say that it is probably one of the parameters or options that is not correct in writing or in the wrong .ini
So the Game resets the config to default ones.

Hopes this helps !

Greetings,

**Comment by BBarfryyy** [comment]
Thanks for your answer, I already think about this, but it still keeps resetting after restart... When I just change maxplayer from 70 to 10 for example, and start the server, pouf, it come back to 70... Same with others settings

**Comment by CaspyBXL** [comment]
@BBarfryyy 
Since u are using Ubuntu and not using ArkManager kinda hard to say.
Something is getting written to console or commandline that gets also written in one of the .ini files I would say.
In the past I saw some people strugle with the sessionnames if they use special characters or something.
Then again hard to say we would have to look atso many factors. I still want to help, but i'm not sure this is the place to talk about this since you are not using Arkmanager, we have to respect the github and move this conversation.

You can add me on discord : 
CaspyMaster#3448
So we can chat without spamming this conversation.
